### ISSUE TITLE
Scroll list height doesn't get adjusted when the keyboard is visible

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#106]

**Comment by jamesr** [comment]
I think we're supposed to set android:windowSoftInputMode="adjustResize" in our AndroidManifest.xml and then respond to the view resizes that android generates for us

**Comment by HansMuller** [comment]
I've been testing against a version of Mojo with windowSoftInputMode="adjustResize". My app and the Sky stocks app work OK with this setting.  In my case it's essential.  I will submit a patch.

**Comment by jamesr** [comment]
That'd be great!

**Comment by HansMuller** [comment]
https://codereview.chromium.org/1056133007/

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#147
