### ISSUE TITLE
Android apptests and mojo/tools/android_mojo_shell.py serve up stale apps

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#109]
I've noticed that if I run MojoShell.apk using mojo/tools/android_mojo_shell.py and switch between --debug and --release builds it'll sometimes (often?) end up running the wrong one on the device.  To test I added logging to mojo_shell, surfaces_app and surfaces_child_gl_app and then ran a few times alternating between --release and --debug.

First I run with --release and get the release version of everything:

$ ./mojo/tools/android_mojo_shell.py --release mojo:surfaces_app
3989 KB/s (4139413 bytes in 1.013s)
	pkg: /data/local/tmp/MojoShell.apk
	ver: -i
Success
starting http for /ssd/mojo/src/out/android_Release
local port= 55281
--------- beginning of main
--------- beginning of system
I/chromium( 8452): [INFO:main.cc(185)] *** SHELL IS RELEASE ***
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/tracing.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.QE9Vu9
I/chromium( 8452): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/tracing.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.QE9Vu9
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.63pbhN
I/chromium( 8452): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.63pbhN
[0421/100232:INFO:surfaces_app.cc(126)] *** SURFACES_APP IS RELEASE ***
I/chromium( 8452): [0421/100232:INFO:surfaces_app.cc(126)] *** SURFACES_APP IS RELEASE ***
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.22i75Y
I/chromium( 8452): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.22i75Y
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_gl_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.iHInUa
I/chromium( 8452): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_gl_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.iHInUa
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_service.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.xrcmhV
I/chromium( 8452): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_service.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.xrcmhV
[0421/100232:INFO:child_gl_app.cc(59)] *** SURFACES_CHILD_GL_APP IS RELEASE (4) ***
I/chromium( 8452): [0421/100232:INFO:child_gl_app.cc(59)] *** SURFACES_CHILD_GL_APP IS RELEASE (4) ***

then I run as --debug and get the debug version of the shell and of surfaces_child_gl_app but the release version of surfaces_app:

$ ./mojo/tools/android_mojo_shell.py --debug mojo:surfaces_app
4193 KB/s (4684265 bytes in 1.090s)
	pkg: /data/local/tmp/MojoShell.apk
	ver: -i
Success
starting http for /ssd/mojo/src/out/android_Debug
local port= 48616
--------- beginning of main
--------- beginning of system
I/chromium( 8584): [INFO:main.cc(187)] *** SHELL IS DEBUG ***
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/tracing.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.MsoQ9C
I/chromium( 8584): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/tracing.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.MsoQ9C
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.GURrYL
I/chromium( 8584): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.GURrYL
[0421/100306:INFO:surfaces_app.cc(126)] *** SURFACES_APP IS RELEASE ***
I/chromium( 8584): [0421/100306:INFO:surfaces_app.cc(126)] *** SURFACES_APP IS RELEASE ***
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.TqgNLX
I/chromium( 8584): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.TqgNLX
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_service.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.suygPC
I/chromium( 8584): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_service.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.suygPC
[INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_gl_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.fqdTMQ
I/chromium( 8584): [INFO:network_fetcher.cc(73)] Caching mojo app http://127.0.0.1:31337/surfaces_child_gl_app.mojo at /data/data/org.chromium.mojo.shell/cache/tmp/.org.chromium.Chromium.fqdTMQ
[0421/100307:INFO:child_gl_app.cc(61)] *** SURFACES_CHILD_GL_APP IS DEBUG (4) ***
I/chromium( 8584): [0421/100307:INFO:child_gl_app.cc(61)] *** SURFACES_CHILD_GL_APP IS DEBUG (4) ***

Obviously this is very confusing when trying to debug issues as sometimes you'll build and not run the code you thought you were.  It's unclear what layer is doing the bad caching here.  I'm testing without --predictable-app-filenames

/cc @qsr @eseidelGoogle

**Comment by jamesr** [comment]
I still get issues with --predictable-app-filenames.  I tried running first in release and got release versions of everything, then ran in debug and got a debug shell but release versions of *both* apps.  The SHA256 of the apps was the SHA256 of the release versions in both cases.  This leads me to believe the network service is caching http://127.0.0.1:31337/surfaces_app.mojo etc even though the web server is running out of a different directory on the host.

**Comment by jamesr** [comment]
skydb uses the skygo HTTP server which sets "Cache-Control: no-cache".  We should do that (or just use skydb instead android_mojo_shell.py)

**Comment by jamesr** [comment]
mojob.py test uses the same python logic for the web server which means that apptests running on Android will use arbitrarily old binaries for mojo apps when running.

**Comment by eseidelGoogle** [comment]
BTW, we recently had (unrelated) caching errors in SkyShell which caused us to add the Cache-Control: no-cache to sky_server.

**Comment by jamesr** [comment]
Thanks for adding ETag support - that's cool.  However I'm disappointed you added this to the Python web server.  The sky team learned several months ago that the python HTTP server was way too slow to run their tests - it was taking multiple seconds to return resources and tests were timing out.  They wrote a very simple HTTP server in Go that's in sky/tools/skygo and is much faster.  We really should use this server everywhere and add new features like ETag support to it, not the python one.

**Comment by eseidelGoogle** [comment]
I'd rather dump both and use Apache or some other server written by team of people who care about servers. :)  The Go sky_server is a unique snowflake, and in being so ends up being a source of bugs.  Writing an http server is not where Sky (or mojo) adds value to the world. :)

**Comment by ppiet** [comment]
On the other hand, Apache or any other production-ready http server might be an overkill in the context of serving static files for testing. I wonder what Chromium ended up using, the last I remember they had 3 different test servers...
