### ISSUE TITLE
skydb needs to be updated for Android mojo shell change

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#117]
For the Android mojo shell build, we no longer produce a `mojo_shell` "binary", but instead just produce `libmojo_shell.so`.

skydb still assumes it does:
* It checks the build directory for `mojo_shell`. (We could change it to check for `args.gn` instead, or something like that.)
* It symlinks `mojo_shell` to `libmojo_shell.so`. (I think this is safe to delete.)
* Its gdb support still refers to `mojo_shell`. (Probably the `file` command should be given `libmojo_shell.so` instead when on Android? But someone who actually uses its gdb support should figure this out.)

**Comment by viettrungluu-cr** [comment]
Hmmm, looks like someone fixed the first item above (but the others remain).

**Comment by abarth** [comment]
Closing this because mojo_shell.py has replaced skydb.
