### ISSUE TITLE
mojom: support enum constants?

### ISSUE THREAD

**Issue by yzshen** [domokit/mojo#121]
Currently the following won't work:

enum SomeEnum { VALUE_1 };
const SomeEnum kSomeEnumValue = SomeEnum.VALUE_1;

Probably we should support.

/cc @viettrungluu-cr

**Comment by viettrungluu-cr** [comment]
Hmmm, this is a dup of #607 (or vice versa), where more discussion has occurred. So I'll close this issue in favor of that one.
