### ISSUE TITLE
sky_tool fails badly when device is not found

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#124]
./packages/sky/sky_tool start --install                 [/tmp/demos/hello_widgets]
error: device not found
error: device not found
Traceback (most recent call last):
  File "./packages/sky/sky_tool", line 241, in <module>
    SkyShellRunner().main()
  File "./packages/sky/sky_tool", line 234, in main
    exit_code = args.func(args, pids)
  File "./packages/sky/sky_tool", line 128, in run
    if not self._is_package_installed(ANDROID_PACKAGE):
  File "./packages/sky/sky_tool", line 123, in _is_package_installed
    return subprocess.check_output(pm_path_cmd).strip() != ''
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['adb', 'shell', 'pm', 'path', 'org.domokit.sky.demo']' returned non-zero exit status 255

**Comment by ppiet** [comment]
You could use .CheckDevice() from devtoolslib.

```
from devtoolslib.android_shell import AndroidShell
(...)

    shell = AndroidShell(adb_path)
    device_status, error = shell.CheckDevice()
    if not device_status:
      print 'Device check failed: ' + error
      return 1
```

^ this should print out something informative when the device is missing or unavailable and shouldn't mind that you're not actually using MojoShell.apk.

**Comment by eseidelGoogle** [comment]
That would require us to ship the devtools python package inside our sky
dart pub package.  We might do that, but initially this script was intended
to be simple and standalone.

**Comment by ppiet** [comment]
Should this be moved to sky_engine issue tracker?

**Comment by eseidel** [comment]
Sorry, yeah, this is long out of date now.
