### ISSUE TITLE
Go build for android is spammy

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#125]
Building for android now produces the following new output in a successful build:

[80/219] ACTION //examples/go:go_echo_client_go(//build/toolchain/android:arm)
# command-line-arguments
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-RzGV5O/go.o for Cortex-A8 erratum because it has no mapping symbols.
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-RzGV5O/go.o for Cortex-A8 erratum because it has no mapping symbols.
[84/219] ACTION //examples/go:go_http_handler_go(//build/toolchain/android:arm)
# command-line-arguments
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-sx9X1N/go.o for Cortex-A8 erratum because it has no mapping symbols.
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-sx9X1N/go.o for Cortex-A8 erratum because it has no mapping symbols.
[88/219] ACTION //examples/go:go_echo_server_go(//build/toolchain/android:arm)
# command-line-arguments
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-Ksb06T/go.o for Cortex-A8 erratum because it has no mapping symbols.
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-Ksb06T/go.o for Cortex-A8 erratum because it has no mapping symbols.
[104/219] ACTION //examples/go:go_http_server_go(//build/toolchain/android:arm)
# command-line-arguments
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-32T5Qy/go.o for Cortex-A8 erratum because it has no mapping symbols.
/ssd/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-32T5Qy/go.o for Cortex-A8 erratum because it has no mapping symbols.

Successful builds should produce no output (this isn't true for some of the Java stuff right now but that's being worked on).  Can you figure out how to fix or suppress this warning, @rogulenko ?

**Comment by ppiet** [comment]
This appears to be fixed now.
