### ISSUE TITLE
sky_tool tracing writes to /data which requires root to read

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#127]
When I run stop_tracing, I see this in the log:

W/adbd    (15894): type=1400 audit(0.0:669): avc: denied { getattr } for path="/data/data/org.domokit.sky.demo/cache/sky-trace-2015-04-28-184035.json" dev="mmcblk0p28" ino=115568 scontext=u:r:adbd:s0 tcontext=u:object_r:app_data_file:s0 tclass=file

There must be a way to do this in production builds.

@jamesr @qsr @abarth

**Comment by jamesr** [comment]
is /data/data/org.domokit.sky.demo/cache/tmp/ writable as non-root?

**Comment by eseidelGoogle** [comment]
The problem is earlier than that.  adb can't even access /data

% adb shell ls /data
opendir failed, Permission denied

**Comment by eseidelGoogle** [comment]
Might be able to hack around it with run-as?

http://blog.shvetsov.com/2013/02/access-android-app-data-without-root.html

**Comment by jamesr** [comment]
skydb's stop_tracing exfiltrates the data over http served from the app on the device so that adb doesn't need to see it. Could you do this in sky_tool as well?

**Comment by eseidelGoogle** [comment]
Presumably we could, yes.

**Comment by abarth** [comment]
Yeah, I couldn't find a place to write the trace file on disk that adb had permission to pull it.  Chrome solves this problem using the sdcard I think.

**Comment by ppiet** [comment]
Should this be moved to sky_engine issue tracker?

**Comment by abarth** [comment]
There's another version of this issue there already.
