### ISSUE TITLE
Sky SDK Demo Example Getting 404s

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#128]
I am attempting to following the instructions in the README.md at https://github.com/domokit/sky_sdk.

I cd into my sky_sdk directory and issue the command:
packages/sky/lib/sky_tool start --install examples/stocks/main.sky

and I see the output below that contains 404 errors. The problem appears to be the path is wrong. It should be "packages/sky/lib/framework/components" instead of "packages/sky/framework/components".

2502 KB/s (7094229 bytes in 2.767s)
	pkg: /data/local/tmp/SkyDemo.apk
Success
Serving HTTP on 0.0.0.0 port 9888 ...
Starting: Intent { act=android.intent.action.VIEW dat=sky://localhost:9888/main.sky }
rudominer@caerus:~/sky_sdk$ 127.0.0.1 - - [28/Apr/2015 14:07:12] "GET /main.sky HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2015 14:07:12] "GET /lib/stock_app.dart HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2015 14:07:12] code 404, message File not found
127.0.0.1 - - [28/Apr/2015 14:07:12] "GET /packages/sky/framework/components/action_bar.dart HTTP/1.1" 404 -
127.0.0.1 - - [28/Apr/2015 14:07:12] code 404, message File not found
127.0.0.1 - - [28/Apr/2015 14:07:12] "GET /packages/sky/framework/components/drawer.dart HTTP/1.1" 404 -

**Comment by MitchRudominer** [comment]
I'm less confident about my diagnosis of the problem above under "The problem appears to be...".

**Comment by MitchRudominer** [comment]
The problem seems to be that the HTTP server's root is the "stocks" folder.

**Comment by eseidelGoogle** [comment]
This was a problem yesterday, but I thought it was fixed?  Can you pull again?

**Comment by eseidelGoogle** [comment]
Ah, I see the problem.  The instructions are wrong.  I'll fix them.
You want to be in teh stocks directory after having run pub get.

cd examples/stocks
pub get
./packages/sky/sky_tool start

**Comment by MitchRudominer** [comment]
I think multiple issues are going on perhaps. One of them may be user error
on my part. I did not run "pub get" at all because the instructions that
mentioned "pub get" were in the section describing how I should write a new
Sky application but I was not trying to write a new Sky application--I was
trying to run an existing Sky application.

So was I supposed to run "pub get"?

**Comment by eseidelGoogle** [comment]
https://codereview.chromium.org/1110283002

**Comment by eseidelGoogle** [comment]
The problem is all of these examples were written expecting skydb or shelldb which use sky_server as a magical http server which knows how to inject a /packages path.  sky_tool isn't that smart.  So users working out of the SDK will need to pub get.

**Comment by eseidelGoogle** [comment]
Hopefully the instructions are now more clear?
