### ISSUE TITLE
SkyDemo.apk uses the log tag 'chromium'

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#129]
SkyDemo.apk uses the log tag 'chromium'

I feel silly every time I type 'adb logcat -s chromium' to see just the logs from SkyDemo.apk.

Should be easy to fix.

**Comment by jamesr** [comment]
I assume that these log messages are bottoming out in the LOG macro which gets the "chromium" tag here:

https://github.com/domokit/mojo/blob/master/base/logging.cc#L579

we could change this and carry a patch (which imo wouldn't be that bad) but it'd mean carrying a patch against //base, which we haven't needed to do yet.

**Comment by ppiet** [comment]
Is this fixed by f409a9cc36b48da1853b1074b30be8e526d11cd3 ? If not, should this issue be moved to sky_engine tracker?

**Comment by ppiet** [comment]
Assuming obsolete.
