### ISSUE TITLE
Build system should be able to run dartanalyzer for sky code

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#143]
When writing a dart mojo app (that runs in the dart content handler), I can package it with a `dart_package` or `dart_packaged_app` build rule that runs the dartanalyzer at build time.

I'd like to be able to do the same for dart code that runs in sky_viewer. Naively, it seemed like simply putting the sky source in a `dart_package` would do the trick, but the analyzer fails to recognize `import 'dart:sky;'`.

It looks to me like this is caused by the fact that `tools/dart/patch_sdk.diff` sets up the sky library to point to the generated out/Debug directory:
```
+  "sky": const LibraryInfo(
+      "../../../../out/Debug/gen/sky/bindings/dart_sky.dart",
+      maturity: Maturity.STABLE),
```

This masks the bug when building mojo in debug mode, but it breaks when building another configuration or when consuming mojo in another repo. Since `dart_sky.dart` is a generated file, it isn't clear to me at all what the right fix here is. Ideas?

/cc @colinblundell @eseidel @HansMuller @jamesr @johnmccutchan @sethladd

**Comment by eseidelGoogle** [comment]
My understanding is the Dart VM team has an OKR this quarter about adding support for some sort of "SDK additions" to allow pub packages to provide bindings like "sky:dart" for the analyzer to understand. @iposva-google may be able to link you to the bug/spec/etc.

**Comment by eseidelGoogle** [comment]
http://dartbug.com/23393

**Comment by sethladd** [comment]
Yes, we're going to provide a "real" fix for this. Sorry for the troubles in the meantime. Stay tuned!

**Comment by tonygentilcore** [comment]
Thanks to @johnmccutchan and @colinblundell , we have a solution for this now so I'm going to close this out. As Eric mentioned there's room for further polish.
