### ISSUE TITLE
Need iOS port of Sky

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#145]
Need iOS port of Sky

I'm sure this will have a ton of blockers. Not sure if Github's issue tracker supports that, but I'll try.

@chinmaygarde

**Comment by eseidelGoogle** [comment]
I don't think gn works on mac: http://crbug.com/431177 So I would recommend we use just a plain xcode project for now to get going.  @dpranke

**Comment by dpranke** [comment]
GN works to some degree on the Mac; you can build regular libraries and executables just fine.

However, framework and bundle support is still missing. It probably isn't too hard to add such support, but someone needs to work out the details of the design. I can't say whether that will be easier or harder than bringing up a separate xcode build for mojo, but if you wanted to help on the GN work it would probably at least be more forward-looking.

**Comment by jamesr** [comment]
I think getting GN going will be a lot easier than trying to deal with xcode

**Comment by jamesr** [comment]
@eseidelGoogle could I suggest that we do the iOS bringup including GN changes in a branch off the mojo tree, then try to figure out the GN integration bits with @dpranke or another kind volunteer with GN experience to see if we can land it as-is in chromium?  I'd like to minimize divergence in build system stuff while also making sure @chinmaygarde can make rapid progress.

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by eseidelGoogle** [comment]
Agreed.  I'm going to encourage @chinmaygarde to dive straight to green square as fast as possible.  Which likely means using Xcode and his own custom branch.  Once we see the green at the end of that tunnel, we'll back track to how we actually make the rest of the world play nice with iOS.

**Comment by abarth** [comment]
I'm not sure it's useful to keep this issue open.  We'll probably need an iOS label to track issues relating to the now-existing iOS version.
