### ISSUE TITLE
dart_pub_get.py step for gclient sync fails on Mac

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#146]
dart_pub_get.py step for gclient sync fails on Mac

Needed for #145.

Investigating.  @zanderso @tonygentilcore 

________ running '/usr/bin/python src/mojo/public/tools/git/dart_pub_get.py --repository-root ../../../.. --dart-sdk-directory ../../../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/' in '/src/mojo'
Traceback (most recent call last):
  File "src/mojo/public/tools/git/dart_pub_get.py", line 81, in <module>
    sys.exit(main(_repository_root, _dart_sdk_path, args.dirs_to_ignore))
  File "src/mojo/public/tools/git/dart_pub_get.py", line 49, in main
    pub_get(dart_sdk_path_from_root, os.path.dirname(f))
  File "src/mojo/public/tools/git/dart_pub_get.py", line 30, in pub_get
    env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/src/mojo/src/mojo/public/tools/git/../../../../third_party/dart-sdk/dart-sdk/bin/pub', 'get']' returned non-zero exit status 1
Error: Command /usr/bin/python src/mojo/public/tools/git/dart_pub_get.py --repository-root ../../../.. --dart-sdk-directory ../../../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/ returned non-zero exit status 1 in /src/mojo

**Comment by eseidelGoogle** [comment]
Looks like the problem is that:
/src/mojo/src/third_party/dart-sdk/dart-sdk/bin/dart
is an elf binary. I guess we need to teach gclient how to pull down the right dart-sdk for mac.

**Comment by eseidelGoogle** [comment]
Looks like src/tools/dart/update.py is the tool which pulls in the SDK binaries.  Looks like its hard-coded for Linux 64 but could be taught about other platforms.  Originally written by @eglaysher, I'm happy to look into updating it.

**Comment by jamesr** [comment]
@cstout and I have a set of patches that can build nearly all of our code from a mac targetting Android.  A good portion of this is probably useful for cross-compilation from a Mac in general

**Comment by eseidelGoogle** [comment]
Hit me with your best patches!

**Comment by eseidelGoogle** [comment]
Nevermind.  I was working from the dart_summit branch and this has been fixed since. :(
