### ISSUE TITLE
Link to examples, from sky's sdk README, is 404

### ISSUE THREAD

**Issue by sethladd** [domokit/mojo#153]
From https://github.com/domokit/mojo/tree/master/sky/sdk#examples

Click the link "examples directory"

Expected: a view of the examples directory

Actual: 404

**Comment by MitchRudominer** [comment]
I see the examples directory when I click on the link.

**Comment by sethladd** [comment]
Hm. Go to https://github.com/domokit/mojo/tree/master/sky/sdk

Then, find "For examples, please see the examples directory."

Clicking on "examples directory" links me to https://github.com/domokit/mojo/blob/master/sky/sdk/examples which is a 404 for me.

**Comment by MitchRudominer** [comment]
Sorry, you are right. I get a 404 too.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#114
