### ISSUE TITLE
No way to hook into Android's Back button from Sky

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#155]
No way to hook into Android's Back button from Sky

**Comment by eseidelGoogle** [comment]
Right now our back button behavior is awful.  We just go back to the Android launcher.  This is probably the most noticeable bug with SkyDemo.

**Comment by abarth** [comment]
We now get an even when the use taps the back button.  However, there's no way to trigger the normal Android "back" behavior if you won't want to consume the back event.

**Comment by collinjackson** [comment]
I believe Adam is planning to expose a finish() API that can be called if the back stack is empty
