### ISSUE TITLE
Sky SDK analyze error: fn.dart hides dart_sky.dart

### ISSUE THREAD

**Issue by colinblundell** [domokit/mojo#158]
Running the Dart analyzer on a file that imports "dart:sky" followed by "package:sky/framework/fn.dart" results in the following error:

[warning] Element 'Text' from SDK library 'dart_sky.dart' is implicitly hidden
by 'fn.dart

@Hixie @eseidel

**Comment by Hixie** [comment]
This is going to solve itself once Text is dropped from dart:sky, but in the meantime, just import dart:sky with an identifier (e.g. "as sky").

**Comment by ppiet** [comment]
Assuming this is obsolete now.
