### ISSUE TITLE
Checkboxes in PopupMenuItems don't respond to taps on the menu item

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#162]
The checkbox control doesn't automatically get checked when you tap on a menu item that contains it.

**Comment by abarth** [comment]
This is fixed in stocks2.

**Comment by Hixie** [comment]
No it's not. :-)

**Comment by abarth** [comment]
Apparently this bug isn't about tapping on the checkbox itself but upon the text associated with the check box.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#105
