### ISSUE TITLE
SkyShell crashes repeatedly when attempting to start with device screen off

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#173]
SkyShell crashes repeatedly when attempting to start with device screen off

adb logcat -c && ./sky/tools/shelldb start out/android_Release sky/dream.dart && adb logcat

Gets a ton of this spam:

I/chromium( 2209): [INFO:builtin_natives.cc(165)] CONSOLE: Observatory listening on http://127.0.0.1:48395
E/        (  185): process stopped due to unexpected signal 27
I/WindowState(  764): WIN DEATH: Window{3795e98d u0 org.domokit.sky.demo/org.domokit.sky.demo.SkyDemoActivity}
W/WindowManager(  764): Force-removing child win Window{35849189 u0 SurfaceView} from container Window{3795e98d u0 org.domokit.sky.demo/org.domokit.sky.demo.SkyDemoActivity}
W/WindowManager(  764): Failed looking up window
W/WindowManager(  764): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@80b9742 does not exist
W/WindowManager(  764): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8514)
W/WindowManager(  764): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8505)
W/WindowManager(  764): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
W/WindowManager(  764): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  764): WIN DEATH: null

@abarth @qsr 

I'm not sure why it appears to be repeatedly attempting to restart.  I'm not aware of code to do that in shelldb.

**Comment by ppiet** [comment]
Should this be moved to sky_engine issue tracker, or is obsolete now?

**Comment by abarth** [comment]
Fixed.
