### ISSUE TITLE
convert RenderNode to points and rects where appropriate

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#177]
We should have code like  "rect.contains(point)" rather than "x < 0.0 || x >= width || y < 0.0 || y >= height".

**Comment by eseidelGoogle** [comment]
@mpcomplete already started some of this.

**Comment by abarth** [comment]
From use in RenderNode, we'll probably want a Rect class that's a pure Dart object...  We might need to study some microbenchmarks to see if we can share that with the painting API.

**Comment by abarth** [comment]
I did this.
