### ISSUE TITLE
Should not need to install 'requests' to use skydb

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#181]
Chromium has a magical way of depending on third_party python libraries.  Presumably through a virtualenv.  I've forgotten how that works, but we need something to make it so that folks don't have to `pip install requests` in order to run skydb.

@jamesr

**Comment by abarth** [comment]
Closing as WONTFIX given that skydb (now called mojodb) is going to be replaced with mojo_shell.py Real Soon Now.
