### ISSUE TITLE
Go build is very spammy

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#182]
I'm not sure who maintains the mojo Go build.  @jamesr?

# command-line-arguments
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-nS5xeP/go.o for Cortex-A8 erratum because it has no mapping symbols.
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-nS5xeP/go.o for Cortex-A8 erratum because it has no mapping symbols.
[1014/2578] ACTION //examples/go:go_echo_server_go(//build/toolchain/android:arm)
# command-line-arguments
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-gf6gKT/go.o for Cortex-A8 erratum because it has no mapping symbols.
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-gf6gKT/go.o for Cortex-A8 erratum because it has no mapping symbols.
[1231/2578] ACTION //examples/go:go_http_handler_go(//build/toolchain/android:arm)
# command-line-arguments
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-2Q8LkV/go.o for Cortex-A8 erratum because it has no mapping symbols.
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-2Q8LkV/go.o for Cortex-A8 erratum because it has no mapping symbols.
[1245/2578] ACTION //examples/go:go_http_server_go(//build/toolchain/android:arm)
# command-line-arguments
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-gPc0zy/go.o for Cortex-A8 erratum because it has no mapping symbols.
/src/mojo/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 1 of /var/tmp/go-link-gPc0zy/go.o for Cortex-A8 erratum because it has no mapping symbols.

**Comment by ppiet** [comment]
This appears to be fixed now.
