### ISSUE TITLE
Consider presubmit check to format dart code

### ISSUE THREAD

**Issue by mpcomplete** [domokit/mojo#187]
Dart has a great code formatting tool. We have it checked in to third_party/dart-sdk/dart-sdk/bin/dartfmt . Let's run it over any .dart code before submitting.

Here's a script the dart guys use for this purpose: https://github.com/dart-lang/dartdoc/blob/master/tool/ensure_dartfmt.sh .

**Comment by viettrungluu-cr** [comment]
Isn't git cl format already formatting dart code?

In which case, we just have to enforce dart code being formatted....

**Comment by mpcomplete** [comment]
Ah, so it does. I'm going to close this, since turning that into a presubmit is not that useful.
