### ISSUE TITLE
ViewManagerClient needs to remove child views on embedding

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#188]
When ViewManagerClient embeds a new Mojo app into a View, the ViewManagerServer will not invoke OnViewHierarchyChanged() on that client. This is by design because the server knows that the client knows that the view hierarcy is changing since it was the one that requested the change. But this means that the client has the responsibility to remove the child views.

**Comment by MitchRudominer** [comment]
Here is a concrete symptom I was seeing: Suppose a Sky app P uses two I-frames to embed Sky apps C1 and C2 into two child views. Now suppose that Sky app C2 invokes window_manager.ptr.embed() to replace the contents of the root view with another Sky app P2. Then P2 will not be able to respond to user input (such as mouse-clicks or taps) and C1 and C2 will continue to respond to the user input even though they are no longer visible. This came up when I was working on a Home button for Modular.

The explanation for the symptom is that the ViewManagerClient's copy of the view tree still includes C1 and C2 and so when it routes input events it routes it to them.
@eseidel, @domokit/modular-team

**Comment by MitchRudominer** [comment]
@sky2  Scott feel free to correct my description of the problem.

This issue will be fixed by https://codereview.chromium.org/1160733003/

**Comment by sky2** [comment]
The reason the server doesn't notify the client of the remove is that the server assumes the client is doing the same action as the server. This is true of all the other client calls too. So, the bug is in the client lib. The client lib should be removing all children before it calls to the server.

**Comment by MitchRudominer** [comment]
Fixed
