### ISSUE TITLE
authentication.mojo spam on every test

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#190]
mojo_shell seems to request an /authentication.mojo for every mojo file.
https://github.com/domokit/mojo/blob/master/shell/application_manager/application_manager.cc#L202

This seems like a bad idea, similar to how favicon.ico was a bad idea:
http://techblog.wimgodden.be/2011/02/22/how-a-bad-favicon-ico-can-cause-a-lot-of-trouble/

Right now it's just causing a ton of test spam.
[ERROR:application_manager.cc(375)] Library not started because library path '/src/mojo/src/out/Debug/authentication.mojo' does not exist.

Can we please remove this from mojo_shell?

@jamesr @viettrungluu-cr @colinblundell @qsr

**Comment by qsr** [comment]
You misread the code. This is not called for each mojo file, this is called once and only once per shell lifetime.

Also this is not related to favicon -> this is not building a new URL and trying to connect to it, this is connecting to a well known mojo application. Exactly the same way we are connecting to mojo:tracing on each shell invocation.

There is not authentication service on Linux, which is the reason for the error.

Will add a dummy authentication service for the moment. But I think this error should not be one (more like a debug) as this is expected that some URL that people will try to connect to will not have content.
