### ISSUE TITLE
Make dart analyzer hints fatal by default

### ISSUE THREAD

**Issue by alhaad** [domokit/mojo#191]
/cc @johnmccutchan @tonygentilcore 
This would include fixing up lots of already existing hint-erros.

Does it make sense delete code which is unused? Especially code is dart/sdk/lib/io like unused socket options?

**Comment by johnmccutchan** [comment]
Any hints under dart/sdk/lib/io will need to be ignored because it is core SDK core.

**Comment by tonygentilcore** [comment]
Including a link to the patch which turns hints on:
https://codereview.chromium.org/1151313007/

/cc @gabeschine @kulakowski

**Comment by Hixie** [comment]
Why does the SDK have dartanalyzer hints? Doesn't that mean either the SDK has issues or the analyzer has issues?

**Comment by kulakowski** [comment]
https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/socket.dart#L426

As I understood @alhaad , the issues were things like that option flag above that aren't used in the file, and it seemed like unsound analyzer warnings to me.

**Comment by Hixie** [comment]
Then we should fix the analyzer.

**Comment by tonygentilcore** [comment]
I understood from @sethladd that hints should be sound. Agree w/ Hixie that, if they aren't, we should probably hold off on enabling hints until they are.

**Comment by sethladd** [comment]
Hints don't necessarily mean a problem. For example, "unused variable" is a hint. The program will function just fine, but a developer probably wants to know about this feedback.

cc @bwilkerson

**Comment by bwilkerson** [comment]
Unless it's explicitly being asked to analyze files in the SDK, dartanalyzer shouldn't be reporting any errors/warnings/hints in the SDK. If it is, then we have a bug we need to fix.

> https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/socket.dart#L426
>
> As I understood @alhaad , the issues were things like that option flag above that aren't used in the file, and it seemed like unsound analyzer warnings to me.

I'm not sure why you think this is unsound. The field is private to the library (so it cannot be referenced from outside the library) and is never referenced inside the library. It might have been included for completeness, and the author might not want to delete it, but it's true that it isn't being used.

**Comment by kulakowski** [comment]
@bwilkerson I hadn't intended to point at a private field. I didn't have a transcript of Alhaad's error log, and only remembered that it was one of the the socket options. Thanks for looking at this.

**Comment by zanderso** [comment]
Is this issue stale? Please re-open if not. Thanks!
