### ISSUE TITLE
Find a better way to do the hashCode functions

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#193]
Rect, Point, Size, BorderSide, Border, EdgeDims, and BoxConstraints all have the same logic to do their hash codes.

@eseidelGoogle

**Comment by sethladd** [comment]
Quiver has hashCode builders: http://www.dartdocs.org/documentation/quiver/0.21.4/index.html#quiver/quiver-core

**Comment by abarth** [comment]
Duplicate of #236
