### ISSUE TITLE
Path: Expose reset() or rewind()

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#198]
...and then convert the border logic to use it, rather than recreating a new Path each time.

Is there some way we can detect when a new Path is being allocated in the same scope as a previous one, where the previous one isn't reused, to make this either automatic or at least catch it?

**Comment by eseidelGoogle** [comment]
Doesn't yet have either:
https://github.com/domokit/mojo/blob/master/sky/engine/core/painting/Path.idl

It's possible @iansf or @mpcomplete might be interested in this next time they're looking for a short bug.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#88
