### ISSUE TITLE
Canvas: expose drawPolygon()

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#199]
...and then convert the border logic to use it, rather than using a Path.

**Comment by eseidelGoogle** [comment]
Looks like it still doesn't:
https://github.com/domokit/mojo/blob/master/sky/engine/core/painting/Canvas.idl

It's possible @iansf or @mpcomplete may be interested in an easy afternoon change like this one at some point.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#85
