### ISSUE TITLE
No way to launch a sky app in mojo_shell.py

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#200]
I'm not quite sure how to launch a sky app in mojo_shell.py.  In mojodb.py I'd use:
./mojo/tools/mojob.py start out/Debug sky/examples/raw/hello_world.dart

I tried:
./mojo/tools/mojo_shell.py sky/examples/raw/hello_world.dart

[ERROR:native_application_support.cc(50)] Failed to load app library (error: /src/mojo/src/sky/examples/raw/hello_world.dart: invalid ELF header)

So presumably I need something like:
./mojo/tools/mojo_shell.py mojo:sky_viewer --args-for="mojo:sky_viewer,sky/examples/raw/hello_world.dart"

But then that doesn't seem to create a window.  Do I need to pass a window_manager as well?

@ppiet

**Comment by viettrungluu-cr** [comment]
Anything relying on being embedded (via the view manager interfaces) needs more than just mojo_shell(.py). This is normal for most apps that display stuff, except the few that talk to the native viewport directly.

For such apps, you need a window manager, and then tell it what to embed.

**Comment by viettrungluu-cr** [comment]
E.g.:
```
out/Debug/mojo_shell --url-mappings=mojo:window_manager=mojo:kiosk_wm --args-for='mojo:window_manager mojo:ganesh_app' mojo:window_manager
```

**Comment by tonygentilcore** [comment]
Could the runner make some of those things defaults, or is the idea that each consumer of the script wrap it in order to provide its own defaults? Ideally the user of the script wouldn't have to actually type all that.

**Comment by viettrungluu-cr** [comment]
If the idea is that mojo_shell.py is just like running the mojo_shell
binary, then it shouldn't do these things.

Probably there should be another wrapper for running the window manager +
app that expects to be embedded.

**Comment by ppiet** [comment]
I'd think that `mojo_shell.py` does not need to be just like running the mojo_shell binary - it is our (Mojo repository) embedder of the devtools library, and we should be able to add whatever layer of convenience we want there.

As of https://github.com/domokit/mojo/commit/875296552fa5f1d2d79da9d520d2ea597a592e9b and https://github.com/domokit/mojo/commit/a787771678b37e56a8c02e3186c09de37b43c5d0 , one can now run the Sky apps through mojo_shell.py by passing the --sky flag:

> mojo/tools/mojo_shell.py --sky sky/examples/raw/hello_world.dart
> mojo/tools/mojo_shell.py --sky sky/examples/raw/hello_world.dart --android

What do you guys think?

**Comment by ppiet** [comment]
PS If you are curious to see what mojo_shell.py is exactly doing with this flag, passing "-v" will print the constructed shell command, e.g.

`
$ mojo/tools/mojo_shell.py --sky sky/examples/raw/hello_world.dart -v
Shell arguments: ['--url-mappings=mojo:window_manager=mojo:kiosk_wm', 'mojo:debugger 7777', '--content-handlers=text/sky,mojo:sky_viewer,application/dart,mojo:sky_viewer', 'mojo:window_manager http://127.0.0.1:9998/sky/examples/raw/hello_world.dart']
`

Mapping of kiosk_wm as window manager is unrelated to --sky, it happens by default unless overriden by passing different --window-manager. Starting the mojo:debugger also happens by default unless --no-debugger is passed.
