### ISSUE TITLE
sky/examples/game has 150ms Dart GC pauses

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#202]
sky/examples/game has 150ms Dart GC pauses

Not sure if this is Dart's problem our Sky's problem or this example's problem or all of the above.  But the game noticeably janks every couple seconds as we drop 10 frames for a GC.

@iposva-google @vlidholt

**Comment by eseidelGoogle** [comment]
Here is an example trace with a single GC pause:
http://filebin.ca/247fiWDumeEI/sky-trace-2015-06-04-223906.json

**Comment by sethladd** [comment]
cc @kodandersson

**Comment by eseidelGoogle** [comment]
sky/tools/skydb start out/androidRelease sky/examples/game/main.dart
sky/tools/skydb start_tracing
sky/tools/skydb stop_tracing

Then open the resulting trace file in about:tracing in chrome.

**Comment by kodandersson** [comment]
I'm having some trouble producing a recent build of sky ("Failed to download Go tool binaries"), but I will try to reproduce this again tomorrow.

The stderr log output produced by adding the flag --verbose_gc to your dart invocation would be useful to diagnose this.

**Comment by eseidelGoogle** [comment]
I'm no longer seeing the 150ms GC pauses on tip of tree.  I believe because @vlidholt removed Box2d from the demo.  Here is a GC log of tip of tree:
https://gist.github.com/eseidelGoogle/6f34ad00d1f906a4245c

**Comment by eseidelGoogle** [comment]
I lied.  The GCs are still here.  Here is a trace showing a 140ms GC of the tip of tree game/main.dart.
http://filebin.ca/24mB9pMvoTAK/sky-trace-2015-06-10-171241.json

**Comment by eseidelGoogle** [comment]
Here is the patch I used to add --verbose_gc in case you'd like to do so locally:
https://gist.github.com/eseidelGoogle/7c1185d642acf8c14cad

**Comment by eseidelGoogle** [comment]
@kodandersson is this a bug you'd like to track separately from the planned GC re-write?  iirc you (or maybe @iposva-google) mentioned to me before vacation that the verbose log seemed large/odd.

This issue will block production Sky apps, but *definitely* does not block Sky development at current.

**Comment by kodandersson** [comment]
This should be tracked as a separate issue. The GC log shows ~150 ms pauses for collecting a 16 MB young generation, which is quite excessive. The timing breakdown shows most of that is spent processing weak references. I will try to get a detailed CPU profile.

How does Sky use weak references currently?

**Comment by iposva-google** [comment]
Daniel, thanks for identifying the surprisingly large number of weak references. Let's use this issue to track down the source of weak references. It would be interesting to see where these originate.

The general on-going GC rewrite does not need to be tracked in this issue.

**Comment by eseidelGoogle** [comment]
I presume "weak references" means usage of Dart_WeakPersistentHandle?  In which case we use them for several things in Sky, including the WTF String cache, as well as some logic for closing mojo handles, etc:

https://github.com/domokit/mojo/search?utf8=%E2%9C%93&q=Dart_WeakPersistentHandle

This is probably a good question for @abarth (who wrote much of this code).

**Comment by abarth** [comment]
I would imagine the main source of weak persistent handles is that we use them to associate C++ state with Dart objects so that we can clean up the C++ state when the Dart object is no longer needed.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#84

**Comment by eseidelGoogle** [comment]
That repo has since moved twice.  I believe this is "resolved" in the current game.  This was solved by removing these sources of weak references.
