### ISSUE TITLE
Latest SkyDemo.apk dies trying to use old sky framework from domokit.github.io

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#204]
Latest SkyDemo.apk dies trying to use old sky framework from domokit.github.io

I expect this is expected, but still disappointing.  This is a just-built SkyDemo.apk, including mojo:network_service (SkyShell's java-based oknet implementation), which is blowing up in the Dart bindings when fetch.dart tries to use an "old" url_response.mojom.dart to talk to the embedded "new" network_service.

Maybe this is a bug that we need to be bundling all relevant mojom's with the apk?  Or maybe this is a bug in that mojom should support this kind of versioning skew?

@abarth @jamesr @viettrungluu-cr 

E/chromium( 9630): [ERROR:dart_error.cc(20)] Unhandled exception:
E/chromium( 9630): Uncaught Error: Header doesn't correspond to any known version.
E/chromium( 9630): Stack Trace:
E/chromium( 9630): #0      UrlResponse.decode (https://domokit.github.io/packages/mojo/services/network/public/interfaces/url_loader.mojom.dart:165:13)
E/chromium( 9630): #1      UrlLoaderStartResponseParams.decode (https://domokit.github.io/packages/mojo/services/network/public/interfaces/url_loader.mojom.dart:425:37)
E/chromium( 9630): #2      UrlLoaderStartResponseParams.deserialize (https://domokit.github.io/packages/mojo/services/network/public/interfaces/url_loader.mojom.dart:398:12)
E/chromium( 9630): #3      UrlLoaderProxyImpl.handleResponse (https://domokit.github.io/packages/mojo/services/network/public/interfaces/url_loader.mojom.dart:668:46)
E/chromium( 9630): #4      Proxy.handleRead (https://domokit.github.io/packages/mojo/public/dart/src/proxy.dart:42:5)
E/chromium( 9630): #5      MojoEventStreamListener.listen.<anonymous closure> (https://domokit.github.io/packages/mojo/public/dart/src/event_stream.dart:203:9)
E/chromium( 9630): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
E/chromium( 9630): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
E/chromium( 9630): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
E/chromium( 9630): #9      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
E/chromium( 9630): #10     _StreamController._add (dart:async/stream_controller.dart:570)
E/chromium( 9630): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
E/chromium( 9630): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
E/chromium( 9630): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
E/chromium( 9630): #14     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
E/chromium( 9630): #15     _StreamController._add (dart:async/stream_controller.dart:570)
E/chromium( 9630): #16     _StreamController.add (dart:async/stream_controller.dart:516)
E/chromium( 9630): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
E/chromium( 9630): 
E/chromium( 9630): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium( 9630): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium( 9630): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium( 9630): [ERROR:dart_error.cc(29)] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium( 9630): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium( 9630): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium( 9630):

**Comment by eseidelGoogle** [comment]
Incidentally, using an Old SkyDemo.apk trying to talk to the latest version of the framework just crashes in c++ code. :)  I could pull out an old checkout and build a Debug version of the old SkyDemo.apk to debug.

Regardless, with the current state of things I'm going to be breaking some number of installs of SkyDemo.apk regardless of what I do.

**Comment by eseidelGoogle** [comment]
I believe this is the old mojom:
https://github.com/domokit/mojo/blob/dart_summit/mojo/services/network/public/interfaces/url_loader.mojom

Verses the new one:
https://github.com/domokit/mojo/blob/master/mojo/services/network/public/interfaces/url_loader.mojom
I'm not quite sure where url_response.mojom is located in the new layout.  Obviously url_response.mojom didn't exist in the old layout.

**Comment by eseidelGoogle** [comment]
Ah, here is the new url_response.mojom, which is what the Java network_service would expect to be talking:
https://github.com/domokit/mojo/blob/46b709be65425f3d3852b48e1cb3ebd85b762919/mojo/public/interfaces/network/url_response.mojom

**Comment by viettrungluu-cr** [comment]
mojom supports versioning and backwards compatibility.

But given that the network interfaces are in nowhere near the form that
we'd like them to be eventually, it might be premature to add versioning to
the mojom files in question.

(Doing so would be a commitment to supporting the current mojom files
"forever". Of course, we could still have flag days where we break
everything, which *might* be better than breaking things more regularly.)

**Comment by eseidelGoogle** [comment]
@yzshen FYI, since at least at one point he was in charge of versioning. :)

**Comment by yzshen** [comment]
In this particular case, if you want the old/new URLResponse definition to be able to communicate with each other, you will need to add a version annotation for the newly added field:
[MinVersion=1] string? redirect_referrer;
And you are all set. :)

As Trung said, it is too early to assume the network API to be stable at this point. But we could use versioning to reduce breakages, and have flag days when we make non-backward-compat changes to clean up old definitions.

**Comment by ppiet** [comment]
Assuming this is obsolete now.
