### ISSUE TITLE
Stock2 stocks missing up/down green/red arrows.

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#211]
Blocks https://github.com/domokit/mojo/issues/207

**Comment by HansMuller** [comment]
Fixed: https://codereview.chromium.org/1172513002

**Comment by eseidelGoogle** [comment]
BTW, if you put any github link in a commit, github will notice and comment on the associated item.  e.g. if you put the full link to this page in a CL this page will get an update.  You can even auto-close if you use the word "close":
https://help.github.com/articles/closing-issues-via-commit-messages/
