### ISSUE TITLE
Impossible to Style text in fn2

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#213]
Blocks https://github.com/domokit/mojo/issues/207

**Comment by eseidelGoogle** [comment]
I need to work on deploying our Demos, so I shouldn't hold this.

**Comment by eseidelGoogle** [comment]
@HansMuller mentioned he was interested in creating a TextStyle class?

**Comment by HansMuller** [comment]
Yes, I'd like to start working on that now.

**Comment by HansMuller** [comment]
WIP - https://codereview.chromium.org/1176133002/
