### ISSUE TITLE
Search widget in Stocks2 looks wrong/crashes fn

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#214]
Search widget in Stocks2 looks wrong/crashes fn

I'm not sure it's crashing fn completely anymore, but it definitely looks wrong when clicking on the search widget.  Mostly the placeholder text is wrong.  Not clear that text input works at all.

Blocks https://github.com/domokit/mojo/issues/207

**Comment by abarth** [comment]
This is not correct except for text styling.
