### ISSUE TITLE
Fn crashes with oldNode.mounted when closing Drawer

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#217]
E/chromium(12584): [ERROR:dart_error.cc(20)] Unhandled exception:
E/chromium(12584): Uncaught Error: 'http://localhost:9888/packages/sky/framework/fn2.dart': Failed assertion: line 126 pos 14: 'oldNode.mounted' is not true.
E/chromium(12584): Stack Trace:
E/chromium(12584): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(12584): #1      UINode.syncChild (http://localhost:9888/packages/sky/framework/fn2.dart:126:14)
E/chromium(12584): #2      Scaffold.syncRenderObject (http://localhost:9888/packages/sky/framework/components2/scaffold.dart:208:5)
E/chromium(12584): #3      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/framework/fn2.dart:303:5)
E/chromium(12584): #4      UINode.syncChild (http://localhost:9888/packages/sky/framework/fn2.dart:148:10)
E/chromium(12584): #5      MultiChildRenderObjectWrapper.syncRenderObject.sync (http://localhost:9888/packages/sky/framework/fn2.dart:574:27)
E/chromium(12584): #6      MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/framework/fn2.dart:590:11)
E/chromium(12584): #7      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/framework/fn2.dart:303:5)
E/chromium(12584): #8      UINode.syncChild (http://localhost:9888/packages/sky/framework/fn2.dart:148:10)
E/chromium(12584): #9      Component._sync (http://localhost:9888/packages/sky/framework/fn2.dart:919:14)
E/chromium(12584): #10     App._buildIfDirty (http://localhost:9888/packages/sky/framework/fn2.dart:1030:5)
E/chromium(12584): #11     _buildDirtyComponents (http://localhost:9888/packages/sky/framework/fn2.dart:781:12)
E/chromium(12584): #12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
E/chromium(12584): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium(12584): #14     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium(12584): 
E/chromium(12584): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium(12584): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium(12584): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium(12584): [ERROR:dart_error.cc(29)] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium(12584): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium(12584): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium(12584): 

Blocks https://github.com/domokit/mojo/issues/207

@Hixie

**Comment by eseidelGoogle** [comment]
Open drawer and then close it by flinging it with your finger closed.

**Comment by abarth** [comment]
https://github.com/domokit/mojo/commit/52d58ab98d6f10565ee1988a5706ccb07d5babdd
