### ISSUE TITLE
Material Design: Dialog

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#219]
We'll need one of these for our next Demo.

http://www.google.com/design/spec/components/dialogs.html

**Comment by eseidelGoogle** [comment]
@collinjackson has started on these:
https://github.com/domokit/mojo/blob/master/sky/tests/widgets/dialog.dart

**Comment by collinjackson** [comment]
There is now a confirm dialog that you can trigger in the Settings of the stocks app
