### ISSUE TITLE
Material Design: Cards

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#221]
Our next demo is going to need Cards:
http://www.google.com/design/spec/components/cards.html

**Comment by abarth** [comment]
We also need to be able to swipe and flip the cards.

**Comment by eseidelGoogle** [comment]
My understanding is that @collinjackson has given us basic card support?

**Comment by collinjackson** [comment]
This is implemented in https://codereview.chromium.org/1217623002/
