### ISSUE TITLE
Material Design: Snackbar

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#222]
We'll need a snackbar for our next demo:
http://www.google.com/design/spec/components/snackbars-toasts.html

The Android implementation of snackbars has more rounded corners than the original Material Design spec has.  We'll have to pick one.

**Comment by eseidelGoogle** [comment]
I'll take a look.

**Comment by collinjackson** [comment]
@mpcomplete is working on animating this

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#83
