### ISSUE TITLE
Sky Framework should use quiver.core for hashCodes

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#236]
http://www.dartdocs.org/documentation/quiver/0.21.4/index.html#quiver/quiver-core

It's silly we write our own hashCodes by hand.

We'll need to add quiver to DEPS.

@johnmccutchan

**Comment by sethladd** [comment]
Cc @cbracken fyi

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1184753002/

Blocked on getting a mirror of quiver setup, which I pinged Robert about.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#62
