### ISSUE TITLE
Deprecate and drop mojodb.

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#238]
`mojo_shell.py` now supports running Sky files through the `--sky` flag. There is a few remaining features of `mojodb` to match in the new toolchain:

 - gdb attach / Androig gdb support in `debugger`
 - android_stack_parser hooked up in `debugger`

If anyone has a way of using `mojodb` that doesn't work with `mojo_shell.py` + `debugger`, please raise a shout here.

@abarth @eseidelGoogle @emembrives

**Comment by abarth** [comment]
I tried using mojo_shell.py today, but hit a blocker because mojo_shell.py doesn't work inside a Linux virtual machine.  Specifically, it seems to be missing the --use-osmesa option from mojodb.  All this flag does is pipe an args into native_viewport_service:

        # Desktop-only work-around for mojo crashing under chromoting.
        if not is_android and args.use_osmesa:
            shell_args.append(
                '--args-for=mojo:native_viewport_service --use-osmesa')

I realize I could specify the native_viewport_service argument manually, but it's a lot of typing.

Thanks!

**Comment by abarth** [comment]
mojo_shell.py doesn't understand how to download the material design icons.  You can reproduce this issue as follows:

 * `find . -name material-design-icons`
 * `rm -rf` each instance of material-design-icons you find.
 * `./mojo/tools/mojo_shell.py --sky sky/examples/stocks2/lib/stock_app.dart`

Notice that there is no + in the red circle in the bottom right.

 * `./mojo/tools/mojodb start out/Debug sky/examples/stocks2/lib/stock_app.dart`

Notice that the + is now present.

 * `./mojo/tools/mojo_shell.py --sky sky/examples/stocks2/lib/stock_app.dart`

Notice that the + is now present when running `mojo_shell.py`.  Once the assets have been downloaded, `mojo_shell.py` is able to find them.  See [https://github.com/domokit/mojo/blob/master/mojo/tools/mojodb#L68] for how `mojodb` solves this problem.

Thanks!

**Comment by tonygentilcore** [comment]
Downloading icons is closely related to the problem I was having in an internal repo here: https://chromereviews.googleplex.com/217647013/

It'd be really nice if we could just remove that custom code for icon downloading without causing the issue in the above revert.

/cc @johnmccutchan
