### ISSUE TITLE
Should be able to run Sky app offline

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#240]
This issue is about implementing basic offline support.  Possibly something like PAK files in Quake/Doom.  Might want to combine with Dart snapshot.

**Comment by sethladd** [comment]
cc @keertip, @devoncarew, @lukechurch

**Comment by abarth** [comment]
https://codereview.chromium.org/1211253004 makes MineDigger work offline.  Still lots of work to do, but once that lands, we'll have at least one thing that work offline.

**Comment by abarth** [comment]
I can build apps that work offline locally by setting enable_skyx to true in gn args.  However, to turn that flag on by default, we need a git mirror of one more dart package.  That's tracked by https://code.google.com/p/chromium/issues/detail?id=507306

**Comment by abarth** [comment]
This now fully works.
