### ISSUE TITLE
Need support for charts in Sky

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#242]
Possibly something like https://github.com/google/charted

Presumably we don't want this in the main framework.  Charting support might be a good place to start with another Dart pub package that depends on the |sky| package.

**Comment by eseidelGoogle** [comment]
I briefly looked at this.  charted currently imports dart:html in many places and will take some surgery to remove that dependency. @psunkari

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#59
