### ISSUE TITLE
Sky framework needs URL routing

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#243]
Different screens inside a Sky application should be named using URLs.  When an app starts up with a given URL, the routing system should build the correct screen.  When some component deep in the app wants to change to a different screen, it should be able to do that by asking for the screen by its name.

**Comment by collinjackson** [comment]
Screens can now be named with URLs. We don't have a mechanism for starting up a Sky application with a particular screen yet.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#58
