### ISSUE TITLE
Flex needs to understand baselines

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#244]
In order to properly align text (e.g., in a horizontal RenderFlex), we need to understand the baseline.  RenderBox needs to understand baselines [hixie] and horizontal RenderFlex needs to use it for layout [jackson].

The test case is that StockRow should be baseline aligned.

@Hixie

**Comment by collinjackson** [comment]
Hixie finished the first part of this

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#57
