### ISSUE TITLE
Sky misses methods for converting points to local space

### ISSUE THREAD

**Issue by vlidholt** [domokit/mojo#249]
In the handleEvent method of RenderBox the BoxHitTestEntry provides a local point for the pointerdown event. But for dragged pointers there is no way of finding the local coordinates within the box. The dragged delta is in global space and therefore doesn't solve the problem.

A method that converts to and from the global space would be useful. E.g.
`Point convertPointToLocalSpace(Point point)` that is a method of RenderBox (or one of its super classes). Another solution could be to pass down the local point in the event method.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#56
