### ISSUE TITLE
Should event handling use constants instead of strings?

### ISSUE THREAD

**Issue by vlidholt** [domokit/mojo#250]
Currently, the `type` property of the Event class is a string. Should this instead be an enumeration or at least provide constants for the string values?

Main benefit for a change would be that more typos would be caught at compile time, but moving to an enumeration could potentially also affect performance.

**Comment by Hixie** [comment]
It should use neither. We should just have a different class per event.

See https://github.com/domokit/mojo/blob/master/sky/specs/pointer.md
