### ISSUE TITLE
Scaffold should know whether to leave room for the status bar

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#257]
Currently `Scaffold` hard codes the `ToolBar`'s height as `double toolbarHeight = kToolBarHeight + kNotificationAreaHeight;`. Mojo shell and older Android versions don't allow painting below the status bar. So @abarth suggested that sky should be able to detect when `kNotificationAreaHeight` should be 0.

/cc @Hixie

**Comment by abarth** [comment]
One approach would be to have View expose a top/left/bottom/right padding value that the scaffold can use.  When we can't draw behind the status bar, we'd set the top padding to zero.

**Comment by abarth** [comment]
https://codereview.chromium.org/1220353002
