### ISSUE TITLE
SkyShell should exist on Mac

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#258]
This would make it possible for us to be able to run test on a Mac.

This should be possible now after the recent refactorings of SkyShell for ios.

@chinmaygarde @collinjackson @johnmccutchan

**Comment by tonygentilcore** [comment]
Is there a strong reason this shouldn't be done in the context of mojo shell instead of sky shell?

/cc @qsr

**Comment by eseidelGoogle** [comment]
If we had a mojo_shell on mac, we could use it.  But sky_shell is much less code to port and would serve our immediate needs.

**Comment by tonygentilcore** [comment]
I thought @jamesr was carrying a hacky patch in his client at one point in time that allowed mojo shell to be built on a mac and it didn't seem like tremendous amounts of work. Maybe I misunderstood or misremembered.

Just for my information, would you be willing to expound on the additional code that has to be ported for mojo shell to work on mac? I'd really like to be able to have the same nice developer experience for Mojo that Sky enjoys :)

**Comment by eseidelGoogle** [comment]
If he does I'd love to see it.  Bringing up sky_shell on mac now.

**Comment by viettrungluu-cr** [comment]
Sure, it's currently trivial to get mojo_shell building/running on a Mac.
But you'd be very disappointed when you realized that there's no native
viewport service, which would be a huge amount of work to get running. (And
as we make mojo_shell more interesting, e.g., by adding sandboxing, it'd
become more and more of a burden to support Mac.)

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#49
