### ISSUE TITLE
left + right mouse button causes dart exception

### ISSUE THREAD

**Issue by cpu-chromium** [domokit/mojo#260]
When you let go of the buttons, you get:

[0622/171434:ERROR:dart_error.cc(20)] Unhandled exception:
The null object does not have a getter 'lastPosition'.

NoSuchMethodError: method not found: 'lastPosition'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SkyBinding._handlePointerEvent (http://127.0.0.1:9998/packages/sky/rendering/sky_binding.dart:116:35)
#3      SkyBinding._handleEvent (http://127.0.0.1:9998/packages/sky/rendering/sky_binding.dart:75:7)
[0622/171434:ERROR:dart_error.cc(29)] #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SkyBinding._handlePointerEvent (http://127.0.0.1:9998/packages/sky/rendering/sky_binding.dart:116:35)
#3      SkyBinding._handleEvent (http://127.0.0.1:9998/packages/sky/rendering/sky_binding.dart:75:7)

This is because in void _handlePointerEvent(sky.PointerEvent event)  this lookup failed:

      case 'pointerup':
      case 'pointercancel':
        state = _stateForPointer[event.pointer];

state here is null. It should have been inserted in during pointerdown but somehow it was not. Possibly a unexpected value of event.pointer is there since this is what we use as key.

**Comment by abarth** [comment]
https://codereview.chromium.org/1215743003
