### ISSUE TITLE
Missing bindings for SkPaint and SkCanvas

### ISSUE THREAD

**Issue by vlidholt** [domokit/mojo#261]
Many drawing methods are missing in Dart for SkPaint and SkCanvas.

**Comment by eseidelGoogle** [comment]
They're pretty simple to add:
https://github.com/domokit/mojo/blob/master/sky/engine/core/painting/Canvas.idl

**Comment by abarth** [comment]
Would you be willing to file individual bugs for the specific things that need to be added?

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#47
