### ISSUE TITLE
sky.Image is backed by SkBitmap (deprecated) instead of SkImage

### ISSUE THREAD

**Issue by vlidholt** [domokit/mojo#265]
In the bindings layer the sky.Image is backed by SkBitmap instead of SkImage. SkImage is a newer API and offer optimizations that aren't available through SkBitmap.

**Comment by collinjackson** [comment]
The decoding happens in https://github.com/domokit/mojo/blob/master/sky/engine/core/loader/CanvasImageDecoder.cpp

Right now we're calling decoder->frameBufferAtIndex(0)->getSkBitmap()

If there is an easy way to get an SkImage instead that would be great

**Comment by reed-at-google** [comment]
If I make modifications to the imagedecoders, should that be directly here, or if they are updated in chromium/blink, will those changes be "merged" back into mojo?

**Comment by collinjackson** [comment]
That is a good question for @abarth or @eseidel

**Comment by eseidelGoogle** [comment]
We are completely forked from Blink. :)  We don't merge anything from Blink.  The mojo project occasionally merges a couple directories from Chromium:
https://github.com/domokit/mojo/wiki/Directory-guide

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#43
