### ISSUE TITLE
Some links in the readme for the sky package on pub.dartlang do not work

### ISSUE THREAD

**Issue by keertip** [domokit/mojo#271]
The readme for the published sky package has links to `framework`, `widgets tutorial`, `examples directory` for more information on sky. These links do not work.

**Comment by abarth** [comment]
Maybe the pub.dartlang docs for Sky should just point to https://github.com/domokit/sky_sdk/blob/master/README.md ?

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#44
