### ISSUE TITLE
hello_widgets example shows black screen on phone

### ISSUE THREAD

**Issue by keertip** [domokit/mojo#276]
Running the `hello_widgets.dart` sample sky app on the phone just shows a black screen. Cannot see any text, so not sure if it is working as indented.

**Comment by abarth** [comment]
We should probably style the text white and center it so its visible.

**Comment by Hixie** [comment]
Would a better way to make the default color and the default background compatible?

Making HelloWorld bigger is sad panda.

**Comment by iansf** [comment]
Right now, by default, apps draw underneath the Android title bar as well.  I think we might have another ticket for that, though.  Should I just change the default background color to white for this ticket instead and ignore the padding issue for now?

**Comment by abarth** [comment]
It might be better to change the default text color to white than to change the default background to white.  A white default background will cause a white flash in some cases like it does in web browsers.
