### ISSUE TITLE
sky libraries don't have library directives

### ISSUE THREAD

**Issue by devoncarew** [domokit/mojo#283]
When I import two libraries from sky:

```dart
import 'package:sky/widgets/basic.dart';
import 'package:sky/painting/text_style.dart';
```

I see this analysis warning:

![screen shot 2015-06-30 at 8 42 29 am](https://cloud.githubusercontent.com/assets/1269969/8435162/a0d2c4f4-1f04-11e5-8e67-92c8fbc95083.png)

The sky libraries should probably have `library` directives, if only to avoid these analysis warnings.

**Comment by eseidel** [comment]
That warning was the product of an argument, and likely just a bug: http://dartbug.com/22836

**Comment by devoncarew** [comment]
Ah, thanks, I missed the discussion there. It doesn't seem like it had a resolution; sky doesn't use library directives and the analyzer kept the warning. We can filter them in each tool but that workaround doesn't scale well.

**Comment by sethladd** [comment]
We plan to remove that warning from the spec

**Comment by devoncarew** [comment]
Cool. I'll close this issue then in anticipation of that -
