### ISSUE TITLE
Material Design: Toasts

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#288]
We'll need a Toast for our next demo:
http://www.google.com/design/spec/components/snackbars-toasts.html

**Comment by iansf** [comment]
Toasts are deprecated, apparently.

**Comment by collinjackson** [comment]
Android provides a capsule-shaped toast, but it's primarily used for system messaging. Developers who are building cross-platform apps should use the snackbar. If we get a lot of demand for toasts we could implement them, but it's not a priority right now.
