### ISSUE TITLE
Running "mojo/tools/mojo_demo.sh --browser" throws error

### ISSUE THREAD

**Issue by vivekgalatage** [domokit/mojo#29]
While running
``` mojo/tools/mojo_demo.sh --browser```
I am getting this error:
```
User entered this URL: http://google.com/
[ERROR:dynamic_application_loader.cc(133)] Library not started because library path '/home/vivekg/workspace/mojo/src/out/Debug/html_viewer.mojo' does not exist.
```

I also ran ```ninja -C out/Debug -t targets``` to see if there is a target named html_viewer, but couldn't find one.

Am I missing something here?

**Comment by ppiet** [comment]
Closing the issue as mojo_demo is no longer with us.
