### ISSUE TITLE
TextStyle textAlign property fails

### ISSUE THREAD

**Issue by HansMuller** [domokit/mojo#291]
Adding textAlign: TextAlign.center or TextAlign.right to the TextStyle created in interactive_flex.dart doesn't seem to have any effect. The TextStyle implementation appears to be doing the right thing but the text-align style change doesn't seem to be connected.

The TextStyle textAlign property is needed for correctly rendering tabs whose text labels wrap to two lines.

**Comment by ppiet** [comment]
Should this be moved to the sky_engine issue tracker?

**Comment by eseidel** [comment]
You should feel welcome to move any issues you think might be better in sky_engine.  @Hixie tried to move most, but probably missed a couple.  I believe TextAlign works now, but I'm not sure.

https://github-issue-mover.appspot.com/ is a helpful tool if you need.

**Comment by ppiet** [comment]
This issue was moved to domokit/sky_engine#885

**Comment by ppiet** [comment]
Cool stuff, thanks!
