### ISSUE TITLE
Review dart content handler packaging

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#296]
Right now, dart content handler expects a zip of dart file that will be compiled and run.

Should we instead try to send a dart snapshot to speed up startup?

/cc @johnmccutchan

**Comment by johnmccutchan** [comment]
Probably what you mean is include a script snapshot in the zip file (because there may be non-Dart sources in the zip file needed to run).

But, I think we should EOL the .dartzip approach and move to loading over http like Sky does.

**Comment by qsr** [comment]
What kind of non-Dart sources are you thinking about? I do not think we do this at all in the moment. I would be in favor of doing the simplest thing first and move the packaging to a more complex format when we need it.

About sky, unless I'm completely misunderstanding what is happening, they are moving to something like what I'm describing with the skyx format. I want to go there for the same reason -> improve startup perf and allow offline mode.

**Comment by abarth** [comment]
A skyx file is a zip file with a Dart script snapshot and whatever other resources the developer wants to bundle with their app.  Drat script snapshots are specific to the Dart embedding environment and the exact version of the DartVM (although they are architecture independent).  That means they're only suitable in cases where there's a tight coupling between the snapshot version and the DartVM version.

**Comment by zanderso** [comment]
I believe this issue is stale. The dart content handler can load both .dart scripts over http, and .mojo files (really zip files) containing a script snapshot.
