### ISSUE TITLE
Sky should be able to draw images from raw data

### ISSUE THREAD

**Issue by alhaad** [domokit/mojo#297]
Currently, it is possible to draw in image in sky using either a live URI or using an undrained mojo data pipe. It should be possible to draw an image also using a data URI.

/cc @abarth @tonygentilcore

**Comment by tonygentilcore** [comment]
Hey Alhaad, I'd recommend putting the use case here instead of the proposed solution. In other words, please mention exactly what structure the data is in that you'd like to put into an `Image`.

**Comment by alhaad** [comment]
As a concrete example, it would be cool if we could have something like:
new Image(src: 'data:image/gif;base64,R0lGOD');

Need for such an interface:
Modular data flow for something like displaying an image from the local gallery is camera_roll --(pipe)-->modular_app1--(base64 encoded)-->firebase--(base64 decode)-->modular_app2--(write to a pipe)-->sky which is very convoluted. This is because we need to drain and serialize the data from pipe to store on firebase and then de-serialize to a pipe as sky can accept only an undrained pipe.

If we are able to provide a data URI to sky, things can be much simpler.
camera_roll--(data uri)-->modular_app1--(data uri)-->firebase--(data uri)-->modular_app2--(data uri)-->sky

**Comment by abarth** [comment]
Let me see if I've understood.  You're receiving a base64 encoded image from firebase and you want to display it to the user.  That makes sense.

Ultimately, we'll need to write the data from the base64 encoded image into a data pipe because the image decoder needs to read the data on a background thread, but we can provide some framework code that makes that easy.

**Comment by alhaad** [comment]
I see. Since sky *needs* to have it in a data pipe, I am wondering if it is better to push writing to data pipe on the sky side of things or not.
Btw, what is the reason for sky not supporting generic data URLs (not specific to this case)?

**Comment by abarth** [comment]
Sky doesn't have any opinion about the types of URLs.  That's up to mojo:network_service.  Another way to address this issue would be to add support for data URLs to mojo:network_service.

**Comment by abarth** [comment]
What would you prefer:
* Teach mojo:network_service to understand data URL
* Add some framework code to Sky to help you turn data URLs into images
?

**Comment by qsr** [comment]
Is there any reason we wouldn't want the network service to support data URLs?

**Comment by abarth** [comment]
IMHO, having the network service handle data URLs is the better approach because its generally useful.

**Comment by abarth** [comment]
https://codereview.chromium.org/1215023014/
