### ISSUE TITLE
Stocks App tab bar is missing highlight underline

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#301]
It was there at some point but seems missing from tip of tree.  Presumably @HansMuller is already on the problem. :)

**Comment by HansMuller** [comment]
OK, I'm on it now.  The TabBar indicator highlight is supposed to be 2 pixels high (https://www.google.com/design/spec/components/tabs.html#tabs-specs) which seems thinner than current Android and sometimes hard to see.  Anyway, I'll take a look.

**Comment by collinjackson** [comment]
Fixed in 91df367a11c3c255b25181b4ea44f3fe91f4fd23
