### ISSUE TITLE
Stocks Menu items appear during menu animation (draw outside the menu)

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#303]
Open Stocks app and click to show/hide the menu.  We don't appear to clip the menu items to the actual menu.  @Hixie says we shouldn't need to necessary clip so long as we're smart enough to hide the menu items as the animation progresses.

**Comment by ppiet** [comment]
Should this be moved to sky_engine or is it obsolete now?

**Comment by ppiet** [comment]
Assuming this is obsolete.
