### ISSUE TITLE
mojo::WeakInterfacePtrSet should be refactored to remove the need for WeakInterfacePtr

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#311]
With connection error callbacks, it's easy to have WeakInterfacePtrSet just own InterfacePtrs and remove them directly on connection error.

Also, WeakInterfacePtrSet needs tests.

**Comment by viettrungluu-cr** [comment]
The same applies to WeakBindingSet (removing the need for WeakBinding) as well. (I'm making a change to remove its use of ErrorHandler, but it should also be refactored.)

**Comment by MitchRudominer** [comment]
sg, I  will refactor both.

**Comment by qsr** [comment]
All is true, but I think we have also usages of WekInterfacePtr. Am I correct that you are mainly doing this to remove our dependency on //base? We could use std::weak_ptr instead.

**Comment by viettrungluu-cr** [comment]
There are no uses of WeakInterfacePtr (outside of WeakInterfacePtrSet) in the mojo repo.

Really, the reason to remove it is that it smells bad:

* It's defined in weak_interface_ptr_set.h, not weak_interface_ptr.h. Moreover, WeakInterfacePtrSet doesn't expose it.
* The main reason one might want to use it is that it was inconvenient to implement ErrorHandler (and create/instantiate a secondary object implementing it, if you had multiple InterfacePtrs whose lives you wanted to track -- this is exactly how WeakInterfacePtrSet uses it). With connection error callbacks, this is simply a matter of doing `foo_.set_connection_error_handler([this]() { foo_.reset(); });`.
* If people really want a weak interface pointer, we should have that, rather than something that's logically a weak pointer to a pointer, which is one level of indirection too many.
* Failing that (i.e., when people are lazy), vending weak pointers to InterfacePtrs is trivial, as long as the InterfacePtr has a primary owner: you have a weak pointer factory and invalidate weak pointers in the connection error callback.
* (Admittedly, receiving a weak pointer to an InterfacePtr isn't as powerful as receiving a weak pointer to a WeakInterfacePtr. But this is generally a good thing, since you probably should retain control over who can get weak pointers.)

**Comment by qsr** [comment]
Trung, we have user in a private repository that uses this.

Out of this, I agree with you.

**Comment by viettrungluu-cr** [comment]
They have a proper fork of it. (Incidentally, they also made
WeakInterfacePtrSet::AddInterface() return a weak pointer to a
WeakInterfacePtr. I *think* I once asked James if something like that was a
good idea and I think he indicated that it was outside the scope of what
WeakInterfacePtrSet was meant for. In retrospect, I think so too.)

**Comment by MitchRudominer** [comment]
Trung, in addition to the above CLs I was also considering changing the names of WeakBindingSet and WeakInterfacePtrSet. The word "weak" no longer seems appropriate to me. Not sure what the right name is yet--something that implies that the objects are owned by the underlying message pipe and are destroyed when a connection error occurs. WDYT?

**Comment by viettrungluu-cr** [comment]
The names haven't been appropriate for a while, especially in the case of
WeakBindingSet (IIRC, what's now called Binding used to be called a weak
binding, and what's now StrongBinding was just a binding, or something like
that). (To be clearer, WeakBindingSet was called that because it doesn't
own the implementation object -- i.e., it's a set of weak bindings. I think
WeakInterfacePtrSet was named in imitation.)

There's no need to say anything about objects being owned by the message
pipe, because these objects aren't exposed publicly.

I think BindingSet and InterfacePtrSet would be fine.
