### ISSUE TITLE
Pointer gesture is dropped if target widget hierchy changes

### ISSUE THREAD

**Issue by HansMuller** [domokit/mojo#312]
A Listener that specifies onPointerDown, onPointerMove, onPointerUp should see all three events if
the PointerDown event targets its widget.

Currently if the target widget's hierarchy changes in response to PointerDown, the rest of the Pointer move/up gesture is dropped.

**Comment by Hixie** [comment]
This will become moot once the Gesture objects capture the pointers.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#29
