### ISSUE TITLE
Support Material Design Card Content Blocks

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#319]
Cards have specific layout patterns for their content:
http://www.google.com/design/spec/components/cards.html#cards-content-blocks

We should provide some helpers to get those layouts as part of the Sky Framework.

FYI @HansMuller

**Comment by eseidelGoogle** [comment]
I may actually work on this some as part of the address_book demo I'm building as part of implementing proper text fields, we'll see:
http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#28
