### ISSUE TITLE
sky.ColorFilter needs operator==

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#324]
When someone sets a sky.ColorFilter on either a ColorFilter widget or on an Image widget, we call operator== to check whether the filter has changed.  If it has changed, we mark ourselves as needing paint.  However, sky.ColorFilter doesn't implement operator==, which means we're just getting object identity, which means we're invalidating paint more often than necessary.

/cc @mpcomplete

**Comment by eseidel** [comment]
Would be nice to be able to catch these errors in some way.  In obj-c one could override -[NSObject equals:] to warn using a "category".  I know dart doesn't have those, but maybe there is another solution we should use.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#25
