### ISSUE TITLE
Dart and Java don't agree how non-argument responses in mojom should be encoded

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#329]
If you implement a Mojo service in Java that has a non-argument response and you try to call that service from Dart, you'll get the following exception:

```
Uncaught Error: Expected a message with a valid request Id.
Stack Trace:
#0      EchoProxyImpl.handleResponse (package:mojom/mojo/examples/echo.mojom.dart:287:11)
#1      Proxy.handleRead (package:mojo/src/proxy.dart:50:5)
#2      MojoEventStreamListener.listen.<anonymous closure> (package:mojo/src/event_stream.dart:203:9)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
#7      _StreamController._add (dart:async/stream_controller.dart:567)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#11     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
#12     _StreamController._add (dart:async/stream_controller.dart:567)
#13     _StreamController.add (dart:async/stream_controller.dart:513)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

To reproduce this issue:

- Apply the following patch: [https://codereview.chromium.org/1233093009](https://codereview.chromium.org/1233093009)
- Build for Android Debug)
- `mojo/devtools/common/mojo_shell --android mojo:dart_echo_client`

Notice that you get an exception.  However, if you change `examples/dart/dart_echo_client/main.dart` to talk to `mojo:echo_server` rather than `mojo:java_echo_server`, everything works fine.  (Note: you'll need to rebuild after changing main.dart.)

/cc @j9brown

**Comment by abarth** [comment]
@eseidelGoogle was there another bug on file about this issue?  I couldn't find it.

**Comment by MitchRudominer** [comment]
I'll investigate this.

**Comment by MitchRudominer** [comment]
I changed the language in the description of the bug from "non-argument responses" to "zero-argument responses" because I understand that better. Feel free to revert back to original language if you disagree.

**Comment by MitchRudominer** [comment]
I have a fix in https://codereview.chromium.org/1242193002/.
The problem turns out to be that in the case that there are zero arguments in the response. the Java Jinja templates are generated code that returns a response without the MESSAGE_IS_RESPONSE flag. The error message given by the Dart parser "Expected a message with a valid request Id" is spurious.

**Comment by j9brown** [comment]
Thanks for fixing this.  That said, I was looking forward to digging into
the code myself.

Jeff.

**Comment by j9brown** [comment]
Maybe next time.  :)
