### ISSUE TITLE
Dart content handler should support tracing(.mojom)

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#333]
Dart VM already collects traces in trace event format. We need to add plumbing to dart content handler, so that the traces being collected are available through the TraceController interface (defined in https://github.com/domokit/mojo/blob/master/mojo/services/tracing/public/interfaces/tracing.mojom).

@johnmccutchan @zanderso @qsr

**Comment by ppiet** [comment]
This will allow dart apps to participate in Mojo "tracing ecosystem". Ie. they would be pulled down by Mojo trace collector and combined with traces collected from the shell and from C++ apps, yielding one unified trace.

**Comment by zanderso** [comment]
This was hooked up by @johnmccutchan some time ago.
