### ISSUE TITLE
"mojo:" URLs only work once per shell lifetime

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#334]
Repo:
  1. Launch a `mojo:` URL on an android device which should open the mojo shell and load the URL.
  1. Move back to the home screen and launch it again.
  1. Notice the screen stays white and it doesn't appear to run the intent.

Going to "settings > force stop mojo shell" resets the state so that `mojo:` URLs will work again.

/cc @qsr @ppiet @emembrives

**Comment by ppiet** [comment]
Might be related to the issue described in MojoShellActivity:

```
        // TODO(ppi): Gotcha - the call below will work only once per process lifetime, but the OS
        // has no obligation to kill the application process between destroying and restarting the
        // activity. If the application process is kept alive, initialization parameters sent with
        // the intent will be stale.
        ShellMain.ensureInitialized(getApplicationContext(), getParametersFromIntent(getIntent()));
```

**Comment by emembrives** [comment]
It should be fixed by 13f64f4986ff0d9773fc86d76de5dc3f5bf36c2c.

**Comment by emembrives** [comment]
@tonygentilcore is it still a problem?

**Comment by tonygentilcore** [comment]
I'm attempting to verify the fix now. Wasn't implying w/ the assignment that I thought it was broken.

**Comment by emembrives** [comment]
Marking as obsolete. Please reopen if it is still an issue.
