### ISSUE TITLE
Properly support CHROMIUM_image GL extensions in mojo_shell?

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#339]
We have headers/thunk tables for the CHROMIUM_image GL extensions, but mojo_shell doesn't set the thunk table when loading apps. I assume we should be? There's some code in cc that appears to use these extensions.

(This is easy enough to take care of, but there's a "certain" lack of testing....)

/cc @jamesr

**Comment by jamesr** [comment]
CHROMIUM_image requires some additional work on our command buffer supporting code, i.e.:

https://github.com/domokit/mojo/blob/master/mojo/gles2/command_buffer_client_impl.cc#L246

We should probably support these or support a more standard image extension at some point.

**Comment by viettrungluu-cr** [comment]
I guess this issue is basically obsolete, since @jamesr is deleting the headers/thunk tables.

**Comment by jamesr** [comment]
It still might be useful to implement these at some point, but there's no pressing need AFAIK
