### ISSUE TITLE
GaneshContext::Scope relies on gles2::GetContext(), which doesn't have a binary-stable equivalent

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#342]
I.e., there's no `MojoGLES2GetCurrent()` in //mojo/public/c/gles2/gles2.h.

Possible fixes:
* Add such a function (and make `GaneshContext::Scope` use that).
* Make `GaneshContext::Scope` not restore the GL scope (which may mean just deleting the class entirely.
* Make `GaneshContext::Scope` only play well with other `GaneshContext::Scope`s. (I.e., each thread would have a notion of a current `GaneshContext`, and `Scope` would set/restore that, but not the general GL context.)

/cc @jamesr

**Comment by jamesr** [comment]
Is the context restoring part of this code used anywhere?  I think it'd be better to explicitly declare the desired 'previous' scope (as a MojoGLES2Context object) if it's needed. @abarth 

Another possibility is to add a MojoGLES2GetCurrent() entry point (seems awkward, but EGL has one)

**Comment by abarth** [comment]
I don't think we actually use the context restoring.  I just wrote it that way originally because GetCurrent existed.

**Comment by viettrungluu-cr** [comment]
@jamesr What's the appropriate "replacement" for `skia_bindings::CreateCommandBufferSkiaGLBinding()`?

**Comment by jamesr** [comment]
https://github.com/domokit/mojo/blob/master/gpu/skia_bindings/gl_bindings_skia_cmd_buffer.cc binds skia's GrGLInterface interface to the C gl entry points, which in our world are provided by the mojo thunks.  So I think that function should do exactly what we want so long as the macros are set up properly for mangling.  The 'command buffer' part of the function name is really misleading - it doesn't have any dependency on what provides the definition of the C entry points.

**Comment by viettrungluu-cr** [comment]
Yeah, I know that, but I was having some problems with some GL extensions.
Not sure if that was due to us not supporting some of the extensions that
that function refers to, or whether I'm missing some dependencies (so that
causes linking issues)....

**Comment by jamesr** [comment]
Can you pastebin some of the errors?

**Comment by jamesr** [comment]
//mojo/public/c/gles2/BUILD.gn defines the gles2_config which #defines GLES2_USE_MOJO.  I believe if you don't have that when including the headers you'll get really weird link errors, so that might be the first thing to check for.

**Comment by viettrungluu-cr** [comment]
//mojo/public/c/gles2 seems to be missing things like
`glBindVertexArrayOES` for one. The error looks like:

```
error: undefined reference to 'MojoGLES2glBindVertexArrayOES'
```

(I'm not properly pasting errors, since for experimental purposes I locally
made a copy of this function in ganesh_context.cc itself.)

The full list of things I have to comment out to get it to build are:
```
//  functions->fBindVertexArray = glBindVertexArrayOES;
//  functions->fDeleteVertexArrays = glDeleteVertexArraysOES;
//  functions->fDiscardFramebuffer = glDiscardFramebufferEXT;
//  functions->fGenVertexArrays = glGenVertexArraysOES;
//  functions->fInsertEventMarker = glInsertEventMarkerEXT;
//  functions->fMapBufferSubData = glMapBufferSubDataCHROMIUM;
//  functions->fPopGroupMarker = glPopGroupMarkerEXT;
//  functions->fPushGroupMarker = glPushGroupMarkerEXT;
//  functions->fTexStorage2D = glTexStorage2DEXT;
//  functions->fUnmapBufferSubData = glUnmapBufferSubDataCHROMIUM;
//  functions->fFramebufferTexture2DMultisample =
//    glFramebufferTexture2DMultisampleEXT;
//  functions->fRenderbufferStorageMultisample =
//    glRenderbufferStorageMultisampleCHROMIUM;
//  functions->fRenderbufferStorageMultisampleES2EXT =
//    glRenderbufferStorageMultisampleEXT;
//  functions->fBindUniformLocation = glBindUniformLocationCHROMIUM;
//  functions->fBlitFramebuffer = glBlitFramebufferCHROMIUM;
//  functions->fMatrixLoadf = glMatrixLoadfCHROMIUM;
//  functions->fMatrixLoadIdentity = glMatrixLoadIdentityCHROMIUM;
```

**Comment by jamesr** [comment]
We have at least some of those defined here: https://github.com/domokit/mojo/blob/master/gpu/GLES2/gl2chromium_autogen.h which is #included from gl2chromium.h.  What happens if you #include that directly?  I see an include of gl2extchromium.h but that's not quite the same (khronos helpfully doesn't define where any of the header files for extension entry points are supposed to be)

**Comment by viettrungluu-cr** [comment]
But isn't the deeper problem that we don't have thunks for those?

**Comment by jamesr** [comment]
Ah yeah, we'll need to generate thunk tables for these if we want to expose them.  It's a bit strange that skia_bindings assumes they will always have entry points defined, but we could define them I suppose.  I believe you'll need to tag the entry points in https://github.com/domokit/mojo/blob/master/gpu/command_buffer/build_gles2_cmd_buffer.py with a string value for 'extension' and then pick a thunk table name to assign these to.

**Comment by jamesr** [comment]
Assuming skia properly checks if the extension string value before calling these entry points and we generate the correct string value when calling glGetString(GL_EXTENSIONS) you could also try just leaving them null in the function pointer table.

**Comment by viettrungluu-cr** [comment]
Sorry, don't have the time to actually work on this at the moment (but will
get back to it eventually). If you want to look at it (ha), my experimental
change is https://codereview.chromium.org/1260693006 .

IIRC, running ganesh_app crashes because creating the GrContext fails, or
something like that.

**Comment by viettrungluu-cr** [comment]
This issue has been resolved/is obsolete.
