### ISSUE TITLE
mojom/generate.dart modifies the central pub_package_cache

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#346]
pub_package_cache is a read-only cache of networked packages yet mojom/generate.dart modifies this. :(  This means you have state bleed between builds and even repositories.  We're going to want a different solution to this problem.

@abarth @zanderso @johnmccutchan

**Comment by eseidelGoogle** [comment]
This means you can blow away your source directory and your build directory and still end up with strange behavior due to this behavior of modifying a global per-machine cache outside of both of those.

**Comment by johnmccutchan** [comment]
The mojom package should no longer be used for copying.
