### ISSUE TITLE
both mojo and mojo_services contain url_requests.mojom

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#347]
I'm not sure if this is intentional, but currently due to #345, #344 and #343 this produces a (seemingly random) runtime failure in apps which happen to use both of these modules.

Certainly if #345 was fixed this risk would be mitigated.  If this is intentional, please just close this bug.

@jamesr @johnmccutchan

**Comment by jamesr** [comment]
What do you mean by "mojo" and "mojo_services"? The pub packages with those names?

**Comment by eseidelGoogle** [comment]
Correct.  I Think the dart_pkg gni build rule just copies all known mojoms into each pub package?
https://github.com/domokit/mojo/blob/master/mojo/public/dart/BUILD.gn#L45
https://github.com/domokit/mojo/blob/master/mojo/public/dart/rules.gni#L245

If you apply https://codereview.chromium.org/1255053003 and run generate.dart you can easily see that we put the same *.mojom file in multiple packages:
git cl patch 1255053003
./mojo/tools/mojob.py gn
./mojo/tools/mojob.py build
cd out/Debug/gen/dart-pkg
../../../../third_party/dart-sdk/dart-sdk/bin/dart --package-root=packages packages/mojom/generate.dart

@zanderso

**Comment by jamesr** [comment]
url_request.mojom is defined only here: https://github.com/domokit/mojo_sdk/blob/master/interfaces/network/url_request.mojom and referenced by things in services.  It looks like all types defined in the mojo SDK also appear in the mojo_services dart pub package, i.e.:

$ find . -name application.mojom.dart
./mojo-0.0.18/lib/mojom/mojo/application.mojom.dart
./mojo_services-0.0.17/lib/mojom/mojo/application.mojom.dart

**Comment by johnmccutchan** [comment]
This should be fixed now.
