### ISSUE TITLE
devtools/common/mojo_run does not easily let me run ganesh_app

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#351]
With the old mojodb I used to be able to type something like `mojodb mojo:ganesh_app` and it would just work.

With the new mojo_run I have to type:

> `mojo_run   --args-for="mojo:window_manager mojo:ganesh_app" mojo:window_manager`

It would be nice to have a flag like --start_wm or something to do this for me.

@ppiet  WDYT?

**Comment by viettrungluu-cr** [comment]
You can just do mojo_run "mojo:window_manager mojo:ganesh_app".

**Comment by MitchRudominer** [comment]
Ah you are right, thanks.

**Comment by ppiet** [comment]
FYI this is documented in https://github.com/domokit/devtools/blob/master/README.md#runner .
