### ISSUE TITLE
README incorrectly mentions mojob.py dartcheck

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#352]
https://github.com/domokit/mojo/blob/master/README.md#dart-code

It mentions

>  `mojo/tools/mojob.py dartcheck`

but this does not work. I don't want to fix it myself because I am not sure if the documentation is wrong or the script is wrong. \cc @ppiet

**Comment by viettrungluu-cr** [comment]
The dartcheck subcommand was removed
in 62e312b60088f007e0296ad0a9607e78fd448392.

**Comment by MitchRudominer** [comment]
OK, thanks. I fixed the README.
