### ISSUE TITLE
Pointer events don't give screenX and screenY

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#36]
We have this in ui::Event and in web input events.  Seems like we should have it for pointer events too.

**Comment by Hixie** [comment]
How would you use this?

**Comment by abarth** [comment]
To coordinate with other apps on the screen that are in some other coordinate system from you.

**Comment by Hixie** [comment]
Ah, yeah, that makes sense.

**Comment by Hixie** [comment]
This issue was moved to domokit/sky_engine#156
