### ISSUE TITLE
Dart mojom generator should use classes for enums instead of `int`

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#360]
I'm told we can't use dart enums for mojom enums because mojom enums can be assigned a specific integer value and dart enums do not support that.

However it would still be better if we generated classes for these enums which were of a separate type than "int" and could at least appear semantically like enums.

Currently:

`keyboard.mojom`
```
enum KeyboardType {
  NUMBER,
  TEXT,
}
```
generates:
```
static int KeyboardType_NUMBER = 0;
static int KeyboardType_TEXT = 1;
```
However this would be better:
```
class KeyboardType {
   const KeyboardType(this.intValue);
   final int intValue;

  const KeyboardType NUMBER(0);
  const KeyboardType TEXT(1);
}
```
As then code using these would look more like Dart enums:

```
KeyboardType.NUMBER
```

@zanderso @abarth

**Comment by eseidelGoogle** [comment]
This is the file in question:
https://github.com/domokit/mojo/blob/master/mojo/public/tools/bindings/generators/dart_templates/enum_definition.tmpl

**Comment by eseidelGoogle** [comment]
This would also allow us to easily re-export enums instead of having to export each one of their values individually. :(

import 'blah/blah/blah.mojom.dart';
export EnumType;

**Comment by eseidelGoogle** [comment]
I started a patch for this, but it will need more work:
https://codereview.chromium.org/1277063003
Unfortunately I do not have time to continue the patch and will just continue working around this issue for now.

@abarth mentioned that @MitchRudominer may be interested in this type of bug.

**Comment by MitchRudominer** [comment]
Hmm, I never noticed this @mention of me back on Aug 7 for some reason, sorry. Looks like zra@ has a fix in https://codereview.chromium.org/1351683003/.

**Comment by MitchRudominer** [comment]
By the way as part of the Mojom parser rewrite we are considering disallowing assigning integers to fields of type enum. Would this mean that we could use real Dart enums?

**Comment by zanderso** [comment]
Likely, yes. An enum in Dart is really a class like:
```dart
class E {
  final int index;
  const E(this.index);
  static const E id0 = const E(0);
  . . .
  static const E idn−1 = const E(n - 1);
}
```

With some other utility stuff in it. So if the mojo encoding of enums is the same as Dart's then we can use them directly.

**Comment by zanderso** [comment]
Fixed in https://github.com/domokit/mojo/commit/66f0b734512d5b56ea3cacf9223c160c38d1e7af
