### ISSUE TITLE
System back button event isn't propagated from mojo shell

### ISSUE THREAD

**Issue by ksimbili** [domokit/mojo#361]
onBackPressed() on Activity should be implemented in mojo shell to detect the system back button, which isn't implemented. This is needed for proper handling of navigation stack in the apps.

Also onPause, onResume which allow app to pause in background. This could be useful feature performance wise.

**Comment by emembrives** [comment]
Regarding pausing in background, have you looked into `View::visible` (not sure it works, but there is already a mechanism on the `native_viewport`/`view_manager` side to handle backgrounding and resuming?

Regarding the back button, `kiosk_wm` is also [supposed to handle](https://github.com/domokit/mojo/blob/master/services/kiosk_wm/kiosk_wm.cc#L127) that. If it does not work, then it needs to be fixed; but if you want another system for handling the back button, then we need to think what it would look like.

**Comment by qsr** [comment]
The back button has been broken when we move from handling raw key event to using an IME keyboard. We need to define another mechanism to get the information.

Also it is not clear at all at the moment how this event should be bubbled down from the system.

**Comment by abarth** [comment]
Can we raise the priority of this issue?  This issue is now blocking a demo we'd like to give.

**Comment by qsr** [comment]
I have a CL in progress for this. To be noted, this will be a temporary fix, as the input will have to be reworked as part of Mozart.

**Comment by abarth** [comment]
\o/  Thanks!

**Comment by aghassemi** [comment]
Thanks!

**Comment by qsr** [comment]
Adam -> You can now use mojo:input to listen for the back button on Android.

**Comment by abarth** [comment]
Thanks!
