### ISSUE TITLE
Consider deleting ApplicationDelegate::ConfigureOutgoingConnection

### ISSUE THREAD

**Issue by j9brown** [domokit/mojo#367]
This method is invoked as part of each outgoing connection to deny the connection and/or provide services.  Nobody is using it other than a test case.

Although the filtering might still be useful for implementing certain kinds of security policies one wonders why an application would deny its own outbound connection attempt (since it could easily bypass that policy in other ways).  That said, being able to observe all outgoing connections may be useful for tracing and debugging but still not terribly useful.

As for providing services, a much safer pattern is to call AddService on the returned ApplicationConnection instance from ConnectToApplication since the caller of that method is more likely to have information about what services should be offered than the ApplicationDelegate.  Moreover, ConfigureOutgoingConnection makes it far too easy to accidentally expose services to all outgoing connections including some that could be security sensitive.

All told, I think we should delete this method.

Thoughts?

**Comment by jamesr** [comment]
+1 to removing it.  Configuring a particular connection is much safer (and imo saner), although it's a bit awkward in our C++ bindings at the moment.  Example of doing this 'manually': https://github.com/domokit/mojo/blob/master/shell/context.cc#L306

**Comment by bengoodger** [comment]
+1. FWIW, I was thinking about removing it from the Mandoline fork of Application.

FYI I am making some other changes in the Mandoline fork - e.g. I'm making ConnectToApplication return a scoped_ptr since I think it's a little weird that the ApplicationImpl manages the lifetime of the connections rather than the caller.

**Comment by jamesr** [comment]
returning scoped_ptr is OK if you're OK taking a dependency on //base (or C++11 stdlib) in ConnectToApplication.  We aren't depending on either in the mojo SDK currently.  We'd like to depend on C++11 stdlib, but Chrome on Mac is holding that back.

**Comment by j9brown** [comment]
Incidentally, I'd recommend removing the "Impl" suffix from any classes
which are intended to be part of the Mojo library APIs.

Rationale: Impl usually denotes an internal implementation type so having
Impl in the name makes it look like the application is doing something
wrong (violating encapsulation).

In general, we might seek simpler names such as Application.

Jeff.

**Comment by bengoodger** [comment]
I agree with that general sentiment, I think the hangup here has come from
there being a corresponding mojom interface Application which collides.

The debates we've had have covered the following points:
- which is the canonical interface? the mojom interface or the C++ client
lib?
- in the case of the application library & the view manager it's the client
lib. for other services, it can just be the mojom.
- for cases where the canonical interface is the client lib, the target of
the mojom interface is language binding developers.
- we discussed pushing mojom interfaces into nested interfaces, but since
there wasn't a single rule we felt bad about doing that.

Perhaps in the cases where we intend mojom to be an implementation we
should use the module feature of mojom to namespace the interface, e.g.
module mojo.internal for application.mojom.

-Ben

**Comment by j9brown** [comment]
I've been thinking of the C++ Mojo bindings as the foundation of one
particular C++ based framework rather than as a canonical client
implementation.  There's nothing all that special about these bindings
other than the fact that we think they are generally useful.  Someone else
could quite reasonably build completely different bindings of their own.

Given the importance of IPC in Mojo, it seems reasonably clear that
applications will need to be able to communicate directly over Mojo
interfaces, even though they will likely rely on their framework to provide
an easier foundation to work with (wrappers, base classes, APIs).

So that means we're likely to see this name collision crop up fairly often
because we'll often have two different representations of a given concept
coexisting.  eg. Application (mojom contract type) vs ApplicationImpl
(framework type).

I might recommend one of the following approaches:

1. Push mojom generated types into their own namespace, separate from other
framework types.  eg. mojo::contracts vs mojo.

2. Deemphasize mojom generated types by applying a prefix or suffix.  eg.
IApplication or ApplicationInterface.  (ick)

In general, I would prefer using a "contracts" (or "interfaces") namespace
since it will help with API hygiene and prevent implementation details of
generated code from leaking into the primary API surface of the framework.

An app can always use contract types directly but developers should
generally be shown the framework types first.

Jeff.

**Comment by viettrungluu-cr** [comment]
My two cents:

1. The interface is generally the most important thing, it's undesirable to
clutter names of interfaces with additional verbiage. E.g., if |Foo| is a
mojom interface, the thing that people will deal with the most are
|FooPtr|s (or even |Foo*|s) and |FooRequest|s.

2. Implementations aren't canonical. While it's often the case that an
application has exactly one implementation of |Foo| and thus call it
|FooImpl|, there many cases where an application may want to have multiple
implementations of |Foo|.

3. |ApplicationImpl| is admittedly an odd case, and it's strange to
explicitly use something provided by someone else with "impl" in the name.

Strictly speaking, it's not even part of our C++ bindings system. Instead,
it's part of an additional "library" (called "application") that one may
use to avoid implementing |Application|. (Though given the
oddness/deficiencies of our current application library, if I were
implementing a nontrivial app, I'd be tempted to roll my own.)

Maybe this means that we should hide |ApplicationImpl| behind a suitable
factory function or something like that. (Or provide it as an explicit base
class, if people like to subclass ... though then we'd have a different
naming problem.)

**Comment by bengoodger** [comment]
I copied parts of this discussion over onto mojo-dev, since this is now pretty off-topic for this bug.
