### ISSUE TITLE
Naming of tracing interfaces.

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#375]
I keep confusing TraceController with TraceCoordinator, as both names imply some entity in control of tracing.

Would the naming be clearer if we had:

- **TraceProvider** instead of TraceController, being the thing one needs to implement to provide traces from their app
- **TraceCollector** instead of TraceCoordinator, being the thing that collects traces from the providers

?

@jamesr @viettrungluu-cr @qsr

**Comment by ppiet** [comment]
And this thing:

```
interface TraceDataCollector {
  DataCollected(string json);
};
```

Could become

```
interface TraceRecorder {
  Record(string json);
};
```

**Comment by jamesr** [comment]
SGTM

**Comment by j9brown** [comment]
Nice.

**Comment by MitchRudominer** [comment]
+1
