### ISSUE TITLE
C++ bindings: A Mojom type [sometimes] needs to be declared before it is used in an array.

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#390]
In general I believe a Mojom type declared in a .mojom file may reference another type by identifier regardless of the lexical ordering of the declarations within the .mojom file. However it seems that the C++ generated code becomes illformed if a type is used in an array before it is declared.

For example consider the following two Mojom declarations.
```c++
struct UnionField {
 // fields elided
};

struct UnionType {
  // fields elided
  array<UnionField> fields;
};
```
Notice how `UnionField` is defined before it is used in the array `fields` in the definition of `UnionType`. This order turned out to be necessary because when I reversed the ordering I got the following C++ compilation error: 

>>In file included from gen/mojo/public/interfaces/bindings/mojom_descriptors.mojom.cc:15:
>>In file included from gen/mojo/public/interfaces/bindings/mojom_descriptors.mojom.h:10:
>>In file included from ../../mojo/public/cpp/bindings/array.h:15:
>>In file included from ../../mojo/public/cpp/bindings/lib/array_internal.h:12:
>>../../mojo/public/cpp/bindings/lib/bindings_internal.h:117:20: error: incomplete type >>'mojo::bindings::types::UnionField' named in nested name specifier
>>  typedef typename S::Data_* DataType;
>>                   ^~~
>>../../mojo/public/cpp/bindings/array.h:34:51: note: in instantiation of template class >>'mojo::internal::WrapperTraits<mojo::StructPtr<mojo::bindings::types::UnionField>, true>' requested >>here
>>  typedef internal::Array_Data<typename internal::WrapperTraits<T>::DataType>
>>                                                  ^
>>gen/mojo/public/interfaces/bindings/mojom_types.mojom.h:577:30: note: in instantiation of template >>class 'mojo::Array<mojo::StructPtr<mojo::bindings::types::UnionField> >' requested here
>>  mojo::Array<UnionFieldPtr> fields;
>>                             ^
>>gen/mojo/public/interfaces/bindings/mojom_types.mojom-internal.h:29:7: note: forward declaration of >>'mojo::bindings::types::UnionField'
>>class UnionField;
>>      ^

**Comment by j9brown** [comment]
Whoops.  That would be bad for recursive types.  We might need to change
the code generator to emit forward declarations or something.

**Comment by MitchRudominer** [comment]
Here is another example that shows that it is not always true that a type needs to appear before it is used.

In mojom_types.mojom we have

```c++
union Value {
  // Some stuff
};

struct Attribute {
  string key;
  Value value;
};

struct DeclarationData {
  array<Attribute>? attributes;
 // Other stuff
};
```

When the type of `value` is `String` then it is OK to move the declaration of `Attribute` after the declaration of `DeclarationData` in the file. But when the type of `value` is `Value` this breaks the generated C++ code with the following compilation error:
```
In file included from gen/mojo/public/interfaces/bindings/service_describer.mojom.cc:15:
In file included from gen/mojo/public/interfaces/bindings/service_describer.mojom.h:12:
In file included from ../../mojo/public/cpp/bindings/array.h:16:
In file included from ../../mojo/public/cpp/bindings/lib/array_internal.h:13:
../../mojo/public/cpp/bindings/lib/bindings_internal.h:199:20: error: incomplete type 'mojo::bindings::types::Attribute' named in nested name specifier
  typedef typename S::Data_* DataType;
                   ^~~
../../mojo/public/cpp/bindings/array.h:34:51: note: in instantiation of template class 'mojo::internal::WrapperTraits<mojo::StructPtr<mojo::bindings::types::Attribute>, true, false>' requested here
  typedef internal::Array_Data<typename internal::WrapperTraits<T>::DataType>
                                                  ^
gen/mojo/public/interfaces/bindings/mojom_types.mojom.h:1731:29: note: in instantiation of template class 'mojo::Array<mojo::StructPtr<mojo::bindings::types::Attribute> >' requested here
  mojo::Array<AttributePtr> attributes;
                            ^
gen/mojo/public/interfaces/bindings/mojom_types.mojom-internal.h:40:7: note: forward declaration of 'mojo::bindings::types::Attribute'
class Attribute;
      ^
1 error generated.
```

**Comment by viettrungluu-cr** [comment]
This is a bug in the generated C++ code (i.e., a bug in the C++ code
generator). Mojom itself should not care about order.

**Comment by MitchRudominer** [comment]
Absolutely. Sorry if my wording did not make this clear. I am just using this bug to record some data about the problem in order to make it easier to debug.

**Comment by viettrungluu-cr** [comment]
@vardhan-cr -- could you take a look at this?
