### ISSUE TITLE
Missing dependency in dart build

### ISSUE THREAD

**Issue by johngro** [domokit/mojo#395]
Was attempting my first sync-up and build, and ran into this error.  Re-running gclient sync seemed to fix the issue.

[46/448] ACTION //mojo/dart/apptest:apptest_pkg_helper(//build/toolchain/linux:clang_x64)
FAILED: python ../../mojo/public/tools/dart_pkg.py --package-name apptest --dart-sdk /usr/local/google/home/johngro/turquoise/mojo/src/third_party/dart-sdk/dart-sdk --gen-directory /usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-gen --pkg-directory /usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg --package-root /usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/packages --stamp-file /usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest.stamp --package-sources /usr/local/google/home/johngro/turquoise/mojo/src/mojo/dart/apptest/lib/apptest.dart /usr/local/google/home/johngro/turquoise/mojo/src/mojo/dart/apptest/pubspec.yaml --package-entrypoints /usr/local/google/home/johngro/turquoise/mojo/src/mojo/dart/apptest/lib/apptest.dart --mojom-sources --sdk-ext-directories --sdk-ext-files --sdk-ext-mappings
#0      JavaFile.getCanonicalPath (package:analyzer/src/generated/java_io.dart:48)
#1      JavaFile.getCanonicalFile (package:analyzer/src/generated/java_io.dart:43)
#10     AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6506)
#11     AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6479)
#12     AnalysisContextImpl._cacheDartParseData (package:analyzer/src/generated/engine.dart:2879)
#13     AnalysisContextImpl._getDartParseData (package:analyzer/src/generated/engine.dart:3472)
#14     AnalysisContextImpl.computeKindOf (package:analyzer/src/generated/engine.dart:1712)
#15     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:163)
#16     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:122)
#17     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:406)
#18     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:145)
#19     Driver.start (package:analyzer_cli/src/driver.dart:99)
#2      PackageUriResolver.getCanonicalFile (package:analyzer/src/generated/source_io.dart:412)
#20     main (file:///mnt/data/b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg/analyzer_cli/bin/analyzer.dart:11)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
#3      PackageUriResolver.resolveAbsolute (package:analyzer/src/generated/source_io.dart:466)
#4      SourceFactory._internalResolveUri (package:analyzer/src/generated/source.dart:828)
#5      SourceFactory.resolveUri (package:analyzer/src/generated/source.dart:740)
#6      ParseDartTask.resolveDirective (package:analyzer/src/generated/engine.dart:9619)
#7      ParseDartTask.internalPerform.<anonymous closure> (package:analyzer/src/generated/engine.dart:9562)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:152)
#9      ParseDartTask.internalPerform (package:analyzer/src/generated/engine.dart:9546)
Canonical failed: /usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/packages/test
JavaIOException: IOException FileSystemException: Cannot resolve symbolic links, path = '/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/packages/test' (OS Error: No such file or directory, errno = 2)
[error] Target of URI does not exist: 'package:test/test.dart' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 14, col 8)
[error] Target of URI does not exist: 'package:test/test.dart' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 15, col 8)
[warning] The method 'group' is not defined for the class '_ConnectionToShellApplication' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 32, col 5)
[warning] The method 'setUp' is not defined for the class '_ConnectionToShellApplication' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 33, col 7)
[warning] The method 'tearDown' is not defined for the class '_ConnectionToShellApplication' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 34, col 7)
[warning] The method 'test' is not defined for the class '_ConnectionToShellApplication' (/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart, line 42, col 5)
Failed analyzing ['/usr/local/google/home/johngro/turquoise/mojo/src/out/Debug/gen/dart-pkg/apptest/lib/apptest.dart']
[46/448] LINK ./view_manager_service_unittests
ninja: build stopped: subcommand failed.

@zanderso

**Comment by zanderso** [comment]
Just tried a clean build, and didn't hit this.

//out/Debug/gen/dart-pkg/packages/test should be created before trying to analyze the apptest package. This happens in //mojo/public/tools/dart_pkg.py as part of the dart_pkg() rule. //out/Debug/gen/dart-pkg/packages/test is a symlink to //mojo/dart/apptest/packages/test, which should be populated by the invocation of pub that happens during 'gclient runhooks'. //mojo/dart/apptest/packages/test is itself a symlink into //dart-pub-cache.

I don't think it will fix this problem, but I'm going to do a little cleanup and remove one layer of these symlinks.

If you happen to be able to reproduce this, if you could report the contents (ls -l) of //mojo/dart/apptest/packages, //out/Debug/gen/dart-pkg/apptest, and //out/Debug/gen/dart-pkg/packages, it might provide a hint about what's going on.

**Comment by jamesr** [comment]
Seems likely to be related to #397.
