### ISSUE TITLE
It takes two builds to have "no work to do"

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#397]
This is distinct from the fixed issue that the build would never be satisfied. Now, it takes two builds to satisfy it. I believe this started with: https://codereview.chromium.org/1317713003

/cc @zanderso @johnmccutchan

**Comment by zanderso** [comment]
I am taking a look.

**Comment by zanderso** [comment]
Fixed by https://github.com/domokit/mojo/commit/03c66d2255bf736c9f9f8006152df54e3613efc9
