### ISSUE TITLE
skydb crashes when you click on it

### ISSUE THREAD

**Issue by ojanvafai** [domokit/mojo#40]
1. Load skydb start out/Debug sky/examples/flights-app/index.sky
2. Click on the page. 

I consistently get the following stack.

Received signal 11 SEGV_MAPERR 0000fbadbeef
#0 0x7f788c7b4a5e base::debug::StackTrace::StackTrace()
#1 0x7f788c7b4593 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f78f5bf8340 <unknown>
#3 0x7f788e819ffc blink::NewEventHandler::handlePointerDownEvent()
#4 0x7f788e819e86 blink::NewEventHandler::handlePointerEvent()
#5 0x7f788dccc353 blink::WebViewImpl::handleInputEvent()
#6 0x7f788b8f7aa7 sky::DocumentView::OnViewInputEvent()
#7 0x7f788b8f7af7 sky::DocumentView::OnViewInputEvent()
#8 0x7f788ba22baf mojo::ViewManagerClientImpl::OnViewInputEvent()
#9 0x7f788ba22c15 mojo::ViewManagerClientImpl::OnViewInputEvent()
#10 0x7f788dc66985 mojo::ViewManagerClientStub::AcceptWithResponder()
#11 0x7f788b9977b8 mojo::internal::Router::HandleIncomingMessage()
#12 0x7f788b9976e1 mojo::internal::Router::HandleIncomingMessageThunk::Accept()
#13 0x7f788dc62e5e mojo::ViewManagerServiceResponseValidator::Accept()
#14 0x7f788dc674de mojo::ViewManagerClientRequestValidator::Accept()
#15 0x7f788b994b77 mojo::internal::MessageHeaderValidator::Accept()
#16 0x7f788b99337f mojo::ReadAndDispatchMessage()
#17 0x7f788b990f3b mojo::internal::Connector::ReadSingleMessage()
#18 0x7f788b991439 mojo::internal::Connector::ReadAllAvailableMessages()
#19 0x7f788b9913eb mojo::internal::Connector::OnHandleReady()
#20 0x7f788b991303 mojo::internal::Connector::CallOnHandleReady()
#21 0x7f788d40143b mojo::internal::(anonymous namespace)::OnHandleReady()
#22 0x7f788d4017c7 base::internal::RunnableAdapter<>::Run()

@abarth @esprehn @eseidel

**Comment by ojanvafai** [comment]
I'm not sure, but I think scrolling might be totally broken as well. Loading tests/lowlevel/scrollbars.sky doesn't scroll. Maybe it's just a focus issue though? Can't tell because I can't click.

In either case, it's pretty likely that both of these are side effects of the pointer events transition.

**Comment by abarth** [comment]
Yeah, scrolling isn't going to work.  The way this will work is we deliver scroll gestures and something in the framework needs to actually set scrollTop or otherwise actuate the scroll.

**Comment by abarth** [comment]
I wasn't able to reproduce the crash...

**Comment by abarth** [comment]
I reproed this morning.

**Comment by abarth** [comment]
https://codereview.chromium.org/879543004

**Comment by abarth** [comment]
Fixed!
