### ISSUE TITLE
dart_pub_get.py is too slow

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#403]
During gclient sync:

```
________ running '/usr/bin/python src/mojo/public/tools/git/dart_pub_get.py --repository-root ../../../.. --dart-sdk-directory ../../../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/' in '/usr/local/google/home/vtl/projects/mojo'
Hook '/usr/bin/python src/mojo/public/tools/git/dart_pub_get.py --repository-root ../../../.. --dart-sdk-directory ../../../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/' took 11.51 secs
```

That's a long time.

**Comment by tonygentilcore** [comment]
@zanderso @johnmccutchan Would pub blow up if we tried to do all the `pub get`s in parallel?

**Comment by zanderso** [comment]
If packages each depend on the same package, concurrent invocations of pub could be trying to write the same files in the pub cache at the same time. I'd guess that could have unpredictable results.

@munificent Mojo runs pub on a whole bunch of packages during 'gclient sync'. Is there a known way of improving performance for that use-case? Thanks!

**Comment by munificent** [comment]
>  Is there a known way of improving performance for that use-case?

Are you checking in lockfiles for each of these packages? If all of the dependencies are already in your local pub cache (which they should be after the first time you run it, unless you explicitly blow them away) and you have an up-to-date lockfile, then running pub get will just read a couple of local files to see if things are up to date, and then exit.

**Comment by eseidel** [comment]
Here is the script:
https://github.com/domokit/mojo/blob/master/mojo/public/tools/git/dart_pub_get.py

It uses a custom pub_cache instead of the default one in the home dir (which actually ends up confusing some other tools, like the analyzer which doesn't know about our sekret pub cache)

**Comment by zanderso** [comment]
Gathered a a few numbers from dart_pub_get.py:

In a Mojo SDK consumer on first run, 40 invocations of 'pub get' take ~50s. On second run, those invocations take ~36s. It looks like the first few invocations do most of the work, but an invocation of pub where no work is required still takes on average a bit less than a second.

I also tried running 'pub get' in parallel, each targeting a different pub cache. It blows up. Many invocations time-out trying to download the material-design pub package.

**Comment by munificent** [comment]
> but an invocation of pub where no work is required still takes on average a bit less than a second.

:(

Part of that is just VM startup time. On my Mac laptop, just running `pub version`, which does almost nothing, is:

```
→ time pub version
Pub 1.13.0-edge.e56efa76783dc9cd8895e15a7bf20c7589373061

real	0m0.205s
user	0m0.186s
sys	0m0.029s
```

The rest of that second is probably:

1. Parsing the pubspec.
2. Parsing the lockfile.
3. Making sure the lockfile is up-to-date.
4. Reconstituting the forest of "packages" directories.

My guess is step 4 is where most of the time is going. Once we get rid of "packages" symlinks and pub only has to output a .packages file, that should go away.

**Comment by tonygentilcore** [comment]
How hard is it to get an overall trace or profile?

Any VM startup improvements would also help w/ #405. For (1) and (2), does pub use the Dart `yaml` package? If so, we notice possible perf issues w/ it in https://github.com/dart-lang/yaml/issues/12.

**Comment by munificent** [comment]
> How hard is it to get an overall trace or profile?

It's pretty tricky, or at least if was the last time I tried. Pub spends most of its time waiting on async IO, so it's hard to get a feel for where the time is actually going.

> does pub use the Dart yaml package? If so, we notice possible perf issues w/ it in dart-lang/yaml#12.

Yup. Natalie actually wrote the YAML package initially *for* pub. :) I'll take a look at it and see what I can figure out.
