### ISSUE TITLE
Starting a DartApp should be faster

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#405]
@alhaad and I were noticing that on an android device the first dart snapshot to load in the dart content handler takes about 500ms and subsequent take about 200ms between the time the `DartApp` is created and the first line of the main() method.

I added traces to everything in `mojo/dart/embedder/dart_controller.cc` and found that the first invocation spends its time in `BlockForServiceIsolateLocked` and all the subsequent ones spend their time in `CreateIsolateHelper` (mostly in `PrepareIsolateLibraries` below that).

/cc @qsr @johnmccutchan @zanderso 

Trace:
https://drive.google.com/a/google.com/file/d/0B4R5tpZiLsHzb2FjYjhsVk90a0E/view

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by tonygentilcore** [comment]
Also, interestingly, in the trace there's 1.16s between when `NetworkFetcher::NetworkRequest` for main.mojo finishes and when main.mojo's `DartApp` calls `BlockForServiceIsolateLocked`.

The trace doesn't exactly make it clear what's going on during this time. Hopefully there's a way to improve that. But if not, perhaps the first isolate could be created during this phase.

**Comment by qsr** [comment]
When NetworkFetcher::NetworkRequest ends, all it means is that header has been fetcher. The time is probably used to fetch the rest of the body, and save this to disk.

Offline by default should solve this.

Or is your trace a hot one?

**Comment by tonygentilcore** [comment]
I expected the trace to be warm (ie it was the second run). But thanks for clearing up my misconception about what that method does. Does it make sense to add async traces around fetching the body to verify?

**Comment by tonygentilcore** [comment]
Oh, also, I know we've gone back and forth about content-type vs #! line, but if we could determine the content handler after only the head is fetched, it might allow for better parallelization.

**Comment by qsr** [comment]
Adding an event for downloading the body of the request: https://codereview.chromium.org/1313903004

**Comment by qsr** [comment]
The sniffing of the content type is done without waiting for the full body to be downloaded.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1336613002

**Comment by zanderso** [comment]
@iposva-google as for PrepareIsolateLibraries, do you have any sense if it would help to try to consolidate to have fewer calls to Dart_Invoke and Dart_SetField? Are those crossings expensive?

**Comment by zanderso** [comment]
Tony, is startup still too slow for subsequent loads? Should we close this issue for the service isolate, and open a separate issue for investigating start-up time generally?

**Comment by johnmccutchan** [comment]
There is no longer any low hanging fruit left on the Dart side. The remaining code in `CreateIsolateHelper` and `PrepareIsolateLibraries` is all required. I've dug into this area in the past and found that compilation of dart:core classes (Uri, Map, etc) overwhelms the time.

**Comment by kulakowski** [comment]
Zach, I agree that this issue is done, and that different issue(s) should be created as we find other bottlenecks.
