### ISSUE TITLE
Should be easier to differentiate isolates in Observatory

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#407]
In the isolate list of the Observatory's main page, every isolate shows up as `snapshot_blob.bin$main`. This gets pretty confusing when you have a dozen or so isolates. We should figure out a way to plumb something from mojo that allows them to be labeled better.

/cc @johnmccutchan @zanderso

**Comment by turnidge** [comment]
cc @turnidge

**Comment by zanderso** [comment]
Probably need to thread the app url:

https://github.com/domokit/mojo/blob/master/services/dart/content_handler_main.cc#L166

Through to the Dart_CreateIsolate call:

https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/dart_controller.cc#L278

**Comment by turnidge** [comment]
We could provide an embedder hook to allow the isolate name to be changed from C++.

It is also possible to provide a Dart api that would all an isolate name to be changed from Dart, but not sure that this is what you need.

**Comment by zanderso** [comment]
@johnmccutchan is this issue still valid?
