### ISSUE TITLE
Custom painting should use a display list

### ISSUE THREAD

**Issue by esprehn** [domokit/mojo#41]
Right now it just has all the same APIs as Canvas2D, we probably want something higher level that's display list based with a type like PaintCustom that stores low level commands in case you want to use Canvas2D. Having to store the canvas commands in the common case is not very efficient for playback and makes it hard to tell what the author is doing.

@Hixie @ojanvafai @abarth

**Comment by eseidelGoogle** [comment]
I added one in 197b907de769c8ddaabc5a8e2fa1d6a0c660e319
