### ISSUE TITLE
C++ bindings: support interface requests in structs

### ISSUE THREAD

**Issue by yzshen** [domokit/mojo#418]
/cc @darinf

**Comment by viettrungluu-cr** [comment]
I agree that we should support this. How's the support for other languages?

**Comment by yzshen** [comment]
AFAICT, at least some of them support this. I haven't checked the code to be sure. Will create new issues when/if I find out any of them doesn't support this.

**Comment by vardhan-cr** [comment]
https://codereview.chromium.org/1404913002 fixes this issue (as of Oct 15th).  Closing
