### ISSUE TITLE
Custom painting needs a way to push a transparency layer (FBO)

### ISSUE THREAD

**Issue by esprehn** [domokit/mojo#42]
Lots of custom painting logic requires more than one "layer" so you can draw into another layer and then composite them together (ex. masks or opacity). Just exposing a Canvas2D API doesn't allow this, you need a way to create another RenderSurface to render your children "into".

@Hixie @ojanvafai @abarth

**Comment by Hixie** [comment]
How we solve this depends mostly on how issue #41 is solved.

**Comment by eseidelGoogle** [comment]
I believe this was solved with https://codereview.chromium.org/1144483002 aka b1b0224dc9c5189344fa96101cb0cff8ef328f6b
