### ISSUE TITLE
Tracing a dart app produces a complete event ("src_func":"DartApp") without duration.

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#425]
on ToT, running the dart benchmarks fails because of one trace event present in the collected trace:

```
{"pid":22459,"tid":22489,"ts":6355562007,"ph":"X","cat":"toplevel","name":"MessageLoop::RunTask","args":{"src_file":"../../services/dart/dart_app.cc","src_func":"DartApp"},"tdur":0,"tts":1315},
```

This breaks `benchmark.mojo` which fails hard when a complete event without "dur" is encountered.

We probably should make `benchmark.mojo` more resilient, ie. ignore incorrect trace events with a warning. Separately, it would be interesting to know how we manage to get the base tracing to produce incorrect trace events.

**Comment by zanderso** [comment]
@ppiet is this issue still valid?

**Comment by ppiet** [comment]
I haven't seen it in a while. Let's close and reopen if observed again.
