### ISSUE TITLE
Underspecified dependency in dart build

### ISSUE THREAD

**Issue by smklein** [domokit/mojo#429]
As can be seen on the failed trybots from https://codereview.chromium.org/1351593002/,
unrelated changes can cause the error:

[error] Target of URI does not exist: 'package:unittest/unittest.dart'

to show up. This issue is unrelated to my patch, and likely caused by an abnormal build order.

**Comment by smklein** [comment]
@johnmccutchan @jamesr

**Comment by cdotstout** [comment]
Please fix, trybots are hitting lots of false positives.

**Comment by zanderso** [comment]
I believe John's CL here: https://codereview.chromium.org/1346773002/ will help with this.

**Comment by johnmccutchan** [comment]
Hi,

Yes, my CL will address this and other build bugs.
