### ISSUE TITLE
Mojom Go Compiler Bug for Structs with Imported Unions

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#434]
https://github.com/domokit/mojo/blob/master/mojo/public/tools/bindings/generators/go_templates/encoding_macros.tmpl

I believe this affects generation of structs with unions imported from other mojom files. I ran into this when creating an interface, which has a union argument defined in another mojom file.

I think line 105 is wrong:
`{%   set decoding_function = ('Decode'~ kind|name)|qualified(kind|package) %}`

Instead, this should be better:
`{%   set decoding_function = ('Decode'~ kind.name)|qualified(kind|package) %}`

The reason is that `kind|name` will include the package name if the union is from another mojom module. If `kind.name` is used instead, this should work properly.

For comparison, you can get this now (for package_name.UnionType):
`package_name.DecodepackageName.UnionType(decoder)`

instead of
`package_name.DecodeUnionType(decoder)`

**Comment by jamesr** [comment]
@AlexandreZani @rogulenko

**Comment by AlexandreZani** [comment]
Fixed in
https://codereview.chromium.org/1349423005/
https://codereview.chromium.org/1357733002/

**Comment by jamesr** [comment]
Two things:

*) If you put the string "#123", i.e. for this "#434", in the commit message then github will linkify the issue for you
*) Please include tests for fixes like this to prevent regressions.

Thanks for fixing these.

**Comment by AlexandreZani** [comment]
Is there a trick to making git not treat # as the start of a comment?

**Comment by jamesr** [comment]
Make sure it isn't the first character on a line
