### ISSUE TITLE
Unstick dart mojo / sky pub package dependencies

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#440]
The most recent sky package (0.0.48 package has the version constraint:
  mojo: 0.0.23

But there are published versions of the 'mojo' package 0.0.24 and 0.0.25.  The most recent version of the sky package that can satisfy these versions is 0.0.23, which had the constraint:
  mojo: ^0.0.17

This means that any app that has the pubspec.yaml:
  sky: any
  mojo: any

will end up with mojo 0.0.25, from September 23, and sky 0.0.23, from July 27th.  This combination crashes immediately.  Publishing a new rev of the mojo package can't unstick things.  Adding a more relaxed version of the constraint in the 'sky' package by itself also doesn't help as sky will start crashing again if we publish a new rev of the mojo package that satisfies the constraint but is not stable.

To unstick things I propose we publish a mojo 0.1.0 and promise that if we make a backwards-incompatible change in the package we bump it to mojo 0.2.0, then 0.3.0, etc up to 0.XXXXXX.0 for however large a value of XXXXXX we end up needing.  We then publish a new package of sky with a constraint '>=0.1.0 <0.2.0' and when we need to bump the 'mojo' package minor rev we then publish a new sky with '>=0.2.0 <0.3.0' and repeat.

/cc @johnmccutchan @abarth @tonygentilcore @jimbeveridge

**Comment by jamesr** [comment]
One consequence of this is that instead of having all of 'mojo', 'mojom', 'mojo_services' and 'mojo_apptest' use the exact same version string we'll want to separate these so that not every change to a mojom service packaged into 'mojo_services' requires changing the 'mojo' revision and requiring a new sky push.

**Comment by johnmccutchan** [comment]
SGTM

**Comment by jamesr** [comment]
Still need to publish a sky and sky_services with updated deps to fix this for pub users.

**Comment by jamesr** [comment]
Running `pub get` with a pubspec.yaml that says `mojo: any` and `sky: any` now gets you up-to-date versions of everything.
