### ISSUE TITLE
Rewrite mojo/tools/roll_pub_package_versions.py in Dart and teach it about our versions

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#441]
This script needs to understand our package interdependencies and the difference between a minor rev (backwards incompatible) vs a patch rev (backwards compatible).  It makes more sense to rewrite this in Dart before making major changes to align with our other Dart-based tooling.  The package dependency scheme it needs to understand is described in #440.

**Comment by zanderso** [comment]
@johnmccutchan I believe this issue is resolved. The script to bump the mojo_sdk package version understands the dependance on the leaf packages.
