### ISSUE TITLE
New (?) test flake in ShellHTTPAppTest

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#444]
http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux/builds/3965/steps/App%20tests/logs/stdio

Failure is:

[==========] Running 4 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from ShellHTTPAppTest
[ RUN      ] ShellHTTPAppTest.Http
[INFO:network_fetcher.cc(298)] Caching mojo app http://127.0.0.1:38239/app at /home/chrome-bot/.mojo_url_response_disk_cache/cache/4E02907E821D05D59152083790B13EA4F00AB3C2D7BE49B8F5658F7FD2226EA9/4E02907E821D05D59152083790B13EA4F00AB3C2D7BE49B8F5658F7FD2226EA9
[       OK ] ShellHTTPAppTest.Http (43 ms)
[ RUN      ] ShellHTTPAppTest.Redirect
[INFO:network_fetcher.cc(298)] Caching mojo app http://127.0.0.1:49886/app at /home/chrome-bot/.mojo_url_response_disk_cache/cache/3E1543357DEAC8B7F14B7F7F213870FB4F1F1A13231D1535047479B8963779BE/3E1543357DEAC8B7F14B7F7F213870FB4F1F1A13231D1535047479B8963779BE
[       OK ] ShellHTTPAppTest.Redirect (4 ms)
[ RUN      ] ShellHTTPAppTest.QueryHandling
[INFO:network_fetcher.cc(298)] Caching mojo app http://127.0.0.1:42117/app?bar at /home/chrome-bot/.mojo_url_response_disk_cache/cache/D49CCB8DCAFB901121B58CCAA85C24EDD4521457315637EA100864AA04CF032A/D49CCB8DCAFB901121B58CCAA85C24EDD4521457315637EA100864AA04CF032A
[INFO:network_fetcher.cc(298)] Caching mojo app http://127.0.0.1:42117/app?foo at /home/chrome-bot/.mojo_url_response_disk_cache/cache/D49CCB8DCAFB901121B58CCAA85C24EDD4521457315637EA100864AA04CF032A/D49CCB8DCAFB901121B58CCAA85C24EDD4521457315637EA100864AA04CF032A
../../shell/shell_apptest.cc:167: Failure
Value of: connection_url
  Actual: http://127.0.0.1:42117/app?bar
Expected: GetURL("app?foo")
Which is: "http://127.0.0.1:42117/app?foo"
../../shell/shell_apptest.cc:169: Failure
Value of: connection_url
  Actual: http://127.0.0.1:42117/app?foo
Expected: GetURL("app?bar")
Which is: "http://127.0.0.1:42117/app?bar"
[  FAILED  ] ShellHTTPAppTest.QueryHandling (5 ms)
[----------] 3 tests from ShellHTTPAppTest (52 ms total)

My naive guess would be bad caching.  @qsr

**Comment by qsr** [comment]
The issue is not with caching. The test is wrong as it supposes FIFO behavior between 2 different handles.
