### ISSUE TITLE
Provide a more convenient way to bind local services.

### ISSUE THREAD

**Issue by j9brown** [domokit/mojo#450]
Currently we have to write code like the following to create an InterfaceRequest and bind it to a local implementation.  Notice that the ComponentPtr is only used to transport a value from GetProxy to the method we care about.

ComponentPtr component;
InterfaceRequest\<Component\> component_request = mojo::GetProxy(&component);
component_manager-\>RegisterComponent(component.Pass());
new Component(component_request.Pass());

We can simplify this by providing an inverted version of GetProxy which returns an InterfacePtr and takes an InterfaceRequest by reference instead.  Something like this:

template \<typename Interface\>
InterfacePtr\<Interface\> GetStub(InterfaceRequest<Interface>* request) {
  InterfacePtr\<Interface\> ptr;
  *request = mojo::GetProxy(&ptr);
  return ptr.Pass();
}

At which point the code becomes a little simpler:

InterfaceRequest\<Component\> component_request;
component_manager-\>RegisterComponent(mojo::GetStub(&component_request));
new Component(component_request.Pass());

**Comment by viettrungluu-cr** [comment]
Why don't you just do:
```
ComponentPtr component;
new Component(GetProxy(&component));
component_manager->RegisterComponent(component.Pass());
```
This is essentially equivalent (i.e., equivalent, unless you're doing bad things).

**Comment by j9brown** [comment]
Ah that's true.  This was following an example in interface_request.h.
Maybe I should just update that.
