### ISSUE TITLE
benchmarks: Saved trace are mostly empties

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#458]
The benchmark app is filtering the event he wants depending on the given benchmark. This means that when we save the trace, we do not get any trace from other categories, which means it is not as useful as it could be to investigate performance issue or regression.

**Comment by tonygentilcore** [comment]
What do you guys have in mind for this? It seems like it'd be useful to keep the traces minimal in the common case, but have a --detailed or --all flag or something that enables all categories.

**Comment by tonygentilcore** [comment]
@qsr and I talked offline. He convinced me that any overhead is close enough to a constant that we should just enable all the categories for now.

**Comment by emembrives** [comment]
cc @nellyv
