### ISSUE TITLE
Ganesh is not working on Nexus 6

### ISSUE THREAD

**Issue by eseidel** [domokit/mojo#46]
Ganesh is not working on Nexus 6
@jamesr @abarth

For example loading the sky widgets:
sky/tools/skydb start out/android_Debug sky/examples/widgets/index.sky

Nothing draws.  It just draws white.  You can click in the right area of the screen and get the android keyboard (sky is fully functioning, etc.).

If we try a simpler app:
sky/tools/skydb start out/android_Debug mojo:ganesh_app

That also doesn't work.  It just shows blue.

In both cases we see some graphics-related logs:
V/chromium( 8152): [VERBOSE1:gl_surface.cc(89)] Using egl GL implementation.
I/chromium( 8152): [INFO:debugger.cc(18)] DebugUtil::WaitForDebugger(pid=8152)
E/chromium( 8152): [ERROR:platform_viewport_android.cc(169)] Not implemented reached in virtual void native_viewport::PlatformViewportAndroid::SetBounds(const gfx::Rect&)
V/chromium( 8152): [VERBOSE1:gl_context_egl.cc(57)] EGL_EXT_create_context_robustness supported.
V/chromium( 8152): [VERBOSE1:gl_context_egl.cc(57)] EGL_EXT_create_context_robustness supported.
I/chromium( 8152): [0204/103857:INFO:SkUtilsArm.cpp(126)] Device supports ARM NEON instructions!
I/chromium( 8152): 
V/chromium( 8152): [VERBOSE1:histogram.cc(225)] Histogram: GPU.ProgramCache.BinaryCacheMissTime has bad minimum: 0
E/chromium( 8152): [ERROR:gles2_cmd_decoder.cc(6059)] [GroupMarkerNotSet(crbug.com/242999)!:7C68AEA2]GL ERROR :GL_INVALID_OPERATION : glUniformMatrix3fv: unknown location
V/chromium( 8152): [VERBOSE1:gl_context_egl.cc(57)] EGL_EXT_create_context_robustness supported.
E/chromium( 8152): [ERROR:gles2_cmd_decoder.cc(6059)] [GroupMarkerNotSet(crbug.com/242999)!:7C84AEA2]GL ERROR :GL_INVALID_OPERATION : glUniformMatrix3fv: unknown location
E/chromium( 8152): [ERROR:gles2_cmd_decoder.cc(6059)] [GroupMarkerNotSet(crbug.com/242999)!:7C84AEA2]GL ERROR :GL_INVALID_OPERATION : glUniformMatrix3fv: unknown location

**Comment by eseidel** [comment]
@darinf this is why Sky isn't working on your Nexus 6.

**Comment by eseidel** [comment]
E/chromium(10248): [ERROR:gles2_cmd_decoder.cc(6059)] [GroupMarkerNotSet(crbug.com/242999)!:7C488EA2]GL ERROR :GL_INVALID_OPERATION : glUniformMatrix3fv: unknown location
I/chromium(10248): [0204/120912:INFO:GrGLUtil.cpp(42)] ---- glGetError 0x502(Invalid Operation)
I/chromium(10248): [0204/120912:INFO:GrGLUtil.cpp(44)]  at
I/chromium(10248): 	../../third_party/skia/src/gpu/gl/GrGLProgramDataManager.cpp(194) : 
I/chromium(10248): [0204/120912:INFO:GrGLUtil.cpp(47)] 
I/chromium(10248): 		UniformMatrix3fv(uni.fVSLocation, 1, false, matrix)
I/chromium(10248): [0204/120912:INFO:GrGLUtil.cpp(49)] 
I/chromium(10248):

**Comment by eseidel** [comment]
Got that by defining GR_GL_CHECK_ERROR_START to 1 in GrGLConfig_chrome.h

**Comment by abarth** [comment]
Ganesh now basically works on Nexus 6.  If there are specific problems, we should file new bugs.
