### ISSUE TITLE
missing pnacl_newlib/bin/pydir/loader.py breaks Mac/Android build

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#460]
On a Mac, `ninja -j8 out/android_Debug` gives:

```
ninja: Entering directory `out/android_Debug/'
ninja: error: '../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pydir/loader.py', needed by 'obj/mojo/nacl/translate_mojo_pnacl_tests_to_native.inputdeps.stamp', missing and no known rule to make it
```

This seems to have appeared in 133a395d155f6bb7158be5f597832da7cbf57717. @smklein

**Comment by smklein** [comment]
I'll take a look into this

**Comment by smklein** [comment]
Seems that this is an issue which would have been caught by having a Mac buildbot. I had to set up mojo from scratch on a macbook to be able to repro this issue. I'm working on a fix, but to prevent issues like this in the future, what would it take to get a mac buildbot/trybot?

**Comment by smklein** [comment]
Pending fix at https://codereview.chromium.org/1386803002/

**Comment by ppiet** [comment]
Thanks for looking into this! @jamesr @viettrungluu-cr for the question about a mac buildbot.

**Comment by jamesr** [comment]
Mac bots might come in the medium term but I wouldn't expect any in the immediate/short term.
