### ISSUE TITLE
Publish the Mojo Dart tracing helper library through dart pub

### ISSUE THREAD

**Issue by emembrives** [domokit/mojo#462]

**Comment by tonygentilcore** [comment]
I believe mojo_apptest would be a reasonable pattern to follow for this (https://codereview.chromium.org/1319503004/). John also mentioned he has tracing support planned for dart core library.

/cc @johnmccutchan @zanderso

**Comment by johnmccutchan** [comment]
Note that Dart is getting first class support for tracing making this library likely optional.

**Comment by emembrives** [comment]
Do you know when this is happening, and do you have a prospective API so I can check all our bases are covered?

**Comment by johnmccutchan** [comment]
The API is not finish but will be part of dart:developer, the synchronous pieces are already available (might not be rolled into Mojo):

https://api.dartlang.org/133972/dart-developer/Timeline-class.html

**Comment by emembrives** [comment]
Regarding the API: Are you planning to also add "instant" events (events without a duration), in addition to the asynchronous tracing?

**Comment by johnmccutchan** [comment]
@emembrives Yes both instant and asynchronous events will be added.

**Comment by zanderso** [comment]
dart:developer with the above mentioned features is now available in Mojo, so I don't think we need to publish this package. I've also removed it from the Mojo tree. Please file issues against the Dart VM if more features are needed in the dart:developer Timeline and TimelineTask classes. Thanks!
