### ISSUE TITLE
Support running/testing in checked mode for Dart apps.

### ISSUE THREAD

**Issue by aghassemi** [domokit/mojo#465]
I would be nice to be able to run `mojo_run` or `mojo_test` in checked mode.

After chatting with @jamesr, we should be able to do something similar to the already existing `enable-checked-mode` in Flutter.

something like:
```
--args-for="mojo:dart_handler --enable-checked-mode"
```

It would also be great if `mojo_test` can fill out the `args-for` automatically based on the test config,
maybe one can do:( note the new `checked` )
```
tests = [
	{
		"test": "https://test.exmaple.com/test.dart",
		"type": "dart",
 		"checked": true
	}
]
```

**Comment by jamesr** [comment]
@johnmccutchan @zanderso

**Comment by zanderso** [comment]
We currently enable checked mode on a per-app basis, but In Debug builds, all apps should already be running in checked mode. Are you noticing that that isn't the case? Do you also need to enable checked mode in Release builds?

**Comment by jamesr** [comment]
Release vs debug is a build time construction and doesn't have any definition when running dart code directly in the content handler.

**Comment by zanderso** [comment]
In Debug builds we append ?strict=true to Dart's content handler URI for all Dart apps, this causes the content handler to run that app in checked mode. In a Release build, you can also do that by setting a flag in the build rule.

**Comment by jamesr** [comment]
Right, but Ali isn't going through the packaging step (nor should he need to) in order to run his dart app.  He should be able to just say "run this .dart file in checked mode".

**Comment by zanderso** [comment]
Oh, okay. I see now. I missed that he wasn't going through the packaging step. Thanks for clarifying. I think it makes sense in that case to parse a --enable-checked-mode flag out of the arguments for the content handler, but note that in that case *every* app that runs in that content handler will run in checked mode.

**Comment by ppiet** [comment]
Thanch, Zach!

Re-opening for the other part of the request, ie. teaching `mojo_test` to set this automatically. I think the strict mode should be enabled for dart apptests by default, unless `strict_mode: False` is specified in the spec file.
