### ISSUE TITLE
Run mojo shell on multiple Android devices

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#470]
When running mojo shell on Android, it looks like fixed ports are used in the code: 5037, 9998, 31839, 31840, and 31841

These ports are found in files like:
https://github.com/domokit/mojo/blob/master/mojo/devtools/common/remote_adb_setup
https://github.com/domokit/mojo/blob/a4f8faf06a4a5417c2e33fc57f674077511867f4/mojo/devtools/common/devtoolslib/shell_arguments.py

Since the values are hard-coded, running a 2nd mojo shell on Android leads to an error:
```
Failed to start http server for [('', ['/<my_project_path>'])] on port 31841: Address already in use.
  Run `fuser 31841/tcp` to find out which process is using the port;
  or `fuser -k 31841/tcp` terminate it.
```

Can the scripts be modified to work around the used port issue? If the ports to be used must be specified manually, that would also be acceptable.

For my program, I think I can make do by disconnecting the first device and then starting the second. I give up convenience and adb output, but I can at least get started. However, I eventually want to do this for 4+ devices, so my manual workaround does not scale.

@ppiet @qsr

**Comment by ppiet** [comment]
Thanks for filing the request. The tools use predictable (nicer word for hardcoded) ports to facilitate caching between runs and port forwarding for remote_adb_setup.

I think that we should have a mode where all ports are system allocated - for instance, running `mojo_run --wild-ports` would always pick a fresh set of ports. (better flag name pending)

Would that address your use case, or would you be concerned about regression on caching?

**Comment by afandria** [comment]
Yes, --wild-ports sounds like the most convenient way.

I'm not sure if there will be issues if I don't cache. I'm not familiar with the benefits. An alternative would be to allow reuse of the same ports.

===========================

It turns out that the "unplugging" idea did not work very well. Sometimes my apps would crash, and using `adb logcat` without mojo_shell/mojo_run seems to lose stdout/stderr.

My current workaround (in-progress) is to
* modify mojo/devtools/common/remote_adb_setup
* modify mojo/devtools/common/devtoolslib/http_server.py
* use my own mojo_config

This prevents the 3 http server conflicts:
* 31839: http server for https://core.mojoapps.io
* 31840: http server for the local mojo: origin
* 31841: http server for base mappings

I use 3 environment variables to work around this, and my mojoconfig needs to also obtain that config-alias. I left default variables where I could, but I was unable to for mojo_config. (That is why I am using my own.) It would be very nice if the config-alias could contain a default value when it is unset.

* remote_adb_setup script handled core mojo port, the local mojo port, and the base mappings port.
* http_server.py used a similar strategy to replace the local mojo port and the base mappings port.
* I used my own mojoconfig to avoid the core mojo port conflict.

I still have to specify the ports on my own for each device, but it does allow simultaneous mojo_shells to run.

I could instead submit this as a pull request. Since the defaults remain the same for each file, there won't be any effect on other users.

**Comment by ppiet** [comment]
If the option to run with system allocated ports works for you (the main drawback is that things will be slower and you won't be able to run over remote_adb_setup), I will be happy to put together a patch for that. This seems to be a universally useful thing and should not be too hard to implement.

Side-note: good point about default value for config-aliases. Would you mind filing a bug for this feature in https://github.com/domokit/devtools/issues ?

**Comment by afandria** [comment]
I actually do not know much about what `remote_adb_setup` does, but it might be important. If it is the one serving image assets and binaries to the phone from my desktop, then I will need it for development.

Also, I filed that issue: https://github.com/domokit/devtools/issues/51

**Comment by afandria** [comment]
Looking at `remote_adb_setup` again, it looks like it's not called by any other file. It looks like it is literally for people working remotely from their devices.

In other words, I do think it would be very valuable to have system allocated ports. Thank you!

**Comment by qsr** [comment]
@ppiet Instead of using random ports, should we use the device id as  seed for the port numbers? So that port are unique per target devices?

**Comment by ppiet** [comment]
Actually, we should probably use system-allocated ports on the host, and forward them to the fixed ports (the same values we use now) on each device. This should allow to run on multiple devices and preserve caching. The only thing that breaks is adb_remote_setup.

I wonder if we should do this by default, and add a switch `--fixed-host-ports` for adb_remote_setup, or the other way round.

**Comment by ppiet** [comment]
@afandria yes, nothing depends on `adb_remote_setup`, it's only for remote work (building on the remote host, running on device attached to the local laptop).

**Comment by ppiet** [comment]
Proposed CL: https://codereview.chromium.org/1397193005/ . @afandria you should be able to patch it in and have everything "just working" with `--free-host-ports`.

**Comment by afandria** [comment]
Thanks @ppiet. It works perfectly!
