### ISSUE TITLE
Async callbacks should be governed by a scheduler in sky

### ISSUE THREAD

**Issue by esprehn** [domokit/mojo#48]
We should reshape the timer API to be in terms of a scheduler with priorities for all tasks instead of setTimeout(), setInterval(), etc.

Scheduler.nextFrame(fn, priority);
nextMicrotask(...)
nextTime(...)
repeating(fn, time, priority)

I think we should also consider killing any task that takes longer than ~10ms. You should run multiple steps continuation style if you want to do something expensive.

@abarth @Hixie @ojanvafai

**Comment by domenic** [comment]
> I think we should also consider killing any task that takes longer than ~10ms. You should run multiple steps continuation style if you want to do something expensive.

I'm really curious to hear how this discussion goes. Breaking JS's run-to-completion model has some bad consequences, but I agree that for user experience purposes this would be nice.

**Comment by Hixie** [comment]
[animation.md](https://github.com/domokit/mojo/blob/master/sky/specs/animation.md) has whenIdle(), callback gets 1ms; beforePaint(), which takes a priority and drops all those that couldn't run in time, and nextFrame(), which is the same but for the next frame.

Timer() and Timer.periodic() don't have priority or budget, but maybe we should add one or both.

In [runloop.md](https://github.com/domokit/mojo/blob/master/sky/specs/runloop.md) it talks about giving each part of the run loop 1ms to do its work. I figured at some point we'd have an API where you can tweak those numbers (but keeping it all within the max frame budget).

**Comment by esprehn** [comment]
@domenic Sky uses dart.

**Comment by domenic** [comment]
@esprehn ah sorry, didn't realize there'd been a complete switch. Dart doesn't have a run-to-completion model, or...?

**Comment by esprehn** [comment]
@domenic It currently does, but we're not sure what we might change. I doubt we'd break run to completion, but we might make a lot of APIs throw a DeadlineExceeded() exception.

**Comment by abarth** [comment]
We have a scheduler now.  We should file separate bugs relating to specific things we want the scheduler to do.
