### ISSUE TITLE
mojo: Android "service name too long" (1024 chars)

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#488]
I'm running a fairly long `mojo_run` command on Android.

It has gotten long for various reasons, mainly the `--args-for` flags that are passed to each mojo app.

Unfortunately, this means that I have hit the 1024 character limit that adb allows when doing `adb_connect` to Android.

I think this is solvable if mojo stores the command it wants to run into a file, pushes that file to Android and then executes it (i.e., the way [this StackOverflow thread](http://stackoverflow.com/questions/21089365/adb-shell-inputtext-too-long) suggests).

**Comment by ppiet** [comment]
This is pretty impressive! cc @qsr

**Comment by afandria** [comment]
Thank you! I'll let you know how it goes shortly.

**Comment by afandria** [comment]
"Shortly". Anyway, it works great. Thanks for the help!
