### ISSUE TITLE
Mojom: Optional members of union type fail validation when null

### ISSUE THREAD

**Issue by dalesat** [domokit/mojo#490]
I'm defining a union type and including it as an optional member of a struct:

union Foo {
  uint8 foo8;
  uint32 foo32;  
}

struct Bar {
  Foo? foo;
}

If I create a Bar and set bar->foo = nullptr, I get a validation failure e.g. "null foo8 field in Foo" when bar is sent.

**Comment by vardhan-cr** [comment]
Hm, I tried that exact example and it seems to run without any errors on both serialization and deserialization:

int main() {
  examples::Bar b;
  b.foo = nullptr;

  char buf[1000];
  MOJO_CHECK(b.Serialize(buf, sizeof(buf)));
  b.Deserialize(buf);
  return 0;
}

(^ this won't do validation when it deserialize()s, but i'm guessing the error you're experiencing is when you're Serializing (i.e., sending the Bar))

Just to clarify, this is C++?

**Comment by AlexandreZani** [comment]
That error message should only trigger if foo8 is a non-nullable object and it is null.

**Comment by AlexandreZani** [comment]
Sorry, that was overly brief and perhaps not helpful.

Can you share the actual mojom file Dale? The error message should only be able to occur when foo8 is a pointer. (struct, union, map, array or string) I also have a test that covers the above case and it's still passing, so I'm really curious as to what is going on.

**Comment by dalesat** [comment]
Here's the actual mojom I was using. I would see "null multiplexed field in MediaType" when I had a MediaType with a null details field. When I added a dummy MediaTypeDetails instead, it worked. 

// A union of all media type details.
union MediaTypeDetails {
  // Each field name should correspond to a value in MediaTypeScheme.
  MultiplexedMediaTypeDetails multiplexed;
  LpcmMediaTypeDetails lpcm;
  CompressedAudioMediaTypeDetails compressed_audio;
  VideoMediaTypeDetails video;
};

// Specifies a type of media.
struct MediaType {
  // Broadly identifies the media type and indicates how the details field is
  // to be interpreted.
  MediaTypeScheme scheme;

  // Scheme-dependent details.
  MediaTypeDetails? details;
};

**Comment by AlexandreZani** [comment]
Thanks. I can reproduce.

**Comment by AlexandreZani** [comment]
I have a fix out for review. You can follow along here
https://codereview.chromium.org/1423833002/
