### ISSUE TITLE
Dart bindings for mojom too aggressive about throwing exceptions

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#496]
See https://github.com/flutter/engine/issues/1787 for context.

When the remote side of a Mojo message pipe closes, the proxy object we use to communicate over that message pipe should start silently swallowing messages instead of throwing exceptions.  The user of the proxy object should be able to subscribe to "connection error" events via a separate mechanism (e.g., a dedicated `Future` for that purpose).

This change will make the Dart bindings more like the C++ bindings (e.g., https://github.com/domokit/mojo/blob/master/mojo/public/cpp/bindings/binding.h#L184)

@zanderso @jamesr

**Comment by zanderso** [comment]
Working on a fix here: https://codereview.chromium.org/1410373004/
