### ISSUE TITLE
C++ bindings:  generate C++ structs for interface method calls/responses (similar to the ones generated for mojo structs)

### ISSUE THREAD

**Issue by vardhan-cr** [domokit/mojo#505]
CL tracking bug.

This will help us construct interface method calls we can easily MojoWriteMessage(), although these serialized params still need to be framed with a |mojo::Message| and written the same way mojo::internal::Connector::Accept() does.

**Comment by j9brown** [comment]
Can we try to do this in a way that avoids heap allocations?

**Comment by vardhan-cr** [comment]
When constructing a method calls' params manually, it's currently possible to /somewhat/ avoid heap allocations: instead of a StructPtr, you can just use Struct and Serialize() it.  I say /somewhat/ because the Struct may contain a AnotherMojoStruct in the form of AnotherMojoStructPtr (which is heap allocated if it's not-null since it's a Ptr).

When constructing a message itself (that contains the params struct and handles), the MessageBuilder currently heap allocates a Message and passes the user a pointer that they can fill up.  We can try to fix this 

So doing method calls currently incurs atmost 2 heap allocations, each on the order of the size of params.  I think the scope of making all method calls avoid heap allocations is a little beyond this issue (it's mostly tracking some CLs i'm working on) that might require more sweeping work, but of course we should fix it!

**Comment by viettrungluu-cr** [comment]
I believe this was actually fixed (by https://codereview.chromium.org/1415713005). Please re-open if I'm missing something.
