### ISSUE TITLE
SkyShell crashes when clicking on a link

### ISSUE THREAD

**Issue by eseidel** [domokit/mojo#51]
SkyShell crashes when clicking on a link

@abarth

signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 13541 (ui_thread)
pid: 13510, tid: 13541, name: ui_thread  >>> org.domokit.sky.shell <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
     r0 00000000  r1 00007000  r2 00000004  r3 aec2c300
     r4 aee5da60  r5 00000000  r6 b4855c00  r7 aebff5e8
     r8 aebff600  r9 59204038  sl aebff648  fp b4855c37
     ip a3a77460  sp aebff5d8  lr a3593a21  pc a3593a24

Stack Trace:
  RELADDR   FUNCTION                                                                                                          FILE:LINE
  003b1a24  blink::HTMLAnchorElement::handleClick(blink::Event*)                                                              /src/mojo/src/out/android_Release/../../sky/engine/core/html/HTMLAnchorElement.cpp:120
  0039aaf9  blink::EventDispatcher::dispatchEventPostProcess()                                                                /src/mojo/src/out/android_Release/../../sky/engine/core/events/EventDispatcher.cpp:168 (discriminator 2)
  0039ad5d  blink::EventDispatcher::dispatch()                                                                                /src/mojo/src/out/android_Release/../../sky/engine/core/events/EventDispatcher.cpp:93
  0039ac0b  blink::EventDispatcher::dispatchEvent(blink::Node*, WTF::PassRefPtr<blink::EventDispatchMediator>)                /src/mojo/src/out/android_Release/../../sky/engine/core/events/EventDispatcher.cpp:51 (discriminator 1)
  003729fb  blink::Node::dispatchEvent(WTF::PassRefPtr<blink::Event>)                                                         /src/mojo/src/out/android_Release/../../sky/engine/core/dom/Node.cpp:1475 (discriminator 2)
  003a84fb  blink::NewEventHandler::dispatchClickEvent(blink::Node&, blink::WebPointerEvent const&)                           /src/mojo/src/out/android_Release/../../sky/engine/core/frame/NewEventHandler.cpp:118 (discriminator 1)
  003a898f  blink::NewEventHandler::handlePointerUpEvent(blink::WebPointerEvent const&)                                       /src/mojo/src/out/android_Release/../../sky/engine/core/frame/NewEventHandler.cpp:227 (discriminator 3)
  00260065  blink::WebViewImpl::handleInputEvent(blink::WebInputEvent const&)                                                 /src/mojo/src/out/android_Release/../../sky/engine/web/WebViewImpl.cpp:319 (discriminator 3)
  0008a20d  sky::shell::Engine::OnInputEvent(mojo::StructPtr<sky::InputEvent>)                                                /src/mojo/src/out/android_Release/../../sky/shell/ui/engine.cc:113 (discriminator 1)
  001cee8d  sky::ViewportObserverStub::Accept(mojo::Message*)                                                                 /src/mojo/src/out/android_Release/gen/sky/services/viewport/viewport_observer.mojom.cc:466 (discriminator 2)
  001cec5f  sky::ViewportObserverRequestValidator::Accept(mojo::Message*)                                                     /src/mojo/src/out/android_Release/gen/sky/services/viewport/viewport_observer.mojom.cc:560
  0021fb9f  mojo::internal::MessageHeaderValidator::Accept(mojo::Message*)                                                    /src/mojo/src/out/android_Release/../../mojo/public/cpp/bindings/lib/message_header_validator.cc:78
  0021fa69  mojo::ReadAndDispatchMessage(mojo::MessagePipeHandle, mojo::MessageReceiver*, bool*)                              /src/mojo/src/out/android_Release/../../mojo/public/cpp/bindings/lib/message.cc:76
  0021f543  mojo::internal::Connector::ReadSingleMessage(int*)                                                                /src/mojo/src/out/android_Release/../../mojo/public/cpp/bindings/lib/connector.cc:154 (discriminator 1)
  0021f617  mojo::internal::Connector::ReadAllAvailableMessages()                                                             /src/mojo/src/out/android_Release/../../mojo/public/cpp/bindings/lib/connector.cc:181
  0021f667  mojo::internal::Connector::OnHandleReady(int)                                                                     /src/mojo/src/out/android_Release/../../mojo/public/cpp/bindings/lib/connector.cc:131
  v------>  base::Callback<void (int)>::Run(int const&) const                                                                 /src/mojo/src/out/android_Release/../../base/callback.h:396 (discriminator 2)
  000b7943  mojo::common::HandleWatcher::StateBase::NotifyAndDestroy(int)                                                     /src/mojo/src/out/android_Release/../../mojo/common/handle_watcher.cc:350 (discriminator 2)
  000b92e5  mojo::common::MessagePumpMojo::DoInternalWork(mojo::common::MessagePumpMojo::RunState const&, bool)               /src/mojo/src/out/android_Release/../../mojo/common/message_pump_mojo.cc:191 (discriminator 1)
  000b942d  mojo::common::MessagePumpMojo::DoRunLoop(mojo::common::MessagePumpMojo::RunState*, base::MessagePump::Delegate*)  /src/mojo/src/out/android_Release/../../mojo/common/message_pump_mojo.cc:150
  000b951f  mojo::common::MessagePumpMojo::Run(base::MessagePump::Delegate*)                                                  /src/mojo/src/out/android_Release/../../mojo/common/message_pump_mojo.cc:119
  000a441d  base::RunLoop::Run()                                                                                              /src/mojo/src/out/android_Release/../../base/run_loop.cc:55
  0009c3a5  base::MessageLoop::Run()                                                                                          /src/mojo/src/out/android_Release/../../base/message_loop/message_loop.cc:307
  v------>  base::Thread::Run(base::MessageLoop*)                                                                             /src/mojo/src/out/android_Release/../../base/threading/thread.cc:174
  000a9743  base::Thread::ThreadMain()                                                                                        /src/mojo/src/out/android_Release/../../base/threading/thread.cc:228
  000a8d4f  ThreadFunc                                                                                                        /src/mojo/src/out/android_Release/../../base/threading/platform_thread_posix.cc:80
  00016baf  __pthread_start(void*)+30                                                                                         /system/lib/libc.so
  00014af3  __start_thread+6                                                                                                  /system/lib/libc.so

**Comment by eseidel** [comment]
To repro:

ninja -C out/android_Release -j 1024
adb install -r out/android_Release/apks/SkyShell.apk
adb shell am start -a "android.intent.action.VIEW" -d "sky:domokit.github.io/home"
(click on a link)
sky/tools/skydb print_crash

**Comment by abarth** [comment]
Links don't exist anymore.
