### ISSUE TITLE
README.md talks about Sky

### ISSUE THREAD

**Issue by kulakowski** [domokit/mojo#510]
https://github.com/domokit/mojo/blob/master/README.md#running-a-sky-app should probably refer to flutter these days.

**Comment by ppiet** [comment]
I wanted to update these instructions to mention the `flutter run_mojo` workflow instead, but I can't get it to work:

```
$ flutter run_mojo --android --mojo-path /usr/local/work/mojo/src/mojo/
Exception: Path "/usr/local/work/mojo/src/mojo/" does not exist
```

Even though:
```
$ stat /usr/local/work/mojo/src/mojo/
  File: ‘/usr/local/work/mojo/src/mojo/’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 811h/2065d	Inode: 2756414     Links: 24
Access: (0750/drwxr-x---)  Uid: (183516/     ppi)   Gid: ( 5000/     eng)
Access: 2015-11-04 15:42:48.752004011 +0100
Modify: 2015-10-29 17:33:48.354620301 +0100
Change: 2015-10-29 17:33:48.354620301 +0100
 Birth: -
```

For now I will just delete the old instructions, as these won't work either as we switched to flx.

@jamesr

**Comment by tonygentilcore** [comment]
@ppiet I think you need the path to `src/`, not `src/mojo`. Take the instructions at the top of the `examples/dart/camera_video/lib/main.dart` for example:

```sh
cd examples/dart/camera_video
rm pubspec.lock  # the one checked in is too old
pub get
pub run flutter build
pub run flutter run_mojo --mojo-path=../../.. --android
```

**Comment by ppiet** [comment]
Good catch, but still no luck

```
$ flutter run_mojo --android --mojo-path /usr/local/work/mojo/src/
Exception: Path "/usr/local/work/mojo/src/" does not exist
```

```
stat /usr/local/work/mojo/src/
  File: ‘/usr/local/work/mojo/src/’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
```

**Comment by ppiet** [comment]
It seems that what `--mojo-path` needs to be depends on the target. We need:

 - a path to **mojo_run** when running on Android, ie. when `--android` is passed
 - a path to the mojo src directory when running on Linux

**Comment by apwilson** [comment]
Yes that's right.  I think it was changed very recently to this behavior.
