### ISSUE TITLE
Perf dashboard should have commit SHAs for each point

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#514]
I wanted to check whether https://codereview.chromium.org/1413713014/ had any impact on the startup graphs, but afaict, the dashboard doesn't show the git commit sha for each point. I believe there's a field in the `versions` dict that'd let the bot pass on this information, but it wasn't totally clear from the docs:
http://www.chromium.org/developers/speed-infra/performance-dashboard/sending-data-to-the-performance-dashboard

/cc @ppiet

**Comment by ppiet** [comment]
We do send the commit sha in `versions` but it somehow isn't surfaced in the dashboard. Sent a question to the dashboard team.

**Comment by ppiet** [comment]
Aaand thanks to Quinten this is now fixed.
