### ISSUE TITLE
Perf dashboard should display traces by default

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#515]
I *think* that the perf dashboard displays traces by default if they're marked core or important or something like that. It isn't documented at http://www.chromium.org/developers/speed-infra/performance-dashboard/sending-data-to-the-performance-dashboard , but I'm sure there's a way to mark the traces to be displayed by default.

/cc @ppiet

**Comment by tonygentilcore** [comment]
ps. It might also be helpful to create a shortened link to the set of graphs we think are most useful. Something like:
https://chromeperf.appspot.com/report?sid=daa8d4f4b2cc718cc682d960cb61f51ce374f5a8ab2a37296fea00fe89e1e077

The link could live in `README.md` or something.

**Comment by ppiet** [comment]
As for dashboard display, https://github.com/catapult-project/catapult/issues/1692 tracks showing all traces when none is marked as "important". Until this is fixed, I agree we should mark our traces as "important" ourselves, will do. Ack for the PS too.

**Comment by ppiet** [comment]
As we enabled monitoring on our datapoints, the graphs are now displayed by default.
