### ISSUE TITLE
[New mojom parser] The translation layer should preserve the information that an identifier was referred to.

### ISSUE THREAD

**Issue by AlexandreZani** [domokit/mojo#518]
Currently, the translation layer resolves the value of identifiers and passes that resolved value to the generators. However, sometimes, a value was referred to via an identifier. We want to give generators the option to use this information if they so desire. This may also be necessary in the case of enums.

There are 6 use-cases along 2 axis.
Axis 1:
1) An identifier is used to refer to a constant.
2) An identifier is used that refers to an enum value.

Axis 2:
1) The identifier is assigned to a constant.
2) The identifier is set as the default value of a field.
3) The identifier is set as the value of an enum value.

Examples:

struct Foo {
  enum Bar {
    ONE, TWO
  };

  Bar field = ONE;
};

const int32 someValue = 52;
const int32 idValue = someValue;

enum SomeEnum {
  VAL = someValue;
};
/cc @MitchRudominer

**Comment by MitchRudominer** [comment]
Could you please use a few more words to explain what you mean and possibly even give an example.
