### ISSUE TITLE
SkyShell crashes attempting to load subresources

### ISSUE THREAD

**Issue by eseidel** [domokit/mojo#52]
SkyShell crashes attempting to load subresources

@abarth 

signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 13685 (ui_thread)
pid: 13652, tid: 13685, name: ui_thread  >>> org.domokit.sky.shell <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
     r0 00000000  r1 aeaed5ac  r2 00000001  r3 a3a30590
     r4 5fb34000  r5 aeaed5ac  r6 5fb34010  r7 aeaed5d8
     r8 5fa80000  r9 5fb28028  sl 5fb280d8  fp aeaed80c
     ip a3a6dd18  sp aeaed5a8  lr a3586031  pc a3586034

Stack Trace:
  RELADDR   FUNCTION                                                                                                          FILE:LINE
  003a4034  blink::ResourceLoader::start()                                                                                    /src/mojo/src/out/android_Release/../../sky/engine/core/fetch/ResourceLoader.cpp:152
  003a2379  blink::Resource::load(blink::ResourceFetcher*, blink::ResourceLoaderOptions const&)                               /src/mojo/src/out/android_Release/../../sky/engine/core/fetch/Resource.cpp:186 (discriminator 1)
  003a3807  blink::ResourceFetcher::requestResource(blink::Resource::Type, blink::FetchRequest&)                              /src/mojo/src/out/android_Release/../../sky/engine/core/fetch/ResourceFetcher.cpp:291 (discriminator 2)
  003a399b  blink::ResourceFetcher::fetchImage(blink::FetchRequest&)                                                          /src/mojo/src/out/android_Release/../../sky/engine/core/fetch/ResourceFetcher.cpp:184
  003bcee9  blink::ImageLoader::doUpdateFromElement(blink::ImageLoader::UpdateFromElementBehavior)                            /src/mojo/src/out/android_Release/../../sky/engine/core/loader/ImageLoader.cpp:213 (discriminator 1)
  0036fb49  blink::Microtask::performCheckpoint()                                                                             /src/mojo/src/out/android_Release/../../sky/engine/core/dom/Microtask.cpp:77 (discriminator 1)
  0009c781  base::MessageLoop::RunTask(base::PendingTask const&)                                                              /src/mojo/src/out/android_Release/../../base/message_loop/message_loop.cc:450 (discriminator 7)
  0009cd4d  base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&)                                                /src/mojo/src/out/android_Release/../../base/message_loop/message_loop.cc:458
  0009d4e5  base::MessageLoop::DoWork()                                                                                       /src/mojo/src/out/android_Release/../../base/message_loop/message_loop.cc:570
  000b943d  mojo::common::MessagePumpMojo::DoRunLoop(mojo::common::MessagePumpMojo::RunState*, base::MessagePump::Delegate*)  /src/mojo/src/out/android_Release/../../mojo/common/message_pump_mojo.cc:155
  000b951f  mojo::common::MessagePumpMojo::Run(base::MessagePump::Delegate*)                                                  /src/mojo/src/out/android_Release/../../mojo/common/message_pump_mojo.cc:119
  000a441d  base::RunLoop::Run()                                                                                              /src/mojo/src/out/android_Release/../../base/run_loop.cc:55
  0009c3a5  base::MessageLoop::Run()                                                                                          /src/mojo/src/out/android_Release/../../base/message_loop/message_loop.cc:307
  v------>  base::Thread::Run(base::MessageLoop*)                                                                             /src/mojo/src/out/android_Release/../../base/threading/thread.cc:174
  000a9743  base::Thread::ThreadMain()                                                                                        /src/mojo/src/out/android_Release/../../base/threading/thread.cc:228
  000a8d4f  ThreadFunc                                                                                                        /src/mojo/src/out/android_Release/../../base/threading/platform_thread_posix.cc:80
  00016baf  __pthread_start(void*)+30                                                                                         /system/lib/libc.so
  00014af3  __start_thread+6                                                                                                  /system/lib/libc.so

To repro:

ninja -C out/android_Release -j 1024
adb install -r out/android_Release/apks/SkyShell.apk
adb shell am start -a "android.intent.action.VIEW" -d "sky:domokit.github.io/sky/examples/stocks/index.sky"
(click on a link)
sky/tools/skydb print_crash

**Comment by abarth** [comment]
Yeah, images specifically.
