### ISSUE TITLE
Media interfaces should close connections instead of calling back with error codes.

### ISSUE THREAD

**Issue by johngro** [domokit/mojo#521]
Per request from Jeff, most of the method in initial common media and audio specific interfaces should close connection in the case of client side failures which they should have avoided using a-priori knowledge, instead of returning a failure code.

Rationale:
1) You always need a connection error handler anyway.
2) Clients are not going to do anything at runtime about this anyway aside from print a message for debugging purposes and crash/shutdown/restart.
3) Not having callbacks with error codes which should always say "A-OK boss!" facilitates pipe-lining of messages and reduces client side complexity to just having a generic "something fatal happened" handler.

Examples of what should change:
1) Invalid configuration requested for AudioTrack?  Close connection.
2) MediaPacket sent whose regions violates requirements (out of bounds, mis-aligned, segmentation limit violation, etc..)?  Close connection.
3) Set a rate on the Rate Control interface which is singular in the local->media direction?  Close connection.

Note:  Currently, there is no way to send back debugging information to let the client know why we chose to hang up the phone.  This is going to be awful to debug, especially if many interface requests are in-flight simultaneously.  In theory, something is going to be done about this someday, but it is unclear what or when.

**Comment by jamesr** [comment]
A service can produce log messages for some types of errors to help developers out.

**Comment by johngro** [comment]
yes, I discussed this with both Trung and Jeff some already.  You can do this, but its not as pleasant as getting context passed directly to client application (in whatever form their bindings make this available).  In a very active log, it may be a pain to line up the specific action which triggered the disconnect to the log message (although the same can be said when you have pipelined multiple requests).

There also may be a security/privacy concern if all services dump these error messages into a common log.  PII any any other sensitive contextual information (such as a content URL) which could otherwise be safely transported back to the calling application must be scrubbed before it can be dumped into a log which anyone can read.

Right now, it is the only channel I have, so its what I will use.  I still think that something more directed would be preferable to me.

**Comment by johngro** [comment]
fixed in 1439953003
