### ISSUE TITLE
5% dart ipc rtt regression at 5f2fca1406a1aed215a4badff5a7494a7c66df04

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#526]
The regression is visible on most of the graphs at https://chromeperf.appspot.com/report?sid=9abc20b46f6f8d908b0f07847f1d42eab54c7025a098336e6dc2d3e2030d66f8 .

One particular example could be dart-dart_ipc_round_trip_time__warm_start / 50th_percentile_ping: 

```
Alert information:
Median of segment before: 0.172
Median of segment after: 0.1805
Relative change: 4.9%
```

This seems to occur in 5f2fca1406a1aed215a4badff5a7494a7c66df04 . @johnmccutchan

**Comment by johnmccutchan** [comment]
@zanderso Has a CL out which switches the Map to HashMap which should help here.

**Comment by zanderso** [comment]
The HashMap helped a bit, but didn't recover everything. Performance has recovered a bit more from changes unrelated to the stuff in https://github.com/domokit/mojo/commit/5f2fca1406a1aed215a4badff5a7494a7c66df04. We do need to track the unclosed handles to avoid leaking them on an unhandled exception etc., and a Map is the right data structure to use. Given all that, I'm going to go ahead and close this one out.
