### ISSUE TITLE
8-18% dart IPC regression at e4ac236 - "Roll Dart runtime forward"

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#532]
Graphs:

https://chromeperf.appspot.com/report?sid=6e49b52a0fc9651c6a32b821cbb83513d7847476b1ab9bf8b71c8531a4890aeb&rev=5421

https://chromeperf.appspot.com/report?sid=fb1020f93a5ee1b1c2311050aa9c8af52d02656a8ceb2e0b7d1fed95ed3f75e2&rev=5421

https://chromeperf.appspot.com/report?sid=e5c970fc5c7ef4ed25c84fb7f2f4b4093a0fcfc0df219f99cb7f6168faa97127&rev=5421

commit: e4ac2367951e8857d06e923b74c455325ae8dcda

**Comment by zanderso** [comment]
This regression was addressed by a subsequent Dart runtime roll, and by rewriting the handle watcher in C++.
