### ISSUE TITLE
Modroid buffers input events

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#538]
MojoShell.apk buffers input events before delivering them to applications, adding latency.  To reduce latency, SkyShell calls requestUnbufferedDispatch to ask the Android framework not to buffer input events.

**Comment by abarth** [comment]
Thanks!

**Comment by j9brown** [comment]
Another thing to look into will be using the NDK API to dispatch input
events.  That will allow for asynchronous handling of events, which is
important for ensuring that the platform's default event handling behavior
can be invoked.

**Comment by qsr** [comment]
I agree that we should move to use async handling, but I have no plan to do any big refactoring of inputs until Mozart has inputs, as the input handling will change a lot for this.
