### ISSUE TITLE
Android MotionEvent#getEventTime unit confusion

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#541]
SkyShell and MojoShell appear to disagree about the units of MotionEvent#getEventTime.  MojoShell thinks getEventTime returns a number of milliseconds where as SkyShell thinks it returns a number of microseconds.  We need to figure out which is right and make them agree.

For now, I'm working around this issue in PlatformViewMojo::OnEvent by dividing the time stamp I get from the NativeViewportInputDispatcher by 1000.

**Comment by jamesr** [comment]
MotionEvent.getEventTime() says:

final long	getEventTime()
Retrieve the time this event occurred, in the uptimeMillis() time base.

so I'd expect that timestamp to be milliseconds.  PlatformViewportAndroid::TouchEvent() appears to be doing a millisecond->microsecond conversion correctly:

 event->time_stamp =
      (base::TimeTicks() + base::TimeDelta::FromMilliseconds(time_ms))
          .ToInternalValue();

https://github.com/domokit/mojo/blob/master/services/native_viewport/platform_viewport_android.cc#L137

so I suspect SkyShell is wrong here:

https://github.com/flutter/engine/blob/b0d8e5c565ba2de55952d1adb645d932cbc612a2/sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java#L189

**Comment by abarth** [comment]
Yes, that seems likely.  /me will verify with a stopwatch.

**Comment by abarth** [comment]
Yep, looks like the SkyShell version is off by 1000x.
