### ISSUE TITLE
Remove MojoCoreNatives from package:mojo

### ISSUE THREAD

**Issue by johnmccutchan** [domokit/mojo#545]
package:mojo has the following native:

class MojoCoreNatives {
  static int getTimeTicksNow() native "Mojo_GetTimeTicksNow";
}

This is used only for the tracing_helper.dart script which should be deprecated in favour of dart:developer's Timeline class.

This is also redundant with dart's own Stopwatch and DateTime classes which provide access to the clocks.

**Comment by jamesr** [comment]
Do the dart StopWatch and DateTime classes refer to the same clock?

**Comment by jamesr** [comment]
Looks like Dart's StopWatch calls gettimeofday() which is definitely not the same as MojoGetTimeTicksNow and not appropriate for measuring intervals of time.

**Comment by zanderso** [comment]
It seems like we might want to add a feature to the VM to use a timing function provided as a callback by the embedder.

**Comment by johnmccutchan** [comment]
@jamesr You want to make sure you have access to a high frequency monotonic clock? Dart's Stopwatch is designed to be used to measure intervals of time. I don't think it uses the monotonic clock today but we should fix that.

**Comment by zanderso** [comment]
https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/builtin.dart#L40

MojoCoreNatives.getTimeTicksNow() is now wired up to be used as the clock for Dart's Stopwatch and Timer classes.
