### ISSUE TITLE
Create Android APK to run a specific Mojo application

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#550]
I have been building an application that uses both Mojo and Flutter, and it is almost demo ready. Unfortunately, one showstopper for my demo is that I cannot launch my application away from my development workstation.

What I want is the ability to launch my app directly from the phone. While this may impose some limitations, I am willing to work around those issues.

I'll describe what I think the current situation is and propose something that could be done to achieve this goal.

Currently, in order to launch a specific Mojo application, we use the `mojo_run` script. For Android Shell, the relevant file is [mojo/devtools/common/devtoolslib/android_shell.py](https://github.com/domokit/mojo/blob/74043582f211fa2e9e40607927b3e73671dba2c0/mojo/devtools/common/devtoolslib/android_shell.py)

In this file, it looks like we do 3 major things to the Android device:
* Install the APK if it isn't there (277)
* Collect shell arguments and put them into a temporary file on the device's sdcard (328-330)
* We send an intent to the Mojo Shell application (336, with the `cmd` being built at 302 and 334). Specifically on 334, it adds an argument called `argsFile` which points to the file we pushed to the sdcard.

How difficult would it be to create an APK that performs the function of the last bullet point? (Do you foresee any problems with this approach? Can you think of better alternatives?)

The Android app only needs to send an intent to Mojo Shell to start the app a certain way. I'm still happy to use `mojo_run` to load the MojoShell and AppLauncher APKs onto the phone.

One issue with the `argsFile` is that the ones generated will often have ports referring to local devservers. (By "devservers", I mean the url-mappings and map-origins that tell you where to find `*.mojo` files on the workstation.) This is something I am willing to work around to make my AppLauncher function. If I need to publicly host my `*.mojo` binaries, I will do that.

Bonus Points:
* It would be great if we can choose the app name.
* It would be even better if we can choose an icon.
* The APK can store the configuration file in its own storage instead of as a tempfile on the sdcard.
* If we can optionally pass in our own `argsFile`, it will greatly speed up the rate at which we can work around the "no local devservers" problem.

While the notion of an `intent-only` app doesn't have to be specific to Mojo, I think it would be very helpful if Mojo included it anyway. It would help us greatly since we can re-launch and demo applications without being tied down to our machines.

Thanks for reading, and let me know what you think!

@qsr @ppiet @apwilson 

Also tagging @abarth. AFAIK, the process for launching Flutter apps is similar, so a similar strategy could be used to create Flutter APKs.

**Comment by qsr** [comment]
So, how important is it for you that this is an APK? Would a shortcut works?

When https://codereview.chromium.org/1454123003/ lands, you will be able to create a shortcut on your device with the name, URL and icon you want.

You can then deploy your application any https site you want: https://www.example.com/foo.mojo

You can then create a shortcut to mojo://www.example.com/foo.mojo that way:

./mojo/devtools/common/mojo_run --android 'mojo:shortcut MyAppName mojo://www.example.com/foo.mojo URL_TO_ICON'

This will create an icon on your android phone that will launch your mojo application.

Is that acceptable?

**Comment by afandria** [comment]
Yes, I think a Shortcut is just as good as an APK. It just needs to look like it is an app on the Home Screen. Thanks for adding `mojo:shortcut`. That takes us most of the way there.

One more thing that we need is the ability to add the `argsFile`. We use these arguments:
* `--enable-multiprocess` is required for our app to work
* `--argsFor` would be helpful since we are having issues with sending args over the mojo url
