### ISSUE TITLE
Using responseFactory with return value named "result"

### ISSUE THREAD

**Issue by nellyv** [domokit/mojo#551]
When in a mojo interface the return value of a method is named "result", e.g.
`Get(array<string> key_prefixes) => (Result result);` 
the corresponding factory method looks like that (which is obviously an error):

```
  SyncedStoreGetResponseParams _SyncedStoreGetResponseParamsFactory(Result result) {
    var result = new SyncedStoreGetResponseParams();
    result.result = result;
    return result;
  }
```
 
So, when using the `responseFactory` method to return the result you get an error:
`NoSuchMethodError: incorrect number of arguments passed to method named 'encode'`.

**Comment by johnmccutchan** [comment]
@zanderso
