### ISSUE TITLE
Allow running Mojo Dart applications without a handle watcher isolate

### ISSUE THREAD

**Issue by johnmccutchan** [domokit/mojo#553]
From: https://codereview.chromium.org/1463673002/

I'm sure this isn't the right place for a feature request, but in Flutter we run
Dart on a thread that already has a MessagePumpMojo.  Would it be possible to
use the underlying MessagePumpMojo to wait on Mojo handles from Dart instead of
bouncing to the handle watcher isolate in Flutter?

**Comment by johnmccutchan** [comment]
@abarth

**Comment by abarth** [comment]
Thx

**Comment by johnmccutchan** [comment]
Started here: https://codereview.chromium.org/1544373003/

**Comment by abarth** [comment]
Thanks!

**Comment by johnmccutchan** [comment]
Related: https://github.com/domokit/mojo/issues/604

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1554173002/

**Comment by johnmccutchan** [comment]
Support for running on top of base::MessageLoop instead of on Dart's thread pool has landed. This frees up the thread that we were pinning to call Dart_RunLoop on.

**Comment by johnmccutchan** [comment]
There is a 33% message passing performance hit (@zra has details) when using MessagePumpMojo's handle watcher (see #604) over the Dart content handler's handle watcher.

**Comment by johnmccutchan** [comment]
The performance hit has killed this.

**Comment by j9brown** [comment]
Sad this is dead.  Why not throw out the handle watcher instead and wrap
around MojoWaitMany or equivalent instead?
