### ISSUE TITLE
TraceRecorderImpl sometimes doesn't receive the data sent to it

### ISSUE THREAD

**Issue by johnmccutchan** [domokit/mojo#555]
My send routine:

  bool got_trace = Dart_GlobalTimelineGetTrace(AppendStreamConsumer, &data);
  if (got_trace) {
    printf("Sending %zu bytes to recorder\n", data.size());
    recorder_->Record(reinterpret_cast<char*>(data.data()));
  }
  recorder_.reset();

My debug printf version of TraceRecorderImpl::Record:

void TraceRecorderImpl::Record(const mojo::String& json) {
  printf("Received %zu bytes at recorder\n", json.size());
  sink_->AddChunk(json.To<std::string>());
}

----

When I get lucky and the data arrives:

Received 11304 bytes at recorder
Received 23921 bytes at recorder
Dart tracing got 2988355 bytes of trace data.
Sending 2988355 bytes to recorder
Received 2988354 bytes at recorder
[INFO:tracer.cc(114)] Wrote trace data to rtt.trace

When I get unlucky and the data doesn't arrive:

Received 11297 bytes at recorder
Received 23691 bytes at recorder
Dart tracing got 5584056 bytes of trace data.
Sending 5584056 bytes to recorder
[INFO:tracer.cc(114)] Wrote trace data to rtt.trace

**Comment by johnmccutchan** [comment]
@zanderso

**Comment by johnmccutchan** [comment]
@jamesr @ppiet (git blame services/tracing/trace_recorder_impl.cc winners) FYI

**Comment by zanderso** [comment]
Repro command line:

out/Release/mojo_shell --args-for="mojo:dart_content_handler --complete-timeline" mojo:dart_rtt_benchmark --trace-startup --trace-startup-duration=2 --trace-startup-output-name=rtt.trace

rtt.trace should have lots of data in it.

**Comment by zanderso** [comment]
I split up the data sent by the DartTraceProvider into chunks. This seems to result in all the data making it to the other side. I also needed to relax the timeout in the tracing app:

https://codereview.chromium.org/1467863002

**Comment by ppiet** [comment]
Thanks! I wonder what is the root cause of the issue - when I reproduce the bug on master, I can see that tracing app terminates not because of hitting the timeout, but because all pipes to recorders were closed. \me looks further

**Comment by ppiet** [comment]
Ah, it turns out we are hitting the message size limit from `mojo/edk/system/configuration.cc`:

```
4 * 1024 * 1024,      // max_message_num_bytes
```

The proxy drops the .Record() calls with more than 4MB of payload on the floor.

@qsr @viettrungluu-cr

**Comment by zanderso** [comment]
Yah, 10 second traces used for benchmarking with events e.g. every 50us are going to result in traces that are up to 50MB or so.
