### ISSUE TITLE
Need to start activity with an intent in Mojo shell on Android

### ISSUE THREAD

**Issue by mishadynin** [domokit/mojo#557]
For the slides demo, we need to open a video player for display of an animated slide content.  Which would involve executing the following code:
```
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setDataAndType(Uri.parse(VIDEO_URL), "video/*");
startActivity(intent); 
```
Can this functionality be added to the Mojo shell?

Tracking issue on the sync slides side: https://github.com/vanadium/syncslides/issues/4

@qsr, @aghassemi told me you are the person to ask.

**Comment by aghassemi** [comment]
@qsr Do you have the powers to publish a new `mojo_services` [pub package](https://pub.dartlang.org/packages/mojo_services) that includes these changes?

**Comment by mishadynin** [comment]
Cc:ing @abarth since he is listed on https://pub.dartlang.org/packages/mojo_services
(it looks like the last version, 0.4.7, was published on November 20th.)

**Comment by abarth** [comment]
I'd recommend getting someone who works in mojo.git to publish new versions.  Last time I did it, I screwed it up.  /cc @jamesr @zanderso

**Comment by mishadynin** [comment]
Thanks for publishing updated mojo_services.  Now would it be possible to publish mojo_sdk package with the updated dependencies?

**Comment by zanderso** [comment]
Yes. A couple of issues came up. Working through those and then I'll push shortly after this change lands: https://codereview.chromium.org/1489193003/.

**Comment by zanderso** [comment]
The mojo_sdk package has been updated.
