### ISSUE TITLE
Validation error messages are opaque

### ISSUE THREAD

**Issue by kulakowski** [domokit/mojo#573]
For example, in [RequestValidator](https://github.com/domokit/mojo/blob/3db36ca1b7ad0c8f0338235352e1bd38da31c50f/mojo/public/tools/bindings/generators/cpp_templates/interface_definition.tmpl#L293) all information about the message is dropped on the floor.

**Comment by kulakowski** [comment]
cc @shinykitten

**Comment by viettrungluu-cr** [comment]
This is a dup of #520.
