### ISSUE TITLE
Multiple shells on same machine + url response disk cache lock

### ISSUE THREAD

**Issue by bprosnitz** [domokit/mojo#579]
When I try to run to mojo shells on the same machine (with different port, etc), it seems that the url response disk cache on the filesystem is shared between them, but not unlocked until the initial locking shell is shut down.

`[FATAL:url_response_disk_cache_db.cc(149)] Check failed: status.ok(). IO error: lock /home/bprosnitz/.mojo_url_response_disk_cache/db/LOCK: Resource temporarily unavailable`

That is, I start up shell 1 and load everything it will ever use and let it stay open. It shouldn't need the disk cache, but it keeps the lock so the second shell can't access the cache.

If I start up shell 1, dangerously delete the lock and start up shell 2 they are both able to coexist with seemingly no problem (at least in the case where the cache is being accessed only in the beginning of the process).

Is it possible to make this locking more fine-grained?

**Comment by qsr** [comment]
The lock is due to leveldb, and leveldb is not multiprocess safe.

If you want to run mutliple shell, set a different HOME environment variable for each so that they each use their own storage.

**Comment by ppiet** [comment]
PTAL also at https://github.com/domokit/mojo/blob/master/mojo/devtools/common/docs/mojo_run.md#running-multiple-instances-simultaneously .
