### ISSUE TITLE
Mojom C++ bindings: if no ServiceName, Name_ is declared (in header)

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#588]
But we don't define it, which is correct. We shouldn't declare it either, so that people get a compile error instead of a link error.

(Or so I'm told. I think @vardhan-cr told me this. I haven't actually double-checked.)

/cc @AlexandreZani

**Comment by freiling** [comment]
Right now its gets declared as Name_ = [], which produces a linker error
