### ISSUE TITLE
mojom.dart files expose many extra public symbols

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#589]
If you look at the dartdoc documentation for a mojom.dart file, you'll see that we're exposing a bunch of symbols unnecessarily:

https://www.dartdocs.org/documentation/sky_services/0.0.70/activity_mojom/activity_mojom-library.html

For example:

- [ ] `kActivity_finishCurrentActivity_name` and all the other ordinals should be private.
- [ ] `ActivityName` should be private.
- [ ] Should `ActivityProxyImpl` be private?
- [ ] `ActivityStartActivityParams` and the other generated params structs shoudl be private.

/cc @zanderso

**Comment by zanderso** [comment]
Interface calls return instances of the ResponseParams classes. It's possible to make them library private, but this may limit help available from the analyzer. See the change needed here:

https://codereview.chromium.org/1525183003/diff/1/examples/dart/netcat/lib/main.dart

The other changes have no issues, as far as I can see.

**Comment by abarth** [comment]
> Interface calls return instances of the ResponseParams classes

Yeah, sorry.  I just mean that the "RequestParams" should be library-private.  For example, `ActivityStartActivityParams` is the parameters we're sending into the pipe rather than the response we get back from the pipe.
