### ISSUE TITLE
mojom.dart generates low quality declarations for enums

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#590]
Looking at this example enum https://www.dartdocs.org/documentation/sky_services/0.0.70/activity_mojom/AuralFeedbackType-class.html

- [ ] The enum constants should be lowercase to match modern Dart style.
- [ ] The enum constants should be typed (instead of dynamic).

/cc @zanderso

**Comment by zanderso** [comment]
The style guide recommends lowerCamelCase for enum fields. This would mean, e.g., that for the Mojo enum:

```
enum Enum {
  DEFAULT,
};
```

We would generate:

```dart
class Enum {
  static const Enum default = const Enum._(0);
}
```

Which doesn't work because `default` is a reserved word and can't be an identifier.

Alternately, we could generate one of:

```dart
Default,
kDefault,
defaultEnum,
enumDefault,
```

For the sake of brevity, out of those choices I'd go with `Default`. WDYT?

**Comment by viettrungluu-cr** [comment]
On Fri, Dec 11, 2015 at 7:55 AM, Zachary Anderson <notifications@github.com>
wrote:

> The style guide recommends lowerCamelCase for enum fields. This would
> mean, e.g., that for the Mojo enum:
>
> enum Enum {
>   DEFAULT,
> };
>
> We would generate:
>
> class Enum {
>   static const Enum default = const Enum._(0);
> }
>
> Which doesn't work because default is a reserved word and can't be an
> identifier.
>
> Alternately, we could generate one of:
>
> Default,
> kDefault,
> defaultEnum,
> enumDefault,
>
> For the sake of brevity, out of those choices I'd go with Default. WDYT?
>
Note that this is a general problem -- each generator should (in theory) be
able to map valid names in mojom to valid names in its target language. (In
practice, we don't do this yet. I guess I should file a bug for that.)

**Comment by abarth** [comment]
> WDYT?

Yeah, we'll need some sort of name mangling to avoid reserved words.  Another option is `default_`.  You probably should just pick one.  None of them are going to be particularly pretty.

**Comment by abarth** [comment]
https://codereview.chromium.org/1517093002/  <--- Looks like there was a change recently to uses of the term `default`.

**Comment by MitchRudominer** [comment]
This was just a change to the not-yet-deployed new parser to make its behavior consistent with the already-deployed code-generators. So no change in behavior.
