### ISSUE TITLE
Should have a mojom file formatter

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#592]
clang-format can format C++ (and Java, I think).
gofmt formats Go.
gn format formats gn files.
There's something for Dart too, I think (though we may not use it).

... so we should have something similar for mojom files.

/cc @MitchRudominer @AlexandreZani

**Comment by MitchRudominer** [comment]
sgtm. We will put this on our TODO list.

**Comment by zanderso** [comment]
FYI: dartfmt runs over Dart code in a CL on a 'git cl format' command.

**Comment by AlexandreZani** [comment]
I'm starting a design for it. https://docs.google.com/a/chromium.org/document/d/1UX9r4PTW_dpRrRGEQwy5AiQE-tkjACK1bVuh-S8rHZE/edit?usp=sharing

**Comment by tonygentilcore** [comment]
FWIW, last I checked `git cl format` and `gn format` we're wired together.

**Comment by j9brown** [comment]
I think gn format happens manually and is only checked as part of a
presubmit.  I know I do git cl format then get whacked over the head a
moment later when I do git cl upload...
