### ISSUE TITLE
New Mojom Compiler: Finish and deploy

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#593]
This is a tracking bug for the odds and ends left to finish and deploy the new version of the compiler. (I thought there was already such a tracking bug but I cannot find it.)

/cc @AlexandreZani

**Comment by viettrungluu-cr** [comment]
AFAIK, this is deployed, and so we should consider it as "finished" insofar as software is ever finished. So I'm going to close this.

@MitchRudominer Please feel free to reopen this if you disagree.
