### ISSUE TITLE
Mojom: API of generated code is dependent on mojom file names

### ISSUE THREAD

**Issue by AlexandreZani** [domokit/mojo#597]
Right now, if I change the name of a mojom file, all the code that depends on it will break. (C++ include statements will fail for instance) This seems like the wrong result since the module statement in mojom files already provides a namespace that generated file consumers could rely upon.

We should update the generators to generate APIs that are not affected by the name of a mojom file changing.

Possible approach: In C++ generate an include file per module which #includes all the other generated .h files for that module. Something similar should be doable with Python. Go is likely unaffected.

**Comment by AlexandreZani** [comment]
@MitchRudominer

**Comment by viettrungluu-cr** [comment]
This is a long-standing problem, but realistically "module" is a bad term; "namespace" is really closer to reality.

There are several problems with trying to use the module name:

1. There's too much stuff under each module name.
2. There's no complete enumeration of everything under each module name.
3. Indeed, there may be things that conflict within the same module name.

Without enforcing more rigidity in the "module" system, there's not much to be done. (We've encountered the same sort of thing for other languages, which why everyone uses the filename somehow in various "package" names -- e.g., in Java and Dart, I think.)

In general, breaking source code is OK -- changing a filename should be viewed as being similar to changing any other name (module name, interface name, struct name, etc.), any of which would also break other source code.

What wouldn't be OK is breaking binary compatibility (and changing any of the above doesn't break binary compatibility).

Without a more extensive/complete proposal (which would be difficult, given 2. above), I think this issue should be closed. (Note that any such proposal would be far-reaching and probably not obviously tractable.)
