### ISSUE TITLE
InkSplash clip looks wrong on Nexus 6

### ISSUE THREAD

**Issue by eseidel** [domokit/mojo#60]
InkSplash clip looks wrong on Nexus 6

Works on Nexus 5 and Nexus 10, I haven't tested others.

fetch mojo
cd mojo/src
./mojo/tools/mojob.py gn --android --release
./mojo/tools/mojob.py build --android --release
./sky/tools/shelldb start out/android_Release sky/examples/stocks/index.sky

Click on any one of the list items to make it splash.  Notice how the splash starts out smooth, but then jumps on the right-hand side.  Spashes are smooth for the whole duration on other devices.

**Comment by eseidel** [comment]
Here is a video:
https://drive.google.com/open?id=0B1C4tS7Ao1fIYlRyYWVMQnpqaE0&authuser=0

By default only Brian can access that.

**Comment by eseidel** [comment]
This is the code for the splash:
https://github.com/domokit/mojo/blob/master/sky/framework/sky-ink-splash.sky

**Comment by ppiet** [comment]
Should this be moved to sky_engine issue tracker, or is obsolete now?

**Comment by ppiet** [comment]
Assuming obsolete.
