### ISSUE TITLE
mojom_parser build is too noisy in successful case

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#606]
Successful builds should leave no output on the console.  Currently a successful build of mojom_parser produces the following output:

[501/894] ACTION //mojom/mojom_parser:mojom_parser(//build/toolchain/linux:clang_x64)
Building the Mojom parser for darwin amd64...
Success! Built /ssd/mojo/src/out/Release/obj/mojom/mojom_parser/mojom_parser_darwin_amd64
Building the Mojom parser for linux amd64...
Success! Built /ssd/mojo/src/out/Release/obj/mojom/mojom_parser/mojom_parser_linux_amd64
[894/894] STAMP obj/default.stamp

It should only print something if a step fails.

/cc @MitchRudominer @AlexandreZani

**Comment by MitchRudominer** [comment]
OK. I would like for those messages to be printed when we run the python script manually. But we can turn off the messages when invoked from Ninja.

**Comment by jamesr** [comment]
That sounds good.

**Comment by viettrungluu-cr** [comment]
Maybe you should just have a --verbose flag?

**Comment by AlexandreZani** [comment]
I'm working on a --quiet flag. I think this makes more sense since the output needs to be there when running the tool by hand and it's easy enough to have that specified in the build file.

**Comment by viettrungluu-cr** [comment]
Seems to me that the "Unix way" (for better or for worse) is to be quiet by
default and have --verbose as an option. <shrug>
