### ISSUE TITLE
Recursively cloning mojo now fails.

### ISSUE THREAD

**Issue by aghassemi** [domokit/mojo#608]
`git clone --recursive https://github.com/domokit/mojo.git`  is failing to resolve bunch of sub modules like `third_party/dart-pkg/archive`

error is `'No submodule mapping found in .gitmodules for path 'third_party/dart-pkg/archive`

Might be related to https://github.com/domokit/mojo/commit/958af74e7606aba3bba4400cf461660b93032bc3 since that commit adds bunch of `Subproject commit` at the end.

@dalesat @jamesr

**Comment by aghassemi** [comment]
@nlacasse

**Comment by jamesr** [comment]
Then don't do that? We shouldn't have any submodule refs but you also should not need --recursive. Mojo doesn't use submodules.

**Comment by afandria** [comment]
We'll try it without `--recursive`, but it is important to note that cloning with that flag worked until the recent CL https://github.com/domokit/mojo/commit/958af74e7606aba3bba4400cf461660b93032bc3 (where a few Subprojects are set up)

**Comment by jamesr** [comment]
Fixed in https://github.com/domokit/mojo/commit/1d12f9f7b7049691b84defab3e302ad3bd26288e
