### ISSUE TITLE
dartx doesn't know about local pubspec dependencies

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#612]
@ppiet wrote:
When you build a module into a dartx, it will not rebuild when its local dependency (for instance the logger in dart/common) changes - the build system doesn't have visibility into local pubspec deps and we don't have BUILD targets for dart libraries so there is nothing to depend on in the dartx spec.

@johnmccutchan wrote:
We could modify the snapshotter to output a list of all source files that were loaded when building the snapshot as a .d file and add a depfile to the dartx rule.

/cc @zanderso @alhaad

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1608043002/

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1607613007/
