### ISSUE TITLE
Fix "Missing case clause for 'unknown'" error for Dart

### ISSUE THREAD

**Issue by armansito** [domokit/mojo#613]
dartanalyzer outputs this error for generated mojom bindings, when there is a union type that gets used in a switch statement. The binding generator actually inserts the line:

    // TODO(azani):  Handle unknown union member.

above the generated snippet (see mojo/public/tools/bindings/generators/dart_templates/union_definition.tmpl, line 54), so maybe fix this now? :)

/cc @AlexandreZani @MitchRudominer

**Comment by MitchRudominer** [comment]
Alex do you want to fix this?

**Comment by AlexandreZani** [comment]
Sure. I'll take a look.

**Comment by AlexandreZani** [comment]
This was fixed early last month. A few days after you last regenerated the files you mentioned. I suggest you regenerate the files in question.

**Comment by AlexandreZani** [comment]
I'm going to close this Arman. Feel free to reopen if regenerating didn't work.
