### ISSUE TITLE
Cannot play audio when running Flutter in Mojo Shell

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#614]
Related: https://github.com/flutter/flutter/issues/1128

In order to play audio, Flutter connects to the service "media::MediaPlayer". Flutter's Shell provides "media::MediaPlayer", but Mojo Shell's does not.

Is there a way to put this service into Mojo or start Mojo Shell in a way such that this service is usable?

**Comment by afandria** [comment]
After some discussion with @abarth, it looks like audio support from Flutter in Mojo Shell is unlikely to be added/supported in the long term.

The good news (for me) is that I was able to locally fork Mojo such that Flutter's MediaService is replicated in Mojo Shell. I called this service `media_service.mojo`. To contact this binary, I only had to make a minor tweak to the `flutter_sprites` package:
* `shell.connectToService(null, _mediaService);` was replaced by `shell.connectToService("mojo:media_service", _mediaService);`.

After those two changes, I am now able to make audio play when running Flutter in Mojo Shell.

**Comment by abarth** [comment]
> To contact this binary, I only had to make a minor tweak to the flutter_sprites package:

We can land that patch to flutter_sprites if you like.  The `null` is just a placeholder for when the service doesn't have a URL yet.

**Comment by afandria** [comment]
Thanks for the offer!

Will Flutter's audio still work if shell.connecToService specifies a wrong/nonexistent service URL?

If there might be problems, It's okay to leave flutter_sprites, as-is. I don't want to mislead other users, since I don't plan on checking in my `mojo:media_service` hack to Mojo.

**Comment by abarth** [comment]
> Will Flutter's audio still work if shell.connecToService specifies a wrong/nonexistent service URL?

Yes, the URL is ignored in standalone Flutter.

**Comment by afandria** [comment]
Here's the proposed patch: https://github.com/flutter/flutter/pull/1193

**Comment by afandria** [comment]
If anyone is interested, the changes I made are [here](https://codereview.chromium.org/1644593004)

**Comment by afandria** [comment]
The changes are not going to be landed, so if you need them, apply the linked patch above.
