### ISSUE TITLE
Instability in new mojom generator

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#617]
I've been compiling the .mojom.dart files repeatedly with `./mojo/dart/tools/bindings/generate.py -f`, and one file in particular `mojo/dart/packages/_mojo_for_test_only/lib/dart_to_cpp/dart_to_cpp.mojom.dart` keeps changing. I'm not sure exactly why this is the case, but it may have something to do with how Go iterates through maps.

The behavior I've noticed is that the file tends to swap the order of its methods.

**Comment by afandria** [comment]
You can see some examples of these changes in the patchsets of this CL https://codereview.chromium.org/1575433005

**Comment by MitchRudominer** [comment]
This is a good point. I traced down one source of instability (there may be more) to the following:
The list of methods in an interface is represented in mojom_types.mojom as a map from uint32 (the method ordinal) to a MojomMethod. This gets deserialized into a Python dictionary and in mojom_translator.py this gets translated to a Python list as follows:
```
interface.methods = [self.MethodFromMojom(mojom_method, interface)
        for mojom_method in mojom_interface.methods.itervalues()]
```

Regarding iterating over a dictionary, the Python documentation says
```
CPython implementation detail: Keys and values are listed in an arbitrary order which is non-random, varies across Python implementations, and depends on the dictionary’s history of insertions and deletions.
```
So if the map is serialized in a different order from run to run then it may be deserialized in a different order from run to run and this would explain the instability. 

One solution is to translate to a Python list in method-ordinal order. Another is to translate to a Python list in textual order. The textual order is represented in mojom_types.mojom in the |declaration_order| field of |DeclarationData|. But currently that field is not being populated by the front end. So for the short term I propose that we use method-ordinal order and then file a bug to consider using declaration order in the future.

**Comment by MitchRudominer** [comment]
\cc @AlexandreZani

**Comment by MitchRudominer** [comment]
Working on https://codereview.chromium.org/1577493002/
This seems to solve the problem.
