### ISSUE TITLE
Make fusl build using gn

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#619]
For now, we just need a .a ("static_library").

**Comment by kulakowski** [comment]
After the patch, there are a few things to do:

- Rationalize the set of flags.
- Duplicate the logic around what to use -O3 on. musl on x86_64 at least wants to use it for src/internal, src/malloc, and src/string.
- Build crt
- Actually build and link against it
- Add -fno-stack-protector to a handful of files

**Comment by kulakowski** [comment]
Building other libraries is probably also part of this.

- libm
- librt
- libpthread
- libcrypt
- libutil
- libxnet
- libresolv
- libdl

**Comment by kulakowski** [comment]
Also, eventually, making .sos.

**Comment by viettrungluu-cr** [comment]
Eventually, though you wouldn't be able to use a fusl .so with the current
mojo_shell (which needs a native/linux libc, which it currently dynamically
links).

**Comment by petrhosek** [comment]
If we're planning to use static build for Mojo "user space", than we probably don't even need .so's.

**Comment by viettrungluu-cr** [comment]
Eventually we'll want dynamic linking for Mojo apps, but that requires a
lot of other work (e.g., having our own loader).

**Comment by kulakowski** [comment]
This is done. Anything else mentioned in this issue is vague and depends on how we load stuff.
