### ISSUE TITLE
custom-elements/registration.sky is flaky on the release bot

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#62]
There are lots of failures i.e. http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux/builds/2011/steps/Sky%20tests/logs/stdio:

Regressions: Unexpected text-only failures (1)
  custom-elements/registration.sky [ Failure ]

http://test-results.appspot.com/dashboards/flakiness_dashboard.html#testType=Sky%20tests&tests=custom-elements%2Fregistration.sky

**Comment by jamesr** [comment]
@abarth @eseidel @esprehn 

(trying out the github @ syntax)

**Comment by abarth** [comment]
This test is gone.
