### ISSUE TITLE
Build failures on OS X

### ISSUE THREAD

**Issue by willbittner** [domokit/mojo#626]
../../third_party/boringssl/src/crypto/cipher/e_aes.c:704:11: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]

          !CRYPTO_gcm128_finish(&gctx->gcm, ctx->buf, gctx->taglen) != 0) {

          ^                                                         ~~

../../third_party/boringssl/src/crypto/cipher/e_aes.c:704:11: note: add parentheses after the '!' to evaluate the comparison first

          !CRYPTO_gcm128_finish(&gctx->gcm, ctx->buf, gctx->taglen) != 0) {

          ^

           (                                                            )

../../third_party/boringssl/src/crypto/cipher/e_aes.c:704:11: note: add parentheses around left hand side expression to silence this warning

          !CRYPTO_gcm128_finish(&gctx->gcm, ctx->buf, gctx->taglen) != 0) {

          ^

          (                                                        )

1 error generated.

[990/5953] ACTION //examples/echo:bindings__generator(//build/toolchain/mac:clang_x64)

ninja: build stopped: subcommand failed.

There is more - I will fix and create pull request.

**Comment by viettrungluu-cr** [comment]
We don't support building on Mac for a Mac target, at all.
