### ISSUE TITLE
shell_apptests crashes flakily after passing

### ISSUE THREAD

**Issue by michaelwasserman** [domokit/mojo#63]
shell_apptests crashes flakily on Mojo Linux (dbg) and Mojo Linux NaCl (dbg):
http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux%20(dbg)
http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux%20NaCl%20(dbg)

Heads up: @qsr, @jamesr 

Here's an example:
http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux%20%28dbg%29/builds/2272/steps/App%20tests/logs/stdio

Running mojo:shell_apptests... Failed command: "/b/build/slave/mojo/build/src/out/Debug/mojo_shell '--args-for=mojo:shell_apptests --gtest_filter=ShellHTTPAppTest.QueryHandling' 'mojo:shell_apptests'"
------------------------------------------------------------------------
  with exit code -11
------------------------------------------------------------------------
Note: Google Test filter = ShellHTTPAppTest.QueryHandling
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ShellHTTPAppTest
[ RUN      ] ShellHTTPAppTest.QueryHandling
[INFO:network_fetcher.cc(70)] Caching mojo app http://127.0.0.1:41393/app?foo at /tmp/01ea9e233c5f3aacf77e685d0c0f0e21c88012ae508d24c20be4881541e357f6.mojo
[       OK ] ShellHTTPAppTest.QueryHandling (78 ms)
[----------] 1 test from ShellHTTPAppTest (78 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (78 ms total)
[  PASSED  ] 1 test.
[0311/113645:FATAL:connection.cc(169)] Check failed: result == MOJO_RESULT_OK (-10 vs. 0)
#0 0x7ff1d42644ae base::debug::StackTrace::StackTrace()
#1 0x7ff1d42c51b5 logging::LogMessage::~LogMessage()
#2 0x7ff1d42127d6 http_server::Connection::OnSenderReady()
#3 0x7ff1d4215269 base::internal::RunnableAdapter<>::Run()
#4 0x7ff1d4215184 _ZN4base8internal12InvokeHelperILb0EvNS0_15RunnableAdapterIMN11http_server10ConnectionEFviEEENS0_8TypeListIJPS4_RKiEEEE8MakeItSoES7_S9_SB_
#5 0x7ff1d4215130 _ZN4base8internal7InvokerI13IndexSequenceIJLm0EEENS0_9BindStateINS0_15RunnableAdapterIMN11http_server10ConnectionEFviEEEFvPS7_iENS0_8TypeListIJNS0_17UnretainedWrapperIS7_EEEEEEENSD_IJNS0_12UnwrapTraitsISF_EEEEENS0_12InvokeHelperILb0EvSA_NSD_IJSB_RKiEEEEEFvSN_EE3RunEPNS0_13BindStateBaseESN_
#6 0x7ff1d4215616 base::Callback<>::Run()
#7 0x7ff1d4215596 mojo::Callback<>::RunnableAdapter<>::Run()
#8 0x7ff1d47f1285 mojo::Callback<>::Run()
#9 0x7ff1d47f11fa mojo::AsyncWaiter::WaitCompleteInternal()
#10 0x7ff1d47f116b mojo::AsyncWaiter::WaitComplete()
#11 0x7ff1d47f161e mojo::(anonymous namespace)::RunLoopHandlerImpl::NotifyCallback()
#12 0x7ff1d47f151f mojo::(anonymous namespace)::RunLoopHandlerImpl::OnHandleError()
#13 0x7ff1d448c358 mojo::RunLoop::NotifyHandlers()
#14 0x7ff1d448c0bd mojo::RunLoop::~RunLoop()
#15 0x7ff1d447f1eb mojo::ApplicationRunner::Run()
#16 0x7ff1d421f512 MojoMain
#17 0x00000065db1e mojo::shell::LoadAndRunNativeApplication()
#18 0x00000065f15d mojo::shell::InProcessNativeRunner::Run()
#19 0x00000065f1ec mojo::shell::InProcessNativeRunner::Run()
#20 0x00000059c462 base::DelegateSimpleThread::Run()
#21 0x00000059c233 base::SimpleThread::ThreadMain()
#22 0x00000058ec2c base::(anonymous namespace)::ThreadFunc()
#23 0x7ff1dd4c2e9a start_thread
#24 0x7ff1dd1f02ed clone

------------------------------------------------------------------------
Failed test:
Failed command: "/b/build/slave/mojo/build/src/out/Debug/mojo_shell '--args-for=mojo:shell_apptests --gtest_filter=ShellHTTPAppTest.QueryHandling' 'mojo:shell_apptests'"
------------------------------------------------------------------------
None
------------------------------------------------------------------------
Failed test(s) in {'test': 'mojo:shell_apptests'}

**Comment by michaelwasserman** [comment]
Running locally with gdb, I get:

Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fffe5a16700 (LWP 21275)]
0x00007ffff6f9f35d in write () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff6f9f35d in write () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fffe4fe06f0 in net::SocketLibevent::Write(net::IOBuffer*, int, base::Callback<void (int)> const&) ()
   from /work/mojo/src/out/Debug/network_service.mojo
#2  0x00007fffe4feec7d in net::TCPSocketLibevent::Write(net::IOBuffer*, int, base::Callback<void (int)> const&) ()
   from /work/mojo/src/out/Debug/network_service.mojo
#3  0x00007fffe4d11714 in mojo::TCPConnectedSocketImpl::SendMore() () from /work/mojo/src/out/Debug/network_service.mojo
#4  0x00007fffe4d2319e in base::debug::TaskAnnotator::RunTask(char const*, char const*, base::PendingTask const&) ()
   from /work/mojo/src/out/Debug/network_service.mojo
#5  0x00007fffe4d32b92 in base::MessageLoop::RunTask(base::PendingTask const&) () from /work/mojo/src/out/Debug/network_service.mojo
#6  0x00007fffe4d32d29 in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) () from /work/mojo/src/out/Debug/network_service.mojo
#7  0x00007fffe4d330eb in base::MessageLoop::DoWork() () from /work/mojo/src/out/Debug/network_service.mojo
#8  0x00007fffe4d34779 in base::MessagePumpLibevent::Run(base::MessagePump::Delegate*) () from /work/mojo/src/out/Debug/network_service.mojo
#9  0x00007fffe4d3cd20 in base::RunLoop::Run() () from /work/mojo/src/out/Debug/network_service.mojo
#10 0x00007fffe4d3275a in base::MessageLoop::Run() () from /work/mojo/src/out/Debug/network_service.mojo
#11 0x00007fffe4d637a5 in mojo::ApplicationRunnerChromium::Run(unsigned int) () from /work/mojo/src/out/Debug/network_service.mojo
#12 0x00007fffe4d0da24 in MojoMain () from /work/mojo/src/out/Debug/network_service.mojo
#13 0x000000000064c55e in mojo::shell::LoadAndRunNativeApplication (app_path=..., cleanup_behavior=mojo::shell::NativeRunner::DontDeleteAppPath, 
    application_request=...) at ../../shell/dynamic_service_runner.cc:106
#14 0x000000000064db9d in mojo::shell::InProcessNativeRunner::Run (this=0xee8d10) at ../../shell/in_process_native_runner.cc:59
#15 0x000000000064dc2c in non-virtual thunk to mojo::shell::InProcessNativeRunner::Run() () at ../../shell/in_process_native_runner.cc:54
#16 0x000000000058d5d2 in base::DelegateSimpleThread::Run (this=0xee97e0) at ../../base/threading/simple_thread.cc:81
#17 0x000000000058d3a3 in base::SimpleThread::ThreadMain (this=0xee97e0) at ../../base/threading/simple_thread.cc:60
#18 0x000000000057ffdc in base::(anonymous namespace)::ThreadFunc (params=0x7fffffffb390) at ../../base/threading/platform_thread_posix.cc:80
#19 0x00007ffff6f98182 in start_thread (arg=0x7fffe5a16700) at pthread_create.c:312
#20 0x00007ffff6cc547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by ncbray** [comment]
FYI: https://codereview.chromium.org/1009003002/

**Comment by ppiet** [comment]
Apparently fixed in https://github.com/domokit/mojo/commit/990a4f98935368412f0b3ff87e4133858ab76972 .
