### ISSUE TITLE
Error when using Union type in Java

### ISSUE THREAD

**Issue by aghassemi** [domokit/mojo#630]
I have a union type in my mojom file, the generated Java code includes lines such as 
```
        mTag_ = None;
```

but compiler complains that it can not find `None` symbol. Is there something I am not importing?
```
/usr/local/google/home/aghassemi/git/v23/release/mojo/discovery/java/generated-src/io/v/mojo/discovery/Update.java:33: error: cannot find symbol
        mTag_ = None;

```

@qsr

**Comment by MitchRudominer** [comment]
/cc @AlexandreZani 

Can you please include a small .mojom file that reproduces the problem?

**Comment by MitchRudominer** [comment]
This is probably a bug in the new compiler. I am investigating.

**Comment by MitchRudominer** [comment]
Ali I am unable to reproduce this. Can you help?

**Comment by aghassemi** [comment]
I am actually using the old compiler and maybe that's the issue. 

Let me upgrade to the new compiler and retry this. (Might take a while to upgrade our mojo SDK and compiler to the latest so let's consider this a non-issue since it is not reproducible with the new compiler and I will re-open if I find otherwise after upgrading)
