### ISSUE TITLE
Dart: mojom.dart script should work when invoked by pub run.

### ISSUE THREAD

**Issue by zanderso** [domokit/mojo#632]
`//mojo/dart/packages/mojom/bin/mojom.dart` should work when invoked by `pub run` so that packages that depend on it don't have to chase symlinks to run it.

Currently, it fails apparently due to passing the wrong paths to the underlying python script.

/cc @alhaad

**Comment by zanderso** [comment]
@alhaad I've been able to run via pub run. My last change may have helped. Could you give it another try, and report any problems you run into? Thanks!

**Comment by alhaad** [comment]
With your latest change, pub run works for me too!
