### ISSUE TITLE
mojom package should not assume that package name is same as the directory name

### ISSUE THREAD

**Issue by alhaad** [domokit/mojo#637]
The current implementation of the mojom dart package for generating dart bindings works by finding dart package names by matching directory names. It should, instead, parse pubspec.yaml files to get package names

@zanderso

**Comment by zanderso** [comment]
Thinking back on when we were writing mojom.dart, I think we explicitly decided that it shouldn't work this way, but I'm struggling to remember what the reasons were. John, James, do you remember?

**Comment by johnmccutchan** [comment]
My memory is that we didn't want to support complex use cases until they were actually needed. I think the best practice is to have a package's directory name match the package name so I'm not sure why this is necessary.

**Comment by alhaad** [comment]
Is the best practice of having the same name of the directory as the name
of the package because this particular tool is implemented a certain way?
If so, then I feel that we should decouple these things and have the
pubspec.yaml be the only place which declares the name of the package.

In our case, it seems an un-necessarily big change just to be able to use
this tool. In particular, our public dart api is in a directory name
//public.
