### ISSUE TITLE
Error with native_client crtbeing.o missing during build.

### ISSUE THREAD

**Issue by dj2** [domokit/mojo#639]
I've done a fetch mojo, installed the build files, and setup GN. When I try to build with ninja I receive the following immediately:

```
Development/mojo/src % ninja -C out/Debug
ninja: Entering directory `out/Debug'
ninja: error: '../../native_client/toolchain/linux_x86/pnacl_translator/translator/x86-32-nonsfi/lib/crtbegin.o', needed by 'clang_x86/obj/services/nacl/nonsfi/__crtbegin_file_generator.inputdeps.stamp', missing and no known rule to make it
```

Looking at the source directory, I don't have a src/native_client/toolchain directory. Does something need to be done to pull in the toolchain? (I have toolchain_build and toolchain_revisions directories under src/native_client)

**Comment by jamesr** [comment]
I believe that's pulled down by build/download_nacl_toolchains.py which should be run as a gclient hook.  Did you run gclient sync successfully?

**Comment by dj2** [comment]
I ran gclient sync and it runs without error. 

```
________ running '/usr/bin/python src/build/download_nacl_toolchains.py --packages pnacl_newlib,pnacl_translator sync --extract' in '/Development/mojo'
```

**Comment by jamesr** [comment]
What platform are you running on?

**Comment by dj2** [comment]
Ubuntu, trying to build without android.

**Comment by jamesr** [comment]
Do you have any GYP_DEFINES set?  I think you should figure out why build/download_nacl_toolchains.py is not doing what you need, it's supposed to populate that directory.

**Comment by dj2** [comment]
Awesome, that was it. I assumed since I was using gn it wouldn't use the GYP_DEFINES. I had the following:

```
clang=1 proprietary_codecs=1 component=shared_library release_extra_cflags=-fno-omit-frame-pointer dcheck_always_on=1 use_goma=1 disable_nacl=1
```

I'm assuming that disable_nacl=1 was the cause.

**Comment by jamesr** [comment]
Yeah that was it.  We should probably erase that line from our copy of build/download_nacl_toolchains.py to avoid confusing.  @petrhosek @mseaborn
