### ISSUE TITLE
Sky ImageOnlyFailure when rolling Chrome into Mojo.

### ISSUE THREAD

**Issue by ncbray** [domokit/mojo#64]
Regressions: Unexpected image-only failures (2)
  framework/flights-app-pixels.sky [ ImageOnlyFailure ]
  lowlevel/layers.sky [ ImageOnlyFailure ]

eseidel said to go ahead with the roll and suppress.

https://codereview.chromium.org/1001833005/

**Comment by eseidel** [comment]
It surprises me that a Chromium roll would affect these.  @ojanvafai

**Comment by jamesr** [comment]
The roll includes an update to skia from a9baa652bb329b5a286e1638938f63433701efca to d1783aefcc0da86c5ff1d124c54704252d817621 which could change rendering, but I'm not sure how these tests are constructed.  It's also possible that it (or some other part of the roll) completely breaks these tests.  Are these like pixel tests or reference tests?

**Comment by ojanvafai** [comment]
These are technically reference tests, but the reference just contains an <img> that points to a png that's hosted on googlestorage. So, they're pixel tests in practice. Unfortunately, updating the expected result is a rather manual process at the moment: https://github.com/domokit/mojo/blob/master/sky/HACKING.md#adding-pixel-tests

**Comment by ppiet** [comment]
Closing as obsolete.
