### ISSUE TITLE
GPU/NativeViewport mojoms should not have a DartPackage annotation

### ISSUE THREAD

**Issue by freiling** [domokit/mojo#644]
A lot of GPU/GL related mojom files have the DartPackage annotation, for example:

https://github.com/domokit/mojo/blob/master/mojo/services/native_viewport/interfaces/native_viewport.mojom
https://github.com/domokit/mojo/blob/master/mojo/services/gpu/interfaces/gpu.mojom
https://github.com/domokit/mojo/blob/master/mojo/services/gpu/interfaces/command_buffer.mojom

@jamesr assures me that this is in error, and that these can all be removed. Opening this issue to track that change.

**Comment by jamesr** [comment]
There's nothing pure Dart code can usefully do with context/native viewport/etc, we should just delete these annotations and the generated code.

@johnmccutchan @zanderso - could one of you take a look at this?

**Comment by johnmccutchan** [comment]
It's completely fine to remove DartPackage annotations from mojom interfaces that we don't want/expect developers to call from Dart code.
