### ISSUE TITLE
Cannot access /system/fonts/Roboto-Medium.ttf

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#65]
font-family: sans-serif;
    font-weight: 500;

Gives synthetic bold on /system/fonts/Roboto-Regular.ttf instead of loading Roboto-Medium.ttf even though /system/etc/fonts.xml lists

        <font weight="500" style="normal">Roboto-Medium.ttf</font>

@eseidel

**Comment by eseidel** [comment]
I'm certain this applies to blink as well.  We're not passing the actual weight down to skia:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/platform/fonts/skia/FontCacheSkia.cpp&q=fontcacheskia&sq=package:chromium&l=212

**Comment by abarth** [comment]
I fixed this.
