### ISSUE TITLE
Issues with Dart binding applicationConnection.provideService

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#651]
The comments in `application_connection.dart` say that the callback you pass to `provideService` should return something. However, the reality is that the return value is ignored. Also, it's not clear in the comment that you have to do the work of creating the stub yourself.

This function should either create the stub for you, or the typedef should have a void return type.

**Comment by Hixie** [comment]
cc @zra

**Comment by zanderso** [comment]
https://codereview.chromium.org/1664943002/
