### ISSUE TITLE
MojoHandleNatives.addOpenHandle captures a stack even in release builds

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#652]
The stack capture should only happen in checked mode (i.e. wrapped in an assert), unless we really need to be capturing a stack even in release builds.

cc @zra, @abarth.

**Comment by zanderso** [comment]
@johnmccutchan

**Comment by zanderso** [comment]
Also, @Hixie, I am @zanderso on github. zra was taken =(

**Comment by Hixie** [comment]
Oh! Good no know. Now I feel bad for whoever I've been cc'ing on all these bugs. Sorry!

**Comment by johnmccutchan** [comment]
@Hixie I'm confused, reading the code:

```static void addOpenHandle(int handle, {String description}) {
    // We only remember a stack trace when in checked mode.
    var stack;
    try {
      // This will only throw when running in checked mode.
      assert(false);
    } catch (_, s) {
      stack = s;
    }
    var openHandle = new _OpenHandle(stack, description: description);
    _openHandles[handle] = openHandle;
  }```

When running in release mode the assertion will not fail and no stack trace will be collected. What flags are you passing to the VM?

**Comment by Hixie** [comment]
Never mind, I'm crazy.

**Comment by floitschG** [comment]
Fwiw this should probably be `StackTrace.current` to avoid the observatory/editor breaking for "stop at caught exceptions".

**Comment by johnmccutchan** [comment]
@floitschG How do we ensure that we only make the call in checked mode?

**Comment by Hixie** [comment]
```dart
assert(() {
  // ... code to only run in checked mode ...
  return true
});
```

**Comment by floitschG** [comment]
or
`assert((stack = Stacktrace.current) != null)`
