### ISSUE TITLE
C++ bindings:  Generate InterfacePtrInfo<> instead of InterfacePtr<>.

### ISSUE THREAD

**Issue by vardhan-cr** [domokit/mojo#662]
InterfacePtrInfo<> is more bare-bone and informational (contains just a MessagePipe handle and an interface version number), whereas InterfacePtr<> actually brings in a Proxy which runs ontop of a message loop-like thing, depends on an AsyncWaiter, etc.

So, when we generate (and use) bindings, we should operate on InterfacePtrInfo<> and consume it with InterfacePtr<> when we want to start using the interface asynchronously.

This also paves the way for a synchronous-version of the interface bindings.

We should also try to rename InterfacePtrInfo<>.  Let's call it InterfaceHandle<> for now, until someone comes up with something much better (discussed offline).

**Comment by viettrungluu-cr** [comment]
I think this is done (except that we also renamed InterfacePtrInfo to InterfaceHandle).

Please re-open if I'm missing something.
