### ISSUE TITLE
mojo_sdk Dart package has too many dependencies

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#664]
Here's the dependency tree package:mojo_sdk pulls into package:flutter:

```
|   '-- mojo_sdk 0.2.14
|       |-- mojo 0.4.14
|       |-- mojo_apptest 0.2.18
|       |   |-- mojo...
|       |   '-- test 0.12.10+2
|       |       |-- args...
|       |       |-- collection...
|       |       |-- crypto...
|       |       |-- matcher...
|       |       |-- path...
|       |       |-- yaml...
|       |       |-- analyzer 0.27.1+2
|       |       |   |-- args...
|       |       |   |-- glob...
|       |       |   |-- path...
|       |       |   |-- yaml...
|       |       |   |-- html 0.12.2+1
|       |       |   |   |-- source_span...
|       |       |   |   |-- csslib 0.12.2
|       |       |   |   |   |-- args...
|       |       |   |   |   |-- logging...
|       |       |   |   |   |-- path...
|       |       |   |   |   '-- source_span...
|       |       |   |   '-- utf 0.9.0+2
|       |       |   |-- package_config 0.1.3
|       |       |   |   |-- charcode...
|       |       |   |   '-- path...
|       |       |   |-- plugin 0.1.0
|       |       |   '-- watcher 0.9.7
|       |       |       '-- path...
|       |       |-- async 1.8.0
|       |       |-- barback 0.15.2+7
|       |       |   |-- collection...
|       |       |   |-- path...
|       |       |   |-- pool...
|       |       |   |-- source_span...
|       |       |   '-- stack_trace...
|       |       |-- glob 1.1.0
|       |       |   |-- collection...
|       |       |   |-- path...
|       |       |   '-- string_scanner...
|       |       |-- http_multi_server 2.0.0
|       |       |-- http_parser 2.1.0
|       |       |   |-- async...
|       |       |   |-- collection...
|       |       |   |-- crypto...
|       |       |   |-- source_span...
|       |       |   |-- stream_channel...
|       |       |   '-- string_scanner...
|       |       |-- pool 1.2.1
|       |       |   |-- async...
|       |       |   '-- stack_trace...
|       |       |-- pub_semver 1.2.3
|       |       |   '-- collection...
|       |       |-- shelf 0.6.5
|       |       |   |-- async...
|       |       |   |-- http_parser...
|       |       |   |-- path...
|       |       |   |-- stack_trace...
|       |       |   '-- stream_channel...
|       |       |-- shelf_static 0.2.3+3
|       |       |   |-- http_parser...
|       |       |   |-- path...
|       |       |   |-- shelf...
|       |       |   '-- mime 0.9.3
|       |       |-- shelf_web_socket 0.1.0
|       |       |   |-- http_parser...
|       |       |   '-- shelf...
|       |       |-- source_map_stack_trace 1.0.4
|       |       |   |-- source_maps...
|       |       |   '-- stack_trace...
|       |       |-- source_maps 0.10.1
|       |       |   |-- path...
|       |       |   '-- source_span...
|       |       |-- source_span 1.2.1
|       |       |   '-- path...
|       |       |-- stack_trace 1.6.1
|       |       |   '-- path...
|       |       |-- stream_channel 1.3.1
|       |       |   |-- async...
|       |       |   '-- stack_trace...
|       |       '-- string_scanner 0.1.4+1
|       |           |-- charcode...
|       |           '-- source_span...
|       |-- mojo_services 0.4.17
|       |   '-- mojo...
|       '-- mojom 0.2.18
|           |-- mojo...
|           |-- args 0.13.3+3
|           |-- crypto 0.9.1
|           |-- logging 0.11.2
|           |-- path 1.3.9
|           '-- yaml 2.1.8
|               |-- collection...
|               |-- source_span...
|               |-- string_scanner...
|               '-- charcode 1.1.0
```

Of these, we only actually need package:mojo and package:mojo_services, which means the dependency tree should like like the following:

```
|   '-- mojo_sdk 0.2.14
|       |-- mojo 0.4.14
|       |-- mojo_services 0.4.17
|       |   '-- mojo...
```

/cc @zanderso @jamesr

**Comment by Hixie** [comment]
probably should use a dev_dependencies entry

**Comment by abarth** [comment]
Yeah, ideally there'd separate packages for the production and development code so that you can have production dependencies on the production code and dev_dependencies on the development code.

**Comment by jamesr** [comment]
dev_dependencies doesn't really work for this exactly as if mojo_sdk listed mojo_apptest as a dev_dependency it would not be possibly to get any version of mojo_apptest through the mojo_sdk dependency, which is the point of having it there (to be strictly versioned).  I think we should definitely remove mojo_apptest from mojo_sdk's list of dependencies, but the trick then is how to make sure that users of mojo_sdk who also want to use mojo_apptest get compatible versions of the two.  I think it might work to have mojo_sdk have no dependency on mojo_apptest and have mojo_apptest declare a dependency on an exact version of mojo_sdk.  Then if a developer wants mojo_apptest and mojo_sdk they have to declare dependencies on exact, matching versions of the two.  If they declare mismatched dependencies then 'pub get' would just completely die, which is unfortunate as it produces absolutely no useful output at all, but at least it wouldn't silently break runtime.

We could also convert all of the users of mojo_apptest (there's only one internal one I'm aware of) away from using pub to manage these dependencies at all.

/cc @johnmccutchan @zanderso @tonygentilcore

**Comment by Hixie** [comment]
we could also have mojo_sdk and mojo_redist.

**Comment by johnmccutchan** [comment]
The new proposed structure:

leaf packages:
mojo
mojo_services

sdk package:
mojo_sdk (depends on exact version of mojo and mojo_services).

sdk peer packages:
mojo_apptest (depends on exact version of mojo_sdk).
mojom (depends on exact version of mojo_sdk).

Release flow:
- Release leaf packages
- Release sdk package
- Release sdk peer packages

**Comment by johnmccutchan** [comment]
clients will continue to depend on an exact version of mojo_sdk and can specify 'any' for the dependencies on mojom / mojo_apptest.

**Comment by abarth** [comment]
SGTM

**Comment by johnmccutchan** [comment]
Just released:

mojo: 0.4.15
mojo_services: 0.4.18

mojo_sdk: 0.2.15

mojo_apptest: 0.2.19
mojom: 0.2.19

mojo_sdk depends on mojo and mojo_services with exact version constraints.
mojom and mojo_apptest depend on mojo_sdk with an exact version constraint.

**Comment by johnmccutchan** [comment]
Release process wiki was also updated https://github.com/domokit/mojo/wiki/Release-process

**Comment by abarth** [comment]
Thanks!!
