### ISSUE TITLE
Lots of dart code is in //mojo/public unnecessarily

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#665]
We have a lot of dart code in the //mojo/public subdirectory including a huge set of third_party pub packages checked in here:

https://github.com/domokit/mojo/tree/master/mojo/public/dart/third_party

however none of this is actually usable by anyone wishing to target Mojo.  All of the code they need is in the repo in https://github.com/domokit/mojo/tree/master/mojo/dart/packages and distributed via pub in the mojo* packages.  We should remove the dart code in //mojo/public and update uses from inside the repository to point to a location in the normal //third_party/.. structure.

/cc @johnmccutchan @zanderso

**Comment by johnmccutchan** [comment]
We moved this there when the packages where under //mojo/public/dart. This is no longer the case and we can move this under //third_party again.
