### ISSUE TITLE
Modroid: Should invoke OnVsyncParametersUpdated passing in the Display refresh rate

### ISSUE THREAD

**Issue by j9brown** [domokit/mojo#667]
/cc @qsr , @emembrives 

Modroid's native viewport implementation currently isn't calling OnVsyncParametersUpdated on the ViewportParameterListener so Mozart doesn't know what the correct refresh rate is and doesn't draw anything on Android.

We should fix this to obtain the refresh rate from the Android Display object and use the Android Choreographer to provide the vsync timebase.  This method may need to be called again later if the Display's parameters changes which can be accomplished by registering a DisplayListener with the Android DisplayManager.

**Comment by j9brown** [comment]
So far I've tracked the rathole down to the level of ui/gl/gl_surface_android.cc which calls NativeViewGLSurfaceEGL::Initialize() passing no vsync provider.  The underlying code in gl_surface_egl.cc is then unable to provide any vsync information because Android doesn't support eglGetSyncValuesCHROMIUM.

What should be happening here is that gl_surface_android.cc passes a valid VSyncProvider to Initialize() which is wired up to the Android Choreographer and Display in some way.

As a short term hack, we could simply seed vsync with some arbitrary timebase and use Display.getRefreshRate() to estimate the frame interval.  That will be good enough to make Mozart work on Android and unblock Modular.

HOWEVER, Display.getRefreshRate() lies!  It may be completely wrong and certainly is inaccurate for any purpose beyond estimating roughly when the next frame will occur.  Timing estimates based exclusively on this value will inevitably drift over even short time intervals manifesting as frame drops and periodic jank (which may be quite severe on certain misconfigured devices).

Suffice to say, we'll need to do much better before we ship anything.

To get accurate timing information on Android, you will compare successive frame times from the Choreographer and periodically resynchronize the timebase as it drifts.  Also be sure to prime the pump again anytime the DisplayListener indicates a change in the display's state (Display.getState()) or its refresh rate (Display.getRefreshRate()) which can cause timing discontinuities.

**Comment by j9brown** [comment]
Debating adding a workaround to Mozart to detect this issue, yell about it, and make a wild guess.

**Comment by pylaligand** [comment]
The people who worked on Display#getRefreshRate in Android should be ashamed :wink:

**Comment by j9brown** [comment]
*no comment*

**Comment by armansito** [comment]
Any updates on this issue?

**Comment by qsr** [comment]
CL is in progress: https://codereview.chromium.org/1694323003/

**Comment by alhaad** [comment]
Thanks Ben, Jeff! :)
