### ISSUE TITLE
Dart: No error when calling method that doesn't exist

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#673]
I have observed that if you call a method that doesn't exist in Dart + Mojo that the client-side will not receive an error. Worse, if you use "await" on the call, it will just stall silently forever.

To clarify, the client-side mojom and implementation are correct, but the server-side connected to might not match the mojom for various reasons (e.g., wrong service or obsolete mojom).

**Comment by zanderso** [comment]
@afandria I think I don't follow you, exactly. Could you give reproduction instructions?

**Comment by krisgiesing** [comment]
A test case here would be very illustrative, agreed.

I do want to note that the canonical way that Mojo pipes register errors is by closing themselves.  If the client doesn't handle properly the notification that a pipe has (unexpectedly) closed, then the client won't understand that an error has occurred.  Whatever code is providing the Dart Future that is being awaited does need to fulfill that Future (with an error) in the case that the Mojo pipe closes.  It's entirely possible that we have framework code that's not doing this properly.

**Comment by afandria** [comment]
One way to reproduce this is to go to the dart_apptests and connect to the wrong service.

In `mojo/dart/apptests/dart_apptests/lib/src/echo_apptests.dart`, change any of the `new EchoServiceProxy.connectToService(application, "mojo:dart_echo");` lines to connect to a different application.

For example, try the ping pong mojo app instead:
`new EchoServiceProxy.connectToService(application, "mojo:dart_pingpong");`

"mojo:dart_pingpong" exists and can be resolved, but it does not implement echo. Thus, we expect an error in our test. However, when running the app tests, we observe that the `mojo:dart_apptests` test never ends.

To rebuild and run all the apptests:
```
taskset ff mojo/tools/mojob.py gn && taskset ff mojo/tools/mojob.py build
mojo/tools/apptest_runner.py mojo/tools/data/apptests out/Debug
```

**Comment by zanderso** [comment]
"Whatever code is providing the Dart Future that is being awaited does need to fulfill that Future (with an error) in the case that the Mojo pipe closes."

This isn't how the Dart bindings work. Errors on Proxies in Dart are routed to a future on the Proxy implementation, e.g. `echoServiceProxy.impl.errorFuture`. To detect errors, you can 1) Attach a `.then()` to that Future before doing anything with the proxy, 2) set `echoServiceProxy.impl.onError` to an error callback or 3) Call interface functions with, e.g.

`await echoServiceProxy.responseOrError(echoServiceProxy.ptr.echoString("foo"))`

which will throw an exception if there is an error on the pipe. Just doing:

`await echoServiceProxy.ptr.echoString("foo")`

will never complete if there is an error on the pipe.

See the discussion on this issue and CL for the rationale: https://github.com/domokit/mojo/issues/496 and https://codereview.chromium.org/1410373004

**Comment by krisgiesing** [comment]
Ah, apologies for the misunderstanding.

**Comment by afandria** [comment]
I see, so `responseOrError` is what you need in order to handle errors. It's possible that this needs to be made more visible or obvious. I don't think the dart client examples use this.

I also recommend updating the echo apptest to use the `responseOrError` pattern more to avoid inexplicable timeouts.

**Comment by qsr** [comment]
I have the impression that responseOnError should be the default case, and
you should be doing something special if you want to silently swallow
error. It is very weird to have error an await foo.bar() never returned
when there is an error.

**Comment by zanderso** [comment]
@abarth @johnmccutchan

**Comment by abarth** [comment]
This is working as-designed.  For example, this behavior matches the C++ behavior for mojom interfaces.  The idea behind this design is that communication across mojom is a point of loose coupling in the system and ought to be quite error-tolerant.  Error handling at this loose coupling point is certainly possible, but should be explicit rather than implicit.
