### ISSUE TITLE
dart_pkg.py depends on the old mojom parser

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#675]
* Hence it was broken by faf496d17f4d7244c6bad88b80cd59dcf084bbd9.
* It reaches into a private library and imports stuff that was never meant for consumption by anything outside mojo/tools/bindings.
* Something weird is going on. I've done clobber builds that succeeded (even after the old mojom parser was removed). But now they break (as they should). Not sure what's going on....
* I guess the immediate fix is to revert faf496d17f4d7244c6bad88b80cd59dcf084bbd9 (and also 0eda5f1a8c0880cc228242b0b8f613f99906799f), but the issues above need to be fixed.

/cc @johnmccutchan @zanderso @MitchRudominer

**Comment by MitchRudominer** [comment]
OK, sorry I missed this.

**Comment by MitchRudominer** [comment]
Is somebody else working on reverting faf496d or should I?

**Comment by johnmccutchan** [comment]
I'm working on a fix.

**Comment by MitchRudominer** [comment]
OK ping me if I can help.
