### ISSUE TITLE
Replacement for mojo:kiosk_wm?

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#676]
https://github.com/domokit/mojo still speaks of `mojo:kiosk_wm`. That should probably be updated because the kiosk appears to have been deleted 3 weeks ago by @j9brown 

Has the window manager been replaced by another mojo binary, and if so, what is it named? (I've saw commits related to Mozart and compositor services, but I wasn't able to answer my question on my own.)

FYI, I'm making a jiri profile that collects important Mojo services like `dart_content_handler.mojo` and `tracing.mojo`. Previously, this list included `kiosk_wm.mojo`, but since it's gone now, I'm wondering if I need to replace it with something else.

Thanks in advance!

**Comment by j9brown** [comment]
You probably want launcher.mojo, compositor.mojo, view_manager.mojo, input_associate.mojo, etc.

**Comment by afandria** [comment]
Thanks, I'll add those.
