### ISSUE TITLE
Java JAR libraries are not uploaded to mojo bucket

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#677]
In our Vanadium Mojo/Discovery repo (https://github.com/vanadium/mojo.discovery/blob/master/java/build.gradle), we are building a discovery service using Mojo + Android. Since this is a Java Mojo service, we depend on some mojo libraries.

We use the following files:
* `out/android_Debug/gen/mojo/public/java/application.jar`
* `out/android_Debug/gen/mojo/public/interfaces/application/application_java.jar`
* `out/android_Debug/gen/mojo/public/java/bindings.jar`
* `out/android_Debug/gen/mojo/public/java/system.jar`

Currently, we find these files with a local installation of Mojo, but in order to make development easier (and more consistent), it is preferable for us if we can download versioned versions of these files from cloud storage instead. This is already done for a variety of mojo services and shell builds, but unfortunately, these java libraries do not appear there. The binary upload script does not appear to upload these files.

Note: Most of these JARs are generated by https://github.com/domokit/mojo/blob/master/mojo/public/java/BUILD.gn

If it is not possible to upload these files from Cloud storage, is there an alternative to obtain them without needing to maintain a complete mojo checkout? Perhaps these files are available publicly from Maven or somewhere other place?

**Comment by qsr** [comment]
All of this code can be build from the mojo_sdk:
https://github.com/domokit/mojo_sdk

Can you use this to build those yourselves?

I can upload those files if you want, but you need to have those synced with your version of the mojo code generator, and the way we were envisioning distributing this code was through the sdk.

**Comment by afandria** [comment]
I'd be okay with building the sdk as long as it isn't too complicated. Our mojo profile does make a checkout of mojo_sdk at a specific revision. However, I've been having trouble building it from just a git checkout of that repo.

Running `gn` out of the box doesn't work:
```
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
```

From what I can tell, this error message actually wants me to have a `.gclient` file (not a git checkout).

I've done `gclient config https://github.com/domokit/mojo_sdk/`, but `gn` still complains:

```
gn.py: Could not find gn executable at: /usr/local/google/home/alexfandrianto/Documents/vanadium_root/profiles/mojo/mojo_sdk/temp/src/mojo/public/buildtools/linux64/gn
```

I'm not very experienced with `gclient` or `gn`. Do you know how to build the JAR files?

It may be faster in the short term for me (and subsequent authors) of our mojo profile to build these JARs in a normal mojo checkout and upload them to our own cloud storage.

**Comment by jamesr** [comment]
The mojo_sdk repo provides code but does not currently export a complete build. You can use the BUILD.gn files as part of a larger GN build if you have one but for building standalone non-C++ artifacts that's probably not the best path. How are you building other bits of Java code? We should probably provide build files that integrate with whatever Java devs expect these days.

**Comment by afandria** [comment]
As for the other bits of Java code, you can see it in our [mojo.discovery repo](https://github.com/vanadium/mojo.discovery/tree/master/java)

(Disclaimer: I didn't write the code here and am not a Java dev by any means.)

Our discovery code for Android uses a Java mojo server application built with gradle. The issue I've noticed is that we're depending on a checkout and build of the mojo repo in order to obtain these JAR files. See the references to `$MOJO_DIR` bottom of our [build.gradle](https://github.com/vanadium/mojo.discovery/blob/master/java/build.gradle#L52) file.

**Comment by jhahn21** [comment]
I'm curious what's the purpose of *.java files in mojo/public/java/* if we can't use them to build mojo app in Java?

IIRC, Shyam mentioned that he talked with @jamesr and we can upload jar files to the cloud storage with a simple script. James, is that right?

**Comment by jamesr** [comment]
> I'm curious what's the purpose of .java files in mojo/public/java/ if we can't use them to build mojo app in Java?

I don't follow you at all - that is the exact purpose of these files.

Uploading files to Google cloud storage is pretty simple, yes.

**Comment by jhahn21** [comment]
> I don't follow you at all - that is the exact purpose of these files.

Yes, that's what I was expecting and so I was asking why we need those jar files.
Now I'm trying to use mojo/public/java/* instead of jar files.

**Comment by jamesr** [comment]
You certainly can use those files.  My point in the earlier comment was that we do not provide any build system rules usable in general for those java files, so you may find it difficult to use those directly.

**Comment by jhahn21** [comment]
I think I can use those files. But we also need mojom bindings.
So I'm trying to generate mojom binding for Java with the following command:

```
mojom_bindings_generator.py --use_bundled_pylibs -g java -o ../gen -I . mojo/public/interfaces/bindings/*.mojom
```
But Union tag seems to be generated incorrectly like this.
All of tags are 'None'

```
public final class UserDefinedType extends org.chromium.mojo.bindings.Union {

    public static final class Tag {
        public static final int EnumType = None;
        public static final int StructType = None;
        public static final int UnionType = None;
        public static final int InterfaceType = None;
    };
```

I'm using mojo_sdk 39488b961eb9dca8c6ca4a2cc0d693dd13db29e3.
Did I use mojom_bindings_generator incorrectly?

**Comment by jhahn21** [comment]
I fetched mojo_sdk like this: (as vanadium jiri profile install does):

```
mkdir mojo-sdk
cd mojo-sdk/
git clone --recursive https://github.com/domokit/mojo_sdk.git .
git reset --hard 39488b961eb9dca8c6ca4a2cc0d693dd13db29e3 --

cat tools/bindings/mojom_parser/bin/linux64/mojom_parser.sha1
wget https://storage.googleapis.com/mojo/mojom_parser/linux64/63b5ed7da139aa02d5443abe846542dd81495aae
mv 63b5ed7da139aa02d5443abe846542dd81495aae tools/bindings/mojom_parser/bin/linux64/mojom_parser
chmod +x tools/bindings/mojom_parser/bin/linux64/mojom_parser

PYTHONPATH=/usr/local/google/home/jhahn/mojo-sdk/third_party /usr/local/google/home/jhahn/mojo-sdk/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -g java -o ../gen -I . -I mojo/services mojo/public/interfaces/bindings/*.mojom
```

**Comment by MitchRudominer** [comment]
Still using tip-of-tree, I ran ninja with the -v option so it would show me what command it was running. I then ran that command manually and the resulting .java file was till correct. Here is the command I ran:
`python ../../mojo/public/tools/bindings/mojom_bindings_generator.py ../../mojo/public/interfaces/bindings/mojom_types.mojom --use_bundled_pylibs -d ../../ -I ../../ -I ../../ -o /home/rudominer/mojo/src/out/Debug/gen --no-gen-imports --no-generate-type-info`

**Comment by MitchRudominer** [comment]
I was in the directory out/Debug when I ran the above command.

**Comment by jhahn21** [comment]
really weird.

I tried the same flags both in gen and src directories, but it generated incorrectly.

```
PYTHONPATH=/usr/local/google/home/jhahn/mojo-sdk/third_party python /usr/local/google/home/jhahn/mojo-sdk/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -g java -o ../gen --no-gen-imports --no-generate-type-info -d . -I . mojo/public/interfaces/bindings/mojom_types.mojom
```

**Comment by MitchRudominer** [comment]
I think I know what is going on. I think the generation of union field tags in Java is just broken. The reason it works for me is that I am running the generator for multiple languages and one of the languages that runs prior to Java is correctly setting up the union field tags and then Java is making use of them. I'm still  trying to prove this theory.

**Comment by MitchRudominer** [comment]
Running the code generator on Java only is broken in other ways too I think.

**Comment by jhahn21** [comment]
Ah, yes. it works with `-g go,java`.

**Comment by jhahn21** [comment]
One more thing. It would be better to create output directories if not exist like other language.
For java, `No such file or directory: u'../gen/mojo/public/interfaces/bindings/mojom_types.mojom.srcjar'` occurred while it is created when generating for Go.

**Comment by MitchRudominer** [comment]
I just filed https://github.com/domokit/mojo/issues/689 to track the problems.
I also have a fix for them in the queue.

**Comment by MitchRudominer** [comment]
Unasssigning myself from this bug. Please close if you are satisfied are re-assign if you are not.

**Comment by jhahn21** [comment]
I think this can be closed. But I can't see a close button - maybe I don't have a permission for it.
