### ISSUE TITLE
Java bindings generator does not function by itself

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#689]
The Java bindings generator only works if it is run in conjunction with the generator from a different language that executes first. The three problems I am aware of are:

(1) The output directory will not be created if it doesn't exist
(2) The Python path will not be set correctly
(3) The union field tags will not be set.

**Comment by jamesr** [comment]
Is this particular to Java or do any other language generators have issues working standalone?  Could we test these in isolation?

**Comment by MitchRudominer** [comment]
The particular problems I found are particular to Java. I agree we should test the generators in isolation. As far as I know we currently do not.

**Comment by MitchRudominer** [comment]
I added https://github.com/domokit/mojo/issues/690 to track the issue of adding tests for stand-alone.

**Comment by viettrungluu-cr** [comment]
Did you really want to close this? It seems to me that adding tests is a separate issue/work item from the bug(s) that these tests would uncover....

**Comment by viettrungluu-cr** [comment]
Never mind, I missed the fact that you had fixed it!

Pro-tip: If you include "fixes #<issue number>" in the CL (e.g., in the BUG= bit), it'll automatically close it, in addition to adding the reference.

**Comment by jhahn21** [comment]
All of three issues are fixed now? Does (2) mean I don't need to set PYTHONPATH anymore?

**Comment by MitchRudominer** [comment]
Yes all fixed now. I'm not sure about whether or not you will need to set PYTHONPATH in your environment.
