### ISSUE TITLE
Sky shell shouldn't drink all my juice

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#69]
I locked my phone with sky shell running and my battery drained within an afternoon (see screenshot). Perhaps we're holding a wake lock? Or just not listening to onPause or something?

@qsr @eseidel 

![screenshot_2015-03-19-18-24-45](https://cloud.githubusercontent.com/assets/1731736/6744552/3bd5784a-ce68-11e4-97d3-e65176253194.png)

**Comment by tonygentilcore** [comment]
So much has changed since March that I don't think this is useful to keep open.

**Comment by eseidelGoogle** [comment]
I specifically addressed this bug a couple weeks ago.  Sorry I didn't find this bug and relate it at the time.
