### ISSUE TITLE
mojom parser doesn't detect cycles

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#694]
Things like the following shouldn't be allowed:
```
struct Baz {
  Quux quux;
};

struct Quux {
  Baz baz;
};
```

(Note that if `quux` or `baz` were nullable, it'd be OK.)

/cc @MitchRudominer

**Comment by MitchRudominer** [comment]
Thanks Trung. I actually have this on my list but it seems I have not made a bug for it yet, so thanks.

**Comment by MitchRudominer** [comment]
I believe that non-nullable arrays are allowed to have length zero and so may act as a cycle-breaker.

So this is ok: (@viettrungluu-cr do you agree?)
```
struct Foo{
  array<Foo> x;
}
```

But this is not ok:
```
struct Foo{
  array<Foo, 1> x;
}
```

Obviously these two are ok:
```
struct Foo{
  array<Foo, 1>? x;
}
```
```
struct Foo{
  array<Foo?, 1> x;
}
```

**Comment by viettrungluu-cr** [comment]
That sounds right.

Something similar applies for maps, I guess. Unions also pose significant
complications.

If you don't want to get it exactly "correct" now, it's probably OK to be
"overly" restrictive now, and then become more permissive/correct later.

**Comment by MitchRudominer** [comment]
Thanks. But I disagree with your suggestion about permissiveness. If the front-end is overly restrictive it might actually block somebody's work: For example it might prevent the introduction of a natural pattern in the design of Mozart. If the front-end is overly permissive the worst thing that will happen is that it will allow a pattern that cannot be serialized and the author will soon understand that when he attempts to use it.

All that said my plan is to get it exactly correct.

**Comment by viettrungluu-cr** [comment]
Being overly permissive means that in the future you'd be making "valid"
mojom files invalid. Allowing such invalid mojom files also may have bad
runtime implications, especially for anyone handling things dynamically.
