### ISSUE TITLE
Dart: Allow encoding a Stub for an interface request

### ISSUE THREAD

**Issue by zanderso** [domokit/mojo#699]
There should be a case for Stubs here:

https://github.com/domokit/mojo/blob/master/mojo/dart/packages/mojo/lib/src/codec.dart#L243

Mirroring the case for Proxies here:

https://github.com/domokit/mojo/blob/master/mojo/dart/packages/mojo/lib/src/codec.dart#L228

/cc @abarth @j9brown

**Comment by j9brown** [comment]
That was quick!

**Comment by zanderso** [comment]
https://codereview.chromium.org/1771743003/
