### ISSUE TITLE
Sky should respect mojo shell's --map-origin flag

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#71]
Mojo Shell supports a --map-origin flag that allows mapping an arbitrary origin to another. It's useful for SDK consumers to be able to do something like this in a dev environment:

--map-origin=http://example.com=http://localhost:9998

The problem is that Sky doesn't respect this when resolving links. @abarth @eseidel, would it make sense to support this?

@HansMuller

**Comment by abarth** [comment]
Rather than writing code in Sky to support this use case, we should instead implement this feature by interposing in front of mojo:network_service.  That way these URLs will be re-mapped for every Mojo app.

**Comment by tonygentilcore** [comment]
Good point.

@ppiet @qsr @colinblundell

**Comment by colinblundell** [comment]
To make sure I understand, the feature being discussed is to do this remapping for all URLs that are fetched via the network service rather than only for Mojo apps being connected to?

**Comment by tonygentilcore** [comment]
Yeah -- the rationale is that in a sky world, a .sky file (plus a content handler) basically is the mojo app from a consumer's point of view. I can't think of any use cases where it'd be desirable not to respect the mapping, but it's very possible I'm missing something.

**Comment by HansMuller** [comment]
Note to put too fine a point on it but: at the moment, a Modular Sky file
can't depend on a Modular .mojom.dart file. That's not good.

I would like to be able to write (in my Modular sky app) imports like:

import package:session_log/session_log.mojom.dart

**Comment by eseidel** [comment]
We haven't yet fixed the Sky subresource loader (<import>, <img>, etc.) to understand package: so you have to use manual urls like /packages/sky/foo.mojom.dart.  I can fix it as soon as I'm back, or perhaps someone else can fix it for you before.

**Comment by HansMuller** [comment]
Importing /packages/sky/foo.mojom.dart doesn't work if the (generated)
foo.mojom.dart file imports package:bar/bar.mojom.dart.

**Comment by tonygentilcore** [comment]
This use-case got solved in other ways.
