### ISSUE TITLE
Dart presubmit checks don't consider changes to mojom_types.mojom

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#714]
Some of the checked in .mojom.dart files now contain serialized runtime Mojom type information. This is a serialized MojomStruct from mojom_types.mojom.

I made a change to mojom_types.mojom and this required me to regenerate the .mojom.dart files by running  mojo/dart/tools/bindings/generate.py.

But then when I attempted to do a "git cl upload" there was a presubmit check failure that claimed 

```
Package _mojo_for_test_only has new mojo/dart/packages/_mojo_for_test_only/lib/dart_to_cpp/dart_to_cpp.mojom.dart without updating source .mojom file.
```
I had to use  --bypass-hooks to get git cl upload to proceed.

\cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@MitchRudominer I see two cases here:

1) We need to force a regeneration of all .mojom.dart files if mojom_types.mojom is modified. That is:

if mojom_types.mojom is modified:
  all .mojom.dart files should be regenerated.

2) We need to allow a .mojom.dart file to be modified without the .mojom file being modified if mojom_types.mojom is modified.

if X.mojom.dart file is modified and mojom_types.mojom is modified:
  pass


Is there a simple way for the presubmit script to determine which .mojom.dart files should be regenarted?

**Comment by MitchRudominer** [comment]
Actually, let's forget about the file mojom_types.mojom. That is already subsumed by looking at the two sha1 files. The following two files should be considered indicators that the Mojom compiler has changed and should force a regeneration of the .mojom.dart files.

mojo/public/tools/bindings/mojom_tool/bin/linux64/mojom.sha1
mojo/public/tools/bindings/mojom_tool/bin/mac64/mojom.sha1
