### ISSUE TITLE
Mojo SDK pub package should be available for every green rev

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#72]
Consumers of the mojo sdk can currently pin to any green revision on the mojo waterfall. The 'upload shell and app binaries' step takes care of uploading the rev-tagged artifacts for the build. Example:
http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux/builds/2168/steps/upload%20shell%20and%20app%20binaries/logs/stdio

It seems like it'd be pretty straightforward to add the sky_sdk to this step. This'd enable external repos to pin to a revision without having to worry about an incompatible sky sdk.

@HansMuller @abarth @eseidel

**Comment by abarth** [comment]
I agree we should adopt a cadence for publishing the sky_sdk.  It's unclear to me what that cadence should be.  For example, maybe once a week would be better than once every fifteen minutes.

**Comment by tonygentilcore** [comment]
Makes sense, but at the current pace of development, it's often useful to land a change in mojo and then be able to use it right away (without having to wait a week) in a bleeding edge sdk consumer. I'm not proposing that each of these releases be stable or pushed to everyone. But, rather, in the same sense that we already support bleeding edge mojo consumers picking their own mojo repo sha, it would be nice to be able to get the corresponding sky sdk without requiring the consumer to checkout mojo and build it themselves.

**Comment by abarth** [comment]
The Mojo and Sky SDKs can be versioned independently.  It sounds like you're interested in having the Mojo SDK deployed continuously.  Is there a reason to deploy the Sky SDK continuously?

As an example of why it might be valuable to have a different release cadence for the Sky SDK, we want to dogfood version skew between the Sky SDK, the Mojo SDK, and MojoShell.apk.  If we have monolithic releases of all three, we won't dogfood that condition and we won't feel whatever pain there is to version skew.

**Comment by tonygentilcore** [comment]
Good point of clarification. I only need the published mojo sdk to be consistent with a certain rev. The error that motivated me filing this bug was a message format mismatch crash.

**Comment by colinblundell** [comment]
@tonygentilcore, can you illustrate the flow that you were using that ended up in the error state you describe in the last comment? Do you have insight as to what resulted in that error state? What is the "it" that needs to be consistent between the Mojo SDK and the Sky SDK when the two are used in tandem in a client repo?

**Comment by tonygentilcore** [comment]
My setup is:

An external repository that depends on a specific SHA of the mojo repo via all of:
  (a) downloading a prebuilt mojo shell for that revision and a prebuilt network service (these binaries were uploaded by the mojo buildbots).
  (b) directly pulling and linking in mojo/public and mojo/services.
  (c) copying in some non-public mojo code (like mojo/tools and sky/tools).

The problem comes in when we try to have a pubspec that pulls in the Sky SDK (which isn't generated by the above mentioned process). The pubspec currently pulls mojo 0.0.1 and sky 0.0.2 (which correspond to some unknown SHA that isn't necessarily compatible with the pinned deps). We currently partially work around this with hacks that call to sky's deploy_sdk into the dev environment in a python wrapper script and special paths on the sky server (like /gen and /packages). But a problem we don't have a solution for yet is that we can't make the Dart Editor happy about the dependencies because sky server is hacking some mappings that are needed to run and if we give it a pubspec.yaml, that pulls incompatible versions as mentioned previously.

There are probably a lot of potential solutions. I'd be happy with anything that lets us:
  1. Use both pub and GN to get deps (perhaps via teaching our build to generate pubspec.lock files?).
  2. Roll in mojo changes at our desired cadence (without having to say, wait a week for a new release).

**Comment by tonygentilcore** [comment]
Colin got this use-case working.
