### ISSUE TITLE
Generated mojom.dart files shouldn't have any linter warnings

### ISSUE THREAD

**Issue by ianloic** [domokit/mojo#720]
For example,
% cd mojo/dart/packages/mojo_services
% dartanalyzer --lints lib/activity/activity.mojom.dart
Analyzing [lib/activity/activity.mojom.dart]...
(lots of lint warnings)
17 lints found.

I'm going to look at fixing the specific issues I'm seeing. It's hard to make this check automatic because of: https://github.com/dart-lang/sdk/issues/25977

**Comment by pylaligand** [comment]
FYI the --fatal-lints flag for dartanalyzer will be available with the next Dart release (April 22nd if you track stable).
