### ISSUE TITLE
dart bindings should not require that mojo services and SDK have given location wrt each other in a client repo

### ISSUE THREAD

**Issue by colinblundell** [domokit/mojo#73]
Cf. https://codereview.chromium.org/1022703005/#msg10, the dart bindings as used in the Mojo repo currently require that the relative location of Mojo services and the Mojo SDK in a client repo reflects their relative location in the Mojo repo. This is a bug, as services' interfaces are not part of the SDK and should be tied to the SDK.

@zanderso, can you provide specific examples of places within the Mojo repo that currently have this requirement? I want to remove this requirement ASAP, as it's a pretty significant bug.

**Comment by zanderso** [comment]
This issue is stale. The generated bindings are checked into the repo, and published as Dart packages.
