### ISSUE TITLE
compositor_service.mojo crashes when context is lost

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#733]
On android, when the context is lost, the applications sometime crashes.

The issue is the following:

When the application is in services/gfx/compositor/backend/gpu_rasterizer.cc in GpuRasterizer::Draw, while on a GaneshContext::Scope the call to frame_->Paint might result in GpuRasterizer::OnContextLost to be called. GpuRasterizer::OnContextLost will destroy the GaneshContext that tries to create a Scope in its destructor, and the context is checking that it is never reentrant in skia/ganesh_context.cc:62

**Comment by j9brown** [comment]
The whole GL context loss recovery pipeline is pretty broken.  This is on
my list but a low priority for now.  I might be able to patch around this
one but there are deeper issues.

**Comment by qsr** [comment]
This one is very visible, as going to the background on Android will crash the application 99% of the time.

**Comment by tonygentilcore** [comment]
Woot! I see this now when going to the background then foreground again:
```
[0419/173254:WARNING:gpu_rasterizer.cc(129)] GL context lost!
[0419/173254:WARNING:gpu_rasterizer.cc(139)] Recreating GL context.
```

**Comment by j9brown** [comment]
Note that it can crash due to other bugs.  I filed an issue on Skia for one
of them.  There's also a bug in how native viewport reports the vsync
interval sometimes that causes a crash (and may also cause jank).
