### ISSUE TITLE
Figure out if https://codereview.chromium.org/1842103003/ works on Android

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#737]
I can't figure out if https://codereview.chromium.org/1842103003/ actually works on Android. `mojob.py test --android` yields various failures for me, even on master. I'd like to land this change, but it'd be nice to know that it doesn't actually break the world on Android.

@qsr

**Comment by qsr** [comment]
mojo_run --android will use the network service. Just patched your CL in, and it works.

**Comment by viettrungluu-cr** [comment]
Thanks, @qsr!
