### ISSUE TITLE
Proposal: make responseFactory available for testing

### ISSUE THREAD

**Issue by pylaligand** [domokit/mojo#739]
In Dart bindings, interface methods are given a responseFactory object used to generate response messages (since Dart does not support multiple return values). It seems that the common pattern is to consider that reponseFactory will always be passed on the stub side and use it to generate the response. 

However this goes out of the window when trying to unit-test the interface implementations since the tests currently have no easy way to create such a responseFactory object.

I see three solutions:
1. make the factories available somewhere in the bindings so that a test can pass one to the implementation under test
2. write implementations defensively and effectively handle the case where responseFactory is null
3. don't write unit tests, or factor all the Mojo stuff out

(3) is not acceptable for various reasons (e.g. I'd like to be able to test the case where a connection goes down without essentially writing a proxy layer on top of all my bindings), (2) is feasible but not necessrily a pattern we would want to promote as it essentially results in two codepaths for run/test, and I don't know how feasible (1) is.

**Comment by j9brown** [comment]
Adam had some thoughts around replacing the response factory with a simpler
callback mechanism.

There are several other aspects of the Dart bindings that could be
improved, particular in the way of type safety and perhaps also performance.

**Comment by zanderso** [comment]
This is obsolete following https://github.com/domokit/mojo/commit/6efece8cde1702743c645eb6a1588d99578c0531
