### ISSUE TITLE
Dart bindings: make testing interface implementations easier

### ISSUE THREAD

**Issue by pylaligand** [domokit/mojo#746]
Let's define a mojom interface with a listener:
```
interface FooListener {
    OnFoo(string foo);
};

interface FooService {
    AddListener(FooListener listener);
};
```

Now let's imagine a class which uses FooService. When writing tests for that class, we'll need to mock FooService.

Since users of a mojom interface are dealing with proxies, we need to mock the proxy first and then the actual service implementation:
```
class MockFooServiceProxy implements FooServiceProxy {
  @override
  FooService ptr = new MockFooService();
}

class ManualMockFooService implements FooService {
  @override
  void addListener(Object trickyToSetUpObject) { . . . }
}
```

The two levels of mocks is an issue in itself as it creates a lot of boilerplate code for every single class we wish to mock. In addition, the Listener pattern introduces an extra difficulty with the type of argument passed to the `addListener` method. I believe the natural instinct is to think of it as a FooListener, but our FooService implementation has taught us that this is actually a FooListenerProxy. The catch is though that in tests this is yet another type: a FooListenerStub which will be passed straight from the client class to the mock service.

It would be nice to provide some testing libraries which would allow to 1/ get rid of the extra mocking layers and 2/ deal with more natural types.

Note that bypassing the extra layers might not always be desirable, e.g. if a test wants to verify that a connection to a service was properly closed by the class under test (that disconnection would happen via the proxy's `close` method).

**Comment by zanderso** [comment]
I believe this may be simpler now. I think you should be able to do:

```dart
class MockFooService implements FooService {
  void addListener(FooListenerInterface fooListener) {
    fooListener.iGotIt();
  }
}

class MyFooListener implements FooListener {
  void iGotIt() {...}
}

var fooService = new FooServiceInterface.fromMock(new MockFooService);
fooService.addListener(new FooListenerInterface(new MyFooListener));
```

Please give this a try, and re-open if there is still a problem. Thanks!

**Comment by j9brown** [comment]
Note that in actual Mojo, the call to iGotIt would be asynchronous.  Does
the fromMock generated proxy have this effect?

**Comment by zanderso** [comment]
Yes.

**Comment by pylaligand** [comment]
There might still be issues with the `ctrl` field which currently cannot be mocked. It becomes problematic when you want to test code that cleans things up after a disconnection.

**Comment by zanderso** [comment]
@pylaligand If you want to trigger the `errorFuture` on `ctrl` you can directly call `proxy.ctrl.proxyError("Some error message")`. If I'm misunderstanding what you're trying to do, please file a separate issue with a more detailed description.

**Comment by j9brown** [comment]
Perhaps the mock created with fromMock could offer some extra functions to
help here.  It feels weird for clients to be reaching down into relatively
obscure ctrl functions.  (To be honest, I would have expected something
like proxyError to be private.)
