### ISSUE TITLE
Mozart should provide a way to coordinate layout changes within a single frame

### ISSUE THREAD

**Issue by j9brown** [domokit/mojo#747]
/cc @abarth 

The Mozart compositor offers scheduling of scene updates on a frame-by-frame basis by way of the SceneScheduler interface.  At the beginning of each frame's update phase, the compositor notifies interested clients that it's time to do some work.  The compositor also provides information to the clients to allow them to anticipate upcoming frames to minimize the effects of IPC latency on kicking off rendering.

Unfortunately this causes a couple of problems:

1. A stampede happens at the beginning of each frame update.  This is mitigated by the fact that clients must express interest in receiving each update so only apps which are animating or which actually need to draw should be awoken.  A stampede is also a good signal for the frequency governor to step things up (and since we can predict them, we could explicitly kick up the clocks).

2. If a view's frame callback has the side-effect of setting view properties on some of its children or otherwise updating the view tree, then those changes will usually lag by a frame because other views have already started rendering the current frame assuming whatever values they had before.  Not good.

Alternatives:

A. Race!  This is the status quo.

Pros: Simplicity.

Cons: This only works well when views propagate and handle property changes immediately rather than deferring work to the frame callback.

Verdict: Nope.

B. Make the Mozart view manager responsible for scheduling frames so that it can give parent views first crack at frame updates before their children.

Pros: Views get a more convenient event to handle.

Cons: Clients could not anticipate the pulse as they do today using the Choreographer so they would be more vulnerable to scheduling jitter.  It would also significantly eat into the rendering budget and would be prone to hangs (would need timeouts to recover from unresponsive parents).  This is also bad news for video decoders and other components which may need scheduling at a Scene or ImagePipe level rather than at the View level.

Verdict: Nope.

C. Introduce a separate mechanism for propagating property changes through the view hierarchy which is arranged to be scheduled shortly *before* the SceneScheduler fires its frame callbacks.  We can model this as a kind of invalidation mechanism.

Pros: If view property propagation takes too long, rendering does not stall, we just end up with latency in proportion to how long it took to propagate the information down the tree.  It's still better than the status quo because when updates are quick we have a good change of applying them before the frame callback fires.

Cons: We can still lag frames.  To take best advantage of this mechanism, we would need to change how views work so they request invalidation as early as possible, apply property changes to children in their update callback as quickly as possible, then defer drawing to the frame update callback so that propagation can continue down the tree as quickly as possible (voluntarily yield the CPU).

Verdict: Better.

**Comment by krisgiesing** [comment]
Are property changes in the final scheme generic? That is, does Mozart need to know about specific property types, or are the client-participants in the system free to define their own property types?

**Comment by j9brown** [comment]
There's no opaque way to transfer properties today but there could be in the future.  I anticipate this being used to transfer information like locale and perhaps theme in addition to layout parameters.

**Comment by j9brown** [comment]
Closing as duplicate of #790
