### ISSUE TITLE
Passing too many frames too quickly to mozart results in a lock-up.

### ISSUE THREAD

**Issue by apwilson** [domokit/mojo#755]
Flutter likes to send a frame every vsync if it's got something new to display.  

During an animation this can result in up to 60FPS on an android device.

Mozart will appear to lock up if 60FPS is sent over a several second animation.

If I modify flutter to drop 75% of its frames and not send them to mozart (ie. fake 15FPS), we no longer lock up.

**Comment by j9brown** [comment]
Which device is this on?  This sounds like the Mojo message pump starvation issue.  If a receiver is kept sufficiently busy processing messages from one pipe then it can end up starving all other events.

**Comment by apwilson** [comment]
This was on an android device - Nexus 5X

**Comment by apwilson** [comment]
I also just tried this on Linux with similar results.

**Comment by apwilson** [comment]
I should also say that lock-up might be misleading, its rare that it will never recover.  Usually the lock-up lasts just for the duration of the animation (ie.  nothing happens and then there's a jump to the last frame or two of the animation).

**Comment by j9brown** [comment]
Yeah, that's the classic symptom of a starvation issue.

**Comment by j9brown** [comment]
Rolling this up into #684 .
