### ISSUE TITLE
Should get rid of "wrong way" ServiceProvider in ConnectToApplication()s, etc.

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#762]
`ConnectToApplication()` (in the `ApplicationConnector` and `Shell` interfaces) takes a `ServiceProvider&` (the usual direction) *and* a `ServiceProvider`. (Relatedly, `Application`'s `AcceptConnection()` has the same thing.)

The former is what everyone wants and uses. You connect to an application and then request services from it.

The latter is mostly a leftover from when interfaces had client interfaces (so connections were implicitly "bidirectional"). It's really odd, since it means that you connect to an application and provide a way for it to request services from you, without the ability to give any additional context.

We should get rid of the latter. Currently, the only user (I know of) is tracing. Tracing clients connect to the tracing service application, and the tracing service application will magically request stuff from clients. Instead, we should tracing clients actually request that they start doing this. (In worst case, in such a request, it can still push a `ServiceProvider` if it really wants -- but at least it'll be able to do so with additional context.)

A lot of the messiness of `ApplicationConnection` (which should basically be killed) results from all of this.

/cc @jamesr @j9brown

**Comment by j9brown** [comment]
Sure, let's get rid of it.  It's not clear what services may sense to "offer" to an application at connection time.  Offering services makes more sense when talking over a specific service interface.

**Comment by apwilson** [comment]
I can see it being useful in a sort of listening pattern.  "Hey service,
here's something you can notify if a change occurs."

**Comment by viettrungluu-cr** [comment]
Removing this doesn't break that, it just makes it things more explicit.
What we have now is more of a "hey service".

**Comment by jamesr** [comment]
I agree having explicit interfaces for the "other way" makes more sense.  I added this direction to ease the client removal transition but it doesn't appear to be terribly useful generally.

**Comment by alhaad** [comment]
A pattern that we use frequently is that application A discovers application B connects to it and provides it some services based on the 'type' of B.

(1) However, with no exposed services the following is what the code looks like:
```
A
-----------------

void acceptConnection(String requestorUrl, ApplicationConnection connection) {
  for (service in urlToService[requestorUrl]) {
    connection.provideService(service);
  } 
}

main() {
  for (url in urlToService.keys) {
    connectToApplication(url);
  }
}

B
---------------
void acceptConnection(String requestorUrl, ApplicationConnection connection) {
  if (requestUrl.endsWith('A')) {
    final newConnection = connectToApplication(requestorUrl);
    newConnection.requestService(someService);
   }
}
```

(2) as compared to what we had earler:
```
A
-----------------
main() {
  for (url in urlToService.keys) {
    final connection = connectToApplication(url);
    connection.provideService(urlToService[url]);
  }
}

B
---------------
void acceptConnection(String requestorUrl, ApplicationConnection connection) {
  if (requestUrl.endsWith('A')) {
    connection.requestService(someService);
  }
}
```

Is there a better way than (1) to achieve what we are trying?

**Comment by viettrungluu-cr** [comment]
@alhaad Your solution in (1) is IMO pretty broken: you shouldn't set up a system in which you expect the app you connect to to connect back to you (you = A, the app you connect to = B).

See https://groups.google.com/a/chromium.org/d/msg/mojo-dev/F1_GbKu1J6w/cZbIJGRYFgAJ for some suggestions. In particular, I'd say that A should request a particular service from B, and using that service A can then either provide B with typed services or even a ServiceProvider.

**Comment by alhaad** [comment]
Yeah (1) is very broken, but the fact that B has to define an interface and implement it just for this purpose seems convoluted.

I'll try passing a ServiceProvider over an interface, but I still a point in having 'exposed_services' for this particular use case.

**Comment by viettrungluu-cr** [comment]
It may seem convoluted, but it solves a significant (but subtle)
namespacing issue.

When you provide "exposed_services", the names of the services it exposes
must be those that the connectee (the one being connected to) expects.
Providing the same ServiceProvider that people get when they connect to you
as exposed_services is broken (because that ServiceProvider has names in
"your" namespace).

Moreover, exposing services is not a single use case. For example,
exposed_services was previously also used for tracing. Wouldn't you be sad
if the names of services required for tracing conflicted with your service
names? Having a single exposed_services also either breaks access control
(probably you only want to give access to your TraceProvider to the tracing
service, not everyone you connect to whom you want to provide services to)
or extremely convoluted code (customizing a ServiceProvider depending on
whom it is you're connecting to -- but even if you do that, it's limited,
since you end up in trouble if you want to connect to the same application
for different purposes).

Having to define an interface provides an important handshake: in effect,
it says, "yes, I want participate in this and provide services for this
purposes".

**Comment by viettrungluu-cr** [comment]
568f845 killed `exposed_services` (together with subsequent monet commits, and bdb59f7 to pull the updated monet).

Note that there's various cleanup work that could be done in the various bindings libraries in various languages (pretty much every language except C++, where I already did it in a bunch of semi-related cleanup): various analogues to the now-defunct C++ `ApplicationConnection` can be removed. I left TODO turds in front of those classes (and such).
