### ISSUE TITLE
Do the sky_viewer Mojo app and the sky SDK need to be published at the same cadence?

### ISSUE THREAD

**Issue by colinblundell** [domokit/mojo#77]
Currently, the sky viewer Mojo app is published at every green build in Mojo, just like all other apps in the Mojo repo. Consumers have two natural options for which sky_viewer version to use: (1) the one that was published along with the version of the Mojo SDK they are using, and (2) the latest published version. The Sky SDK is published manually on an as-desired basis. However, it seems to me that the Sky SDK and sky_viewer aren't guaranteed to play well together if they're not published from the same revision, as the SDK might be expecting runtime support that's not present in sky_viewer. For example, https://codereview.chromium.org/1028243003 simultaneously adds new support to sky_viewer and uses it in the sky SDK.

@eseidel @abarth What do you think?

@tonygentilcore fyi

**Comment by eseidel** [comment]
Correct, they aren't.  We don't have a solution for publishing a pub package on every revision (yet).  I can think of lots of ways we could do that, but right now changing sky at that level is pretty rare.  The vast majority of the change going into Sky at this moment is at the framework level (which is up in dart and does not depend on the sky_viewer C++ ABI or the dart "native" bindings which are dependent on having the same version of sky_viewer as you have package:sky).

**Comment by ppiet** [comment]
Closing as it seems there is no actionable items remaining here.
