### ISSUE TITLE
Tracing is busted

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#775]
Repro on clean master:

```sh
$ mojo/devtools/common/mojo_run mojo:spinning_cube --trace-startup
```

And, once the trace is written:

```sh
$ stat mojo_shell.trace
```

Observe that the file is empty.

cc @viettrungluu-cr @vardhan-cr @tonygentilcore

**Comment by ppiet** [comment]
```
b14cd33ee8b2780adbcbf721a73caca6ba7b5044 is the first bad commit
commit b14cd33ee8b2780adbcbf721a73caca6ba7b5044
Author: Viet-Trung Luu <viettrungluu@chromium.org>
Date:   Tue May 3 10:29:36 2016 -0700

    Use TraceProviderRegistry in //shell/context.cc.

    R=vardhan@google.com
    BUG=#763

    Review URL: https://codereview.chromium.org/1940973002 .
```

Trung, can you tal?

**Comment by viettrungluu-cr** [comment]
I will add this to the queue, with the priority indicated by its level of
testing.

**Comment by ppiet** [comment]
Thanks. For testing, there is anperf bot running trace-based benchmarks on the waterfall, see also https://github.com/domokit/mojo/issues/776 .

**Comment by viettrungluu-cr** [comment]
Hmmm, this seems to work for me now.

So, I'll close it. Please re-open (and add details) if it isn't fixed for you.

On the other hand, I think that #776 is probably still busted. Which, of course, indicates a woeful lack of testing. <shrug>
