### ISSUE TITLE
Benchmarks are busted

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#776]
Perf buildbot is has been sad since https://build.chromium.org/p/client.mojo/builders/Mojo%20Linux%20Perf/builds/4746 . The build says the relevant commit is:

```
Change #6242

Changed by	viettrungluu@chromium.org
Changed at	Tue 26 Apr 2016 11:16:50
Repository	https://chromium.googlesource.com/external/mojo
Project	mojo
Branch	master
Revision	20412557bd9672d3fe9c9ea85df2e948a4fbd883
Comments

ApplicationImpl::ConnectToServiceDeprecated() -> mojo::ConnectToService() conversion, part 2.

R=vardhan@google.com

Review URL: https://codereview.chromium.org/1915403002 .
```

This is likely separate from (but maybe related to?) #775 , as it predates the offending commit for #775.

cc: @viettrungluu-cr @vardhan-cr @tonygentilcore

**Comment by viettrungluu-cr** [comment]
I think that I fixed "benchmarks: benchmarks".

"benchmarks: rtt_benchmarks" is still busted, but seems to be a Dart bindings issue to me. -> @zanderso
