### ISSUE TITLE
dart analyzer shouldn't output redundant errors

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#78]
The dart analyzer step appears to print a single unique error out for every dartzip in the build. For example:

[warning] Undefined class 'MyClass' (my_package.dartzip:my.dart, line 107, col 29)
[warning] Undefined class 'MyClass' (my_package.dartzip:my.dart, line 107, col 29)
No issues found
No issues found
[warning] Undefined class 'MyClass' (my_package.dartzip:my.dart, line 107, col 29)
[warning] Undefined class 'MyClass' (my_package.dartzip:my.dart, line 107, col 29)
No issues found
[warning] Undefined class 'MyClass' (my_package.dartzip:my.dart, line 107, col 29)
ninja: build stopped: subcommand failed.

Instead, it'd be nice if it collected all the error messages into a set, tossed out "No issues found" and then just printed the unique errors. Bonus points if `my.dart` were the full src-relative path (currently the package.dartzip name can be loosely tied to the directory of the source file.

/cc @zanderso @eglaysher @colinblundell

**Comment by sethladd** [comment]
cc @bwilkerson
