### ISSUE TITLE
MojoWriteMessage() returns "busy" if a handle to be sent is in a two-phase write/read, but should it?

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#782]
Currently, `MojoWriteMessage()` returns `MOJO_RESULT_BUSY` if a data pipe producer/consumer handle to be sent is in a two-phase write/read, but should it?

This behavior kind of makes sense, but `MojoClose()` does not do this, and I don't think we want to prevent users from shooting themselves in the foot everywhere.

My feeling is that it shouldn't.

@jamesr WDYT?

**Comment by j9brown** [comment]
Probably unnecessary if we can make it error out when the app subsequently
calls the matching function to complete the two-phase operation on the
handle which has been closed / transferred.

**Comment by viettrungluu-cr** [comment]
Well, transferring a handle is (to the transferring side) equivalent to closing it (in observable effects).

So the likely error in ending the two-phase operation is "invalid handle (value)". But of course, the handle value may be reused, conceivably for something of the same type, and whoever has that value may conceivably actually start the same kind of two-phase operation. (All of these coincidences would lead to the operation "succeeding".)

**Comment by jamesr** [comment]
If it doesn't return BUSY, what is the effect on the data pipe as observed from the other end?  One possibility is that if the WriteMessage() succeeds it acts like the read/write was ended with num_bytes_XXX set to 0, since the multi-stage read/write can't survive the transition.    If the WriteMessage() fails does it behave as if nothing happened?

**Comment by viettrungluu-cr** [comment]
Yes, I suppose the behavior would have to be that the two-phase write/read
was terminated with 0 bytes.

(Currently, when it fails with "busy", there are no side effects.)

**Comment by jamesr** [comment]
It's kind of awkward for whatever started the two-phase read/write as they need to conclude the read/write themselves if the handle didn't send or forget about it if the handle did send, but that's the same issue as if it was conditionally MojoClose()d during the two-phase read/write so no new issue there.

Not returning BUSY sounds good.
