### ISSUE TITLE
Is MojoReduceRights() really what we want?

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#783]
Currently, we have (declared):
```
MojoResult MojoReduceRights(MojoHandle handle,
                            MojoHandleRights rights_to_remove);
```
Is this really what we want? Maybe we'd prefer something like:
```
MojoResult MojoReplaceHandleWithReducedRights(
    MojoHandle handle,
    MojoHandleRights rights_to_remove,
    MojoHandle* replacement_handle);  // Out.
```
This would effectively close `handle`.

This has the benefit of keeping a handle's rights immutable, which has various benefits, one of which is that you don't have to think too hard about what happens if you reduce a handle's rights while it's being used concurrently.

@jamesr WDYT?
/cc @cpu-chromium

**Comment by jamesr** [comment]
On initial thinking minting a new handle with the reduced rights seems nice.  The failure cases are slightly trickier - we would have to make strong promises that the handle is unmodified if the system couldn't mint |replacement_handle| for whatever reason, I think, but that seems resolvable.  It does make some use cases more awkward especially if code wants to do a 'just to be safe' rights reduction on a handle that's already wrapped up in potentially multiple places but that's a less interesting case to worry about.

**Comment by j9brown** [comment]
+1, definitely easier to work with if rights are immutable.

Wouldn't a "just to be safe" reduction always succeed?  The only reason
this call should fail is if you pass it an invalid handle.  There's no harm
in trying to remove rights which already aren't granted.

**Comment by jamesr** [comment]
> Wouldn't a "just to be safe" reduction always succeed?  The only reason
this call should fail is if you pass it an invalid handle.  There's no harm
in trying to remove rights which already aren't granted.

The difficulty is if a piece of code wants to ensure that a handle does not have a particular right at some point in time and the primitive to reduce rights is replace then every time it calls reduce it may have to update all other potential uses of that handle value.  With an in-place reduction calling ReduceRights() just-in-case is a no-op - the value stays the same.  This may or may not be an issue in practice.

**Comment by j9brown** [comment]
Why not add a query function?  That would make for an easy assertion at
lower layers of a program where it would not make sense to change handles.

Rights narrowing should mainly be happening at interfacing boundaries.
