### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by zanderso** [domokit/mojo#785]
Seems to be broken by: https://github.com/domokit/mojo/commit/9030792b19912f334f058261e23c2b36bc091ce0

@viettrungluu-cr 

```
$ ./mojo/tools/mojob.py build --release
...
FAILED: fusl_x64/obj/mojo/application/application.run_application.o
...
../../mojo/application/run_application.cc:89:26: error: no member named 'is_set' in 'mojo::(anonymous namespace)::ResultHolder'
  DCHECK(!result_holder->is_set);
          ~~~~~~~~~~~~~  ^
../../base/logging.h:658:54: note: expanded from macro 'DCHECK'
  LAZY_STREAM(LOG_STREAM(DCHECK), DCHECK_IS_ON() ? !(condition) : false) \
                                                     ^~~~~~~~~
../../base/logging.h:355:5: note: expanded from macro 'LAZY_STREAM'
  !(condition) ? (void) 0 : ::logging::LogMessageVoidify() & (stream)
    ^~~~~~~~~
1 error generated.
```

**Comment by viettrungluu-cr** [comment]
Sorry about that, will fix asap.

**Comment by viettrungluu-cr** [comment]
I believe this was not caught by the trybots, since their "release" builds build with DCHECK_ALWAYS_ON, whereas the waterfall bots don't. Sigh.

**Comment by jamesr** [comment]
We can change that behavior on the trybots if we want.  Chromium sets that as they can't afford debug bot coverage for everything but we do have equivalent coverage except for ASAN which shouldn't be influenced by dchecks (hopefully).

The config is set here: https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipes/mojo.py&q=dcheck_always_on&sq=package:chromium&type=cs&l=38 and then interpreted by mojob.py
