### ISSUE TITLE
mojo:dart_apptests flakily crash on shutdown

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#79]
The mojo dart_apptests step is flakily red on the buildbots due to crashing during shutdown.  Here's a backtrace from a local (release) run on linux:

(gdb) bt
#0  dart::ThreadInterrupterLinux::ThreadInterruptSignalHandler (signal=27, info=0x7fff04429130, context_=0x7fff04429000) at ../../dart/runtime/vm/thread_interrupter_linux.cc:21
#1  <signal handler called>
#2  0x00007f3df0def687 in munmap () at ../sysdeps/unix/syscall-template.S:81
#3  0x00007f3df0deeddd in _dl_unmap (map=0x36910d8d6300) at ../sysdeps/x86_64/tlsdesc.c:139
#4  0x00007f3df0debbf7 in _dl_close_worker (map=map@entry=0x36910d8d6300) at dl-close.c:639
#5  0x00007f3df0dec48c in _dl_close (_map=0x36910d8d6300) at dl-close.c:773
#6  0x00007f3df0de5ff4 in _dl_catch_error (objname=0x36910d8a7f90, errstring=0x36910d8a7f98, mallocedp=0x36910d8a7f88, operate=0x7f3df0bd30e0 <dlclose_doit>, args=0x36910d8d6300) at dl-error.c:187
#7  0x00007f3df0bd362d in _dlerror_run (operate=operate@entry=0x7f3df0bd30e0 <dlclose_doit>, args=0x36910d8d6300) at dlerror.c:163
#8  0x00007f3df0bd310f in __dlclose (handle=<optimized out>) at dlclose.c:46
#9  0x000000000044fce0 in mojo::shell::InProcessNativeRunner::~InProcessNativeRunner() ()
#10 0x000000000044fd29 in mojo::shell::InProcessNativeRunner::~InProcessNativeRunner() ()
#11 0x00000000004a18f3 in mojo::shell::ApplicationManager::~ApplicationManager() ()
#12 0x000000000040c1d9 in mojo::shell::Context::~Context() ()
#13 0x0000000000408109 in main ()

The issue appears to be that dart::ThreadInterrupterLinux is installing a signal handler for SIGPROF and never uninstalling it.  During mojo shutdown we try to unload the app containing the dart VM and this signal handler runs against an unloaded DLL.  This stack is not the only way it can crash, any signal handler that runs after the dart vm app is unloaded crashes.

Is this ThreadInterrupter thread joined on dart vm shutdown?  Would it be possible to unregister the signal handler then?

/cc @johnmccutchan @viettrungluu-cr

**Comment by johnmccutchan** [comment]
Thanks for the stack trace. I'll take this.

**Comment by johnmccutchan** [comment]
The ThreadInterrupter thread is joined on VM shutdown but:

* A number of SIGPROF(s) may still be in flight (sent before thread is joined but not delivered until after shared object is unloaded).
* The signal handler is still registered.

I have a CL up for review that unregisters the signal handler before VM shutdown (and ignores any pending SIGPROF signals).
