### ISSUE TITLE
mojo build for Android is spammy

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#80]
E.g.:

$ mojo/tools/mojob.py build --android
[...]
[1900/2696] ACTION //mojo/android:mojo...ist_jar(//build/toolchain/android:arm)
/usr/local/google/home/vtl/projects/mojo/src/build/android/gyp/util/build_utils.py:251: UserWarning: Duplicate name: u'META-INF/'
  out_zip.writestr(name, in_zip.read(name))
/usr/local/google/home/vtl/projects/mojo/src/build/android/gyp/util/build_utils.py:251: UserWarning: Duplicate name: u'META-INF/MANIFEST.MF'
  out_zip.writestr(name, in_zip.read(name))
[...]

**Comment by viettrungluu-cr** [comment]
@qsr Could you please take a look at this?

**Comment by qsr** [comment]
https://codereview.chromium.org/1075143003/

**Comment by viettrungluu-cr** [comment]
Thanks for the fix! (Now I guess someone needs to do a Chromium -> Mojo update....)

There's also:

AndroidManifest.xml:12 Permission is only granted to system apps: ProtectedPermissions [warning]
    <uses-permission android:name="android.permission.INJECT_EVENTS" />
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Lint found 1 new issues.
 - For full explanation refer to out/android_Release/gen/mojo/android/mojo_test_apk__java__lint/result.xml
 - Wanna suppress these issues?
    1. Read comment in build/android/lint/suppressions.xml
    2. Run "python build/android/lint/suppress.py out/android_Release/gen/mojo/android/mojo_test_apk__java__lint/result.xml"

**Comment by eseidelGoogle** [comment]
Thank you very much for fixing this!

**Comment by viettrungluu-cr** [comment]
Hmmm, I just got (on an Android debug build):
```
[5884/8923] ACTION //ui/android:ui_jav...__javac(//build/toolchain/android:arm)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by viettrungluu-cr** [comment]
@rogulenko for the second thing above, since it looks go-related.

**Comment by jamesr** [comment]
Issue #125 is on file for the Go spam

**Comment by ppiet** [comment]
Closing this as the Go spam is tracked in #125 and a clean Android build does not produce any other log output.
