### ISSUE TITLE
Mojo c generator prevent no-op build

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#803]
On a dependant project of mojo, we are importing the mojo sdk and using mojom.gni

 When rebuilding an up-to-date project, I still see a lot of build being re-executed. ninja is expecting to see .c files that are not generated.

/cc @nellyv

**Comment by vardhan-cr** [comment]
Are you seeing build failures (you say that ninja is expecting to see .c files that aren't there) in your repo? I believe you should also be errors for go bindings as well, right? Would you mind pasting the verbose output somewhere if possible?

mojom.gni is admittedly very monolithic right now, and isn't designed to be easily consumed by other repos, and needs to be reworked -- right now, every language-specific target depends on a "__generator" target depends on and generates bindings for every language (including go, js, dart).  I think fixing this problem require writing a big chunk of mojom.gni.

The C bindings generator (and the new Go generator) dependencies are actually pulled in externally using gclient -- the immediate fix i recommend is pulling in the generator binaries (see the "mojom_generators" hook in DEPS).

**Comment by nellyv** [comment]
There are no failures but the build is re-executed even without any changes on the source.
Running `ninja -d explain -j2000 -C out/Debug` we get:

```
ninja: Entering directory `out/Debug'
ninja explain: output gen/mojo/public/interfaces/bindings/interface_control_messages.mojom-c.h doesn't exist
ninja explain: gen/mojo/public/interfaces/bindings/interface_control_messages.mojom-common.cc is dirty
ninja explain: gen/mojo/public/interfaces/bindings/interface_control_messages.mojom-common.h is dirty
...
```

And the missing `interface_control_messages.mojom-c.h` file is not generated after re-building.

**Comment by vardhan-cr** [comment]
I would guess this is happening because you don't have mojom_generator hook
in your repo's DEPS -- does that work for you?

**Comment by nellyv** [comment]
I added the hook and it seems to be working fine now. Thanks!
