### ISSUE TITLE
New dart generated bindings introduce analyzer errors

### ISSUE THREAD

**Issue by ianloic** [domokit/mojo#804]
We use --fatal-hints in our project and the new bindings introduce an unused local variable 'r' everywhere. For a random example:
```
~mojo/mojo/dart/packages/mojo_services% dartanalyzer --fatal-hints lib/input/input.mojom.dart
Analyzing [lib/input/input.mojom.dart]...
[error] The value of the local variable 'r' is not used (/Users/ianloic/tq/mojo/src/mojo/dart/packages/mojo_services/lib/input/input.mojom.dart, line 290, col 13)
[warning] Undefined name 'callbackMap' (/Users/ianloic/tq/mojo/src/mojo/dart/packages/mojo_services/lib/input/input.mojom.dart, line 296, col 29)
[warning] Undefined name 'callbackMap' (/Users/ianloic/tq/mojo/src/mojo/dart/packages/mojo_services/lib/input/input.mojom.dart, line 302, col 9)
1 error and 2 warnings found.
zsh: exit 3     dartanalyzer --fatal-hints lib/input/input.mojom.dart
```

**Comment by krisgiesing** [comment]
@Hixie Is there some reason this isn't also causing issues for Flutter?

**Comment by ianloic** [comment]
IIRC Flutter greps out errors that come from *.mojom.dart.

**Comment by Hixie** [comment]
We currently ignore warnings in any code we didn't write. At some point we're going to start caring more about warnings in our dependencies and this will likely lead to us pushing to get the bindings to compile cleanly.

**Comment by krisgiesing** [comment]
I wonder if Modular should do the same (in parallel to fixing this particular issue).

**Comment by viettrungluu-cr** [comment]
If this is something people care about, we should have tests for it. @zanderso

**Comment by ianloic** [comment]
Yeah, I failed to add tests last time I fixed this. My bad.

@Hixie are you still basically grepping the output of dartanalyzer to exclude code you don't care about?

**Comment by Hixie** [comment]
I think right now we're accidentally not checking the .mojom.dart files because they happen to be in the engine repo and not the framework (`flutter`) repo, and for various technical reasons we're only checking the latter. (For the same reason we fail to analyze `dart:ui` and `dart:jni`.) We have plans to fix this but @pq may know more about that.

**Comment by Hixie** [comment]
(Note that Flutter's use of the analyzer turns on almost all the flags, including lots of lint stuff and all but four strong mode checks. By default `dartanalyzer` isn't anywhere near as strict.)

**Comment by ianloic** [comment]
Posted a patch for review: https://codereview.chromium.org/2149533004/
