### ISSUE TITLE
Can't control how much memory MojoBeginWriteData and MojoBeginReadData map

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#812]
The magenta versions of these APIs let you supply a max size for the mapping so that you can control how much of your address space is consumed.  That seems worth doing in the Mojo API as well.

/cc @jamesr @viettrungluu-cr

**Comment by viettrungluu-cr** [comment]
I removed that parameter from the magenta version.

The two-phase APIs are mostly useful if the mapping is persistent, and a persistent mapping is really only useful if the entire buffer is mapped.
