### ISSUE TITLE
Missing dependency in the C mojom generator

### ISSUE THREAD

**Issue by abarth** [domokit/mojo#814]
```
FAILED: obj/out/debug-x86-64/gen/mojo/services/gfx/composition/interfaces/interfaces_c.compositor.mojom-c.o 
../../buildtools/toolchain/clang+llvm-x86_64-darwin/bin/clang -MMD -MF obj/out/debug-x86-64/gen/mojo/services/gfx/composition/interfaces/interfaces_c.compositor.mojom-c.o.d  -I../.. -Igen -I../.. -Igen -g --sysroot=../../buildtools/sysroot/x86_64-fuchsia -fPIE --target=x86_64-fuchsia -Werror -Wall -Wextra -Wno-unused-parameter -g -O0 -std=c11 -c gen/mojo/services/gfx/composition/interfaces/compositor.mojom-c.c -o obj/out/debug-x86-64/gen/mojo/services/gfx/composition/interfaces/interfaces_c.compositor.mojom-c.o
In file included from gen/mojo/services/gfx/composition/interfaces/compositor.mojom-c.c:3:
gen/mojo/services/gfx/composition/interfaces/compositor.mojom-c.h:26:10: fatal error: 'mojo/services/gpu/interfaces/context_provider.mojom-c.h' file not found
#include "mojo/services/gpu/interfaces/context_provider.mojom-c.h"
         ^
1 error generated.
```

@vardhan-cr @viettrungluu-cr

**Comment by abarth** [comment]
mojo/services/gfx/composition/interfaces/compositor.mojom depends on mojo/services/gpu/interfaces/context_provider.mojom but the build doesn't know that mojo/services/gpu/interfaces/context_provider.mojom needs to be generated before compiling mojo/services/gfx/composition/interfaces/compositor.mojom-c

**Comment by vardhan-cr** [comment]
The dependencies listed in mojo/services/gfx/composition/interfaces/BUILD.gn includes mojo/services/gpu/interfaces, so I don't see anything wrong there.  According to @abarth, it worked when he tried again.

**Comment by abarth** [comment]
When the template expands, does the c target inside composition/interfaces/BUILD end up with a dep on the c target inside gpu/interfaces/BUILD.gn?  The two groups having a dependency on each other isn't sufficient to ensure the ordering we need.

**Comment by abarth** [comment]
Take a look at `source_set("${target_name}_c") {` in mojom.gni.  It probably needs some logic that uses `invoker.deps`

**Comment by abarth** [comment]
Hey, can you update the fuchsia tree?  Folks are still running into this issue there.

**Comment by viettrungluu-cr** [comment]
I'm updating now, which should take care of it.

**Comment by vardhan-cr** [comment]
Thanks Trung!
