### ISSUE TITLE
mojom c++ bindings gencode is invalid if the mojom is in a directory with a - in the name

### ISSUE THREAD

**Issue by gmesch** [domokit/mojo#817]
gen/apps/modular/story-runner/main.mojom-common.h:2:27: error: extra tokens at end of #ifndef directive
#ifndef APPS_MODULAR_STORY-RUNNER_MAIN_MOJOM_COMMON_H_

**Comment by jamesr** [comment]
This'll break other generators too.  Could you put these in a directory that doesn't have a "-" character?

**Comment by gmesch** [comment]
I just fixed it for C++. I can look at others, but this particular construct only exists in C++.

**Comment by gmesch** [comment]
Fixed for C++ by https://fuchsia-review.googlesource.com/#/c/8432/

**Comment by gmesch** [comment]
Hm, so it does also break the C generator, and the C generator is a binary in the source tree. Where do I find its sources?

**Comment by vardhan-cr** [comment]
The C generator is found under the fuschia project, under mojom/ repo.
Specifically, the thing to edit is:  https://fuchsia.googlesource.com/mojom/+/master/src/mojom/generators/c/cgen/type_translation.go#23

**Comment by vardhan-cr** [comment]
(once you edit the generator, you also need to build+upload the generator binary, and checkin the binary hashes so that other repos can pull it in. i'm away next week, so feel free to ask @AlexandreZani or @viettrungluu-cr if you have any questions about how)

**Comment by gmesch** [comment]
Yeah, right. Why make anything simple.

**Comment by gmesch** [comment]
There is no documentation as to how to build or deploy in the mojom repo; so I won't touch it.

**Comment by gmesch** [comment]
@AlexandreZani can you point me to how to build the go mojom compiler? I would like to fix this finally.

**Comment by viettrungluu-cr** [comment]
Sometimes there's information in the README.md, and sometimes the
information is even accurate. Anyway, I'm doing this now.

**Comment by gmesch** [comment]
I read all the README files I could find, but couldn't find any that tell me how to build it.

**Comment by viettrungluu-cr** [comment]
How about the one in the mojom repo?

**Comment by gmesch** [comment]
Yeah right: 

"""
# Mojom tool

This repository contains the mojom tool, together with (new-style) code
generators.
"""

There is a BUILD.gn file that jamesr assured me doesn't do what I think it does.

So there.

**Comment by AlexandreZani** [comment]
Hey mesch,

Sorry about the confusion. There is a README file in the fuchsia repo:

https://fuchsia.googlesource.com/mojom/

Alex

**Comment by gmesch** [comment]
Ha, I was looking at the same README.md but on my branch from two weeks ago
when I first tried to fix that. Jiri caveat again.

**Comment by gmesch** [comment]
OK, but my original problem still isn't fixed in the mojom c generator, right?

**Comment by gmesch** [comment]
Which cloud project do I need to be member of to be able to upload? Can you
please add me?

On 16 September 2016 at 15:20, mesch (孟熙 Steffen Meschkat) <mesch@google.com
> wrote:

> Ha, I was looking at the same README.md but on my branch from two weeks
> ago when I first tried to fix that. Jiri caveat again.
>
> On 16 September 2016 at 15:16, Alexandre Zani <notifications@github.com>
> wrote:
>
>> Hey mesch,
>>
>> Sorry about the confusion. There is a README file in the fuchsia repo:
>>
>> https://fuchsia.googlesource.com/mojom/
>>
>> Alex
>>

**Comment by gmesch** [comment]
(Or else please upload tools again, after
https://fuchsia-review.googlesource.com/#/c/10066/ is in.

On 16 September 2016 at 15:52, mesch (孟熙 Steffen Meschkat) <mesch@google.com
> wrote:

> Which cloud project do I need to be member of to be able to upload? Can
> you please add me?
>
> On 16 September 2016 at 15:20, mesch (孟熙 Steffen Meschkat) <
