### ISSUE TITLE
Building Dart observatory is super-spammy

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#83]
[262/297] ACTION //mojo/dart/embedder:copy_observatory_deps(//build/toolchain/linux:clang_x64)
Resolving dependencies...
Warning: You are using these overridden dependencies:
! analyzer 0.22.4 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/analyzer
! args 0.12.2+5 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/args
! barback 0.15.2+4 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/barback
! browser 0.10.0+2 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/browser
! cli_util 0.0.1+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/cli_util
! code_transformers 0.2.5 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/code_transformers
! collection 1.1.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/collection
! csslib 0.11.0+4 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/csslib
! dart_style 0.1.3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/dart_style
! glob 1.0.4 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/glob
! html5lib 0.12.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/html5lib
! initialize 0.5.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/initialize
! logging 0.9.3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/logging
! matcher 0.11.4+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/matcher
! observe 0.12.2+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/observe
! path 1.3.2 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/path
! polymer 0.15.5+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/polymer
! polymer_expressions 0.13.0+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/polymer_expressions
! pool 1.0.1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/pool
! smoke 0.2.1+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/smoke
! source_maps 0.10.0+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/source_maps
! source_span 1.0.3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/source_span
! stack_trace 1.2.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/stack_trace
! string_scanner 0.1.3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/string_scanner
! template_binding 0.14.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/template_binding
! unittest 0.11.5+3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/unittest
! usage 1.0.0+1 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/usage
! utf 0.9.0+2 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/utf
! watcher 0.9.4 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/watcher
! web_components 0.10.2 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/web_components
! when 0.2.0 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/when
! which 0.1.3 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/which
! yaml 2.1.2 from path /usr/local/google/home/vtl/projects/mojo/src/dart/third_party/observatory_pub_packages/yaml
Changed 33 dependencies!
[273/297] ACTION //mojo/dart/embedder:pub_build_observatory(//build/toolchain/linux:clang_x64)
Loading source assets...
Loading initialize/build/loader_replacer, initialize, polymer/src/build/mirrors_remover, code_transformers/src/delete_file, observe, smoke/src/default_transformer and web_components transformers...
Loading polymer transformers...
Building observatory...
[Info from Dart2JS]:
Compiling observatory|web/index.html_bootstrap.dart...
[Warning from Dart2JS on observatory|web/index.html_bootstrap.dart]:
packages/observatory/src/service/object.dart:1903:17:
No member named 'library' in class 'ServiceObject'.
      library = dartOwner.library;
                ^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on observatory|web/index.html_bootstrap.dart]:
packages/observatory/src/service/object.dart:1904:26:
No member named 'qualifiedName' in class 'ServiceObject'.
      qualifiedName = "${dartOwner.qualifiedName}.${name}";
                         ^^^^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on observatory|web/index.html_bootstrap.dart]:
packages/observatory/src/service/object.dart:1907:17:
No member named 'library' in class 'ServiceObject'.
      library = dartOwner.library;
                ^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on observatory|web/index.html_bootstrap.dart]:
packages/observatory/src/service/object.dart:1988:33:
No member named 'darOwner' in class 'Field'.
  String toString() => 'Field(${darOwner.name}.$name)';
                                ^^^^^^^^
[Warning from Dart2JS on observatory|web/index.html_bootstrap.dart]:
packages/observatory/src/service/object.dart:1969:17:
No member named 'library' in class 'ServiceObject'.
      library = dartOwner.library;
                ^^^^^^^^^^^^^^^^^
[Info from Dart2JS]:
Took 0:00:19.106539 to compile observatory|web/index.html_bootstrap.dart.
Built 132 files to "/usr/local/google/home/vtl/projects/mojo/src/out/Debug/observatory/build".

**Comment by viettrungluu-cr** [comment]
@johnmccutchan Could you please take a look at this?

**Comment by johnmccutchan** [comment]
The following https://codereview.chromium.org/1073113005/ will completely silence Observatory builds.
