### ISSUE TITLE
ninja always things observatory_sources.gypi is dirty and thus always regenerates

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#84]
~/projects/mojo/src$ ninja -C out/Debug -d explain
ninja: Entering directory `out/Debug'
ninja explain: /usr/local/google/home/vtl/projects/mojo/src/mojo/dart/embedder/observatory_sources.gypi is dirty
[1/1] Regenerating ninja files
ninja: no work to do.
~/projects/mojo/src$ ninja -C out/Debug -d explain
ninja: Entering directory `out/Debug'
ninja explain: /usr/local/google/home/vtl/projects/mojo/src/mojo/dart/embedder/observatory_sources.gypi is dirty
[1/1] Regenerating ninja files
ninja: no work to do.
~/projects/mojo/src$

**Comment by viettrungluu-cr** [comment]
@johnmccutchan Could you please take a look at this?

**Comment by colinblundell** [comment]
https://codereview.chromium.org/1079033002/
