### ISSUE TITLE
Starting up network service takes 500ms+ on Android

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#86]
It takes 500ms+ to start running the network service on Android. Since all apps have to download via this service, this means nothing can start up faster than this no matter how svelte it is.  Tracing shows that nearly all of this time is going into the Android handler startup sequence.  Once the service actually starts running, it's really fast.  Here's some tracing data under the AndroidHandler::RunApplication trace:

Name | Wall Duration (ms) | CPU Duration (ms) | Self Time (ms) | CPU Self Time (ms) | Occurrences
-----|--------------------|-------------------|----------------|--------------------|------------
BlockingCopyToFile | 35.291 | 23.529 | 35.291 | 23.529 | 1
ExtractBootstrapJavaLibrary | 1.085 | 1.029 | 1.085 | 1.029 | 1
ExtractBootstrapNativeLibrary | 4.858 | 4.759 | 4.858 | 4.759 | 1
ExtractApplicationJavaLibrary | 88.293 | 86.566 | 88.293 | 86.566 | 1
ExtractApplicationNativeLibrary | 61.988 | 57.028 | 61.988 | 57.028 | 1
CreateDexClassLoader | 305.332 | 14.445 | 305.332 | 14.445 | 1
Totals | 496.847 | 187.356 | 496.847 | 187.356 | 6

The fact that CreateDexClassLoader takes so long is particularly surprising since this service should have very little java.

/cc @qsr @tonygentilcore

**Comment by jamesr** [comment]
@ppiet says that the time in CreateDexClassLoader is spent doing the dex optimize step, which systrace confirms.  He's going to look at caching the results of this step.

**Comment by ppiet** [comment]
Benjamin has some CL in progress that could help with that.

**Comment by viettrungluu-cr** [comment]
I think this is obsolete.
