### ISSUE TITLE
MojoShell sometimes hangs for ~11s in activityStart prior to main

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#87]
Some of the time (33%? 50%?) MojoShell sits with a blank window for 10-12 seconds doing nothing before our main runs.  Android systrace: https://drive.google.com/file/d/0Bx3FsySZx1hSendRT29yQzJTTTQ/view?usp=sharing shows that we're spending 11-ish seconds inside of activityStart.  It's unclear from the trace what is actually happening in this time (if anything).  Trace recorded by running:

./mojo/tools/android_mojo_shell.py --release --trace-startup mojo:spinning_cube

My suspicion given that everything on the phone appears to be idle (clocks are all turned down, etc) is that it's waiting for some information from the host in order to start running.

/cc @ppiet @qsr @tonygentilcore

**Comment by ppiet** [comment]
Ad-hoc instrumentation suggests that we are blocking in freopen call that is redirecting the shell stdout to a fifo file. The call is blocking until fifo is open for reading from the other side - thanks, @qsr for explanation.
