### ISSUE TITLE
Binary stability: gpu::ContextSupport is exported by GLES2 thunks

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#89]
We need to use thunks instead.

Also, this object has member that takes base::Closure as parameters, and we need to abstract those as base::Closure is not stable (and is not even passable between a Debug and Release build of the same sources).

**Comment by jamesr** [comment]
More specifically the interface has to be C, not C++ objects

**Comment by jamesr** [comment]
There aren't any uses of the gpu::ContextSupport objects from the Mojo repo.  Chromium's still using it for html_viewer via downcast

**Comment by viettrungluu-cr** [comment]
Obsolete.
