### ISSUE TITLE
android_mojo_shell.py should create and open the fifo before starting the shell.

### ISSUE THREAD

**Issue by ppiet** [domokit/mojo#91]
Instead of creating the fifo, opening it for writing and waiting for the script to open it for reading in the shell code, we could try creating the fifo and opening it for reading in the script before the shell is started.

That would speed up the startup and simplify the script.

/cc @qsr @jamesr

**Comment by qsr** [comment]
An issue with that is that it will be harder to detect if the shell crashes before opening the fifo. You read will be blocked and we will not have any signal telling us that this will never be unblocked.

**Comment by viettrungluu-cr** [comment]
Maybe there should just be an explicit timeout (for the first thing to be
read from the FIFO)? (Presumably, you'd want the shell to immediately write
something to the FIFO after opening it.)

**Comment by ppiet** [comment]
Moved to the devtools tracker at https://github.com/domokit/devtools/issues/9 .
