### ISSUE TITLE
Mojo should expose an oath2 service

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/mojo#94]
Mojo should expose the ability to get oath2 tokens from the OS. On android, that looks like this:
https://developer.android.com/google/auth/http-auth.html

There's a CL in progress that does this for basic HTTP here, but I'm not sure whether it is being actively pursued.
https://codereview.chromium.org/1017713002/

/cc @qsr @seefeldb @brawer

**Comment by qsr** [comment]
What is your use case? This particular CL is not a generic way to get OAuth2 token, but a way for the shell to access protected resources.

Adding a generic mechanism is find too, but we need to decide how we let the user control when he want to allow the shell to generate a token or not...

**Comment by tonygentilcore** [comment]
I'd like to be able to authenticate with Firebase's REST API using the user's google account. Documentation here: https://www.firebase.com/docs/rest/guide/user-auth.html

I suspect the most seamless implementation would be for the service to send an intent to the android system to display the account picker/access permission to the user and then read the token from the intent's return value. It'd be fine if the service only worked on android in the first implementation.

**Comment by qsr** [comment]
But how would the user knows which service is asking for authorization to access its data?

**Comment by tonygentilcore** [comment]
The mojo service's API would require the caller to pass the client ID of the google application which is requesting the token (more details at https://www.firebase.com/docs/web/guide/login/google.html).

**Comment by qsr** [comment]
Sorry, there is some misunderstanding here.

If an mojo app can have an OAuth2 token for the user, it can then access some remote service as the user.

It means that the user needs to know which Mojo Application is requesting for a token, not just which remote app will be contacted.

It means that the mojo authentication service you are speaking about need to get consent from the user. And we have no easy way to do this today...

**Comment by seefeldb** [comment]
Ack, but let's track this as another requirement before we can open this
widely, incl. dogfood outside the team.

Note that we have the same problem for any Mojo Application talking to any
other exposed service, incl. Mojo-wrapped Android APIs. Not having
sandboxing also leads to a lot related issues.

**Comment by tonygentilcore** [comment]
I understand your point. We absolutely should not allow this proposed auth service to be called from arbitrary mojo apps. I'd propose we have some concept of "privileged" system apps which are pre-installed into the shell and can do things that downloaded apps cannot do. We could enforce that by testing the URL of the connecting service.

But maybe your point is that once the mojo shell apk has a certain permission, then there's nothing we can do to prevent any application running within it from using that permission. That seems like a problem worth inspiring more design around how we'll sandbox.

**Comment by qsr** [comment]
No my issue is the first point. For the second point, we will have ways (only privileged apps will have access ot the android context, and we will run other apps in other process, with fork/exec from an isolated process)

But for the first point, I don't think privileged app is the right thing. The facebook app is not privileged, but should be able to get tokens for the facebook site. Mainly, we need a way to let the user knows which app is requesting a token before sending one to the mojo application.

 We can decide to delay this for sure, but we have to make sure we solve this before distributing this.

**Comment by tonygentilcore** [comment]
Can we do it by origin of the mojo app like the browser does? ie. "example.com would like access to authenticate to $REMOTE_APPLICATION"

**Comment by qsr** [comment]
The issue is that we do not have any way for a generic service to do any UI at all... Out of this, yes we will probably do it by origin.

**Comment by tonygentilcore** [comment]
@qsr and I talked briefly about this offline. A minimal first step might be a service that allows the user to grant a mojo-shell wide oauth2 token for a google account that is already registered on the device. This'd allow us to demo/test mojo apps that require auth (with the understanding that it isn't safe for an environment that includes arbitrary mojo apps). Then, subsequently we can design the non-trivial scheme for safely supporting app level granularity.

**Comment by tonygentilcore** [comment]
Marking this fixed as the initial impl seems to be working. We can file more bugs for continued enhancement.
