### ISSUE TITLE
/sky_home and Stocks App take several seconds to load in SkyDemo.apk

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#97]
We had a trace at one point.  I'll get a new one and attach it.

@abarth

**Comment by eseidelGoogle** [comment]
6.5 seconds to fetch all our .dart files from github.io
1.3 seconds to actually do the bootup once we have them.

@Hixie tells me that a few weeks ago @abarth had this under 1s boot time, presumably that was running off of local host.

I don't see any way to attach files to issues in Github unfortunately.

**Comment by eseidelGoogle** [comment]
Turns out there are lots of silly websites for hosting files for you.  Here is the trace:
http://s000.tinyupload.com/index.php?file_id=43983567511915922445

**Comment by eseidelGoogle** [comment]
I would expect some of the 6.5 seconds to disappear on a second load of Stocks App, but I guess we don't have any caching in our oknet NetworkService implementation at the moment?

**Comment by abarth** [comment]
You could try reverting https://github.com/domokit/mojo/commit/9b03c575a4e12f80739d1de7d2c6d66a7cdb214a to see if that helps.

**Comment by eseidelGoogle** [comment]
Reverted in https://github.com/domokit/mojo/commit/d27d79360296a822966cc0f6d46660767c271b78

**Comment by abarth** [comment]
These now load in less than a second.
