### ISSUE TITLE
dart:mirrors.currentMirrorSystem crashes in sky

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#98]
I tried this:

import "dart:mirrors" as mirrors;

...

var m = mirrors.currentMirrorSystem();

in SkyShell and crashed with this:

Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  dart::Smi::ValueFromRaw(unsigned int)                                             /ssd/mojo/src/out/android_Release/../../dart/runtime/vm/object.h:5519
  v------>  dart::Smi::Value(dart::RawSmi const*)                                             /ssd/mojo/src/out/android_Release/../../dart/runtime/vm/object.h:5486
  v------>  dart::String::Length() const                                                      /ssd/mojo/src/out/android_Release/../../dart/runtime/vm/object.h:5766
  v------>  _ZN4dart6String17CodePointIteratorC4ERKS0_                                        /ssd/mojo/src/out/android_Release/../../dart/runtime/vm/object.h:5737
  0043ac74  dart::String::Equals(char const*) const                                           /ssd/mojo/src/out/android_Release/../../dart/runtime/vm/object.cc:17471
  00325ed1  CreateLibraryMirror                                                               /ssd/mojo/src/out/android_Release/../../dart/runtime/lib/mirrors.cc:364
  v------>  CreateIsolateMirror                                                               /ssd/mojo/src/out/android_Release/../../dart/runtime/lib/mirrors.cc:533
  v------>  CreateMirrorSystem                                                                /ssd/mojo/src/out/android_Release/../../dart/runtime/lib/mirrors.cc:561
  v------>  DN_HelperMirrors_makeLocalMirrorSystem                                            /ssd/mojo/src/out/android_Release/../../dart/runtime/lib/mirrors.cc:775
  00326211  dart::BootstrapNatives::DN_Mirrors_makeLocalMirrorSystem(_Dart_NativeArguments*)  /ssd/mojo/src/out/android_Release/../../dart/runtime/lib/mirrors.cc:774
  00000138

**Comment by eseidelGoogle** [comment]
I think @Hixie hit something similar?

**Comment by eseidelGoogle** [comment]
static RawInstance* CreateLibraryMirror(const Library& lib) {
  const Array& args = Array::Handle(Array::New(3));
  args.SetAt(0, MirrorReference::Handle(MirrorReference::New(lib)));
  String& str = String::Handle();
  str = lib.name();
  args.SetAt(1, str);
  str = lib.url();
  if (str.Equals("dart:_builtin") || str.Equals("dart:_blink")) {
    // Censored library (grumble).
    return Instance::null();
  }
  args.SetAt(2, str);
  return CreateMirror(Symbols::_LocalLibraryMirror(), args);
}

The line we crash on is:
  if (str.Equals("dart:_builtin") || str.Equals("dart:_blink")) {

**Comment by eseidelGoogle** [comment]
Presumably one of the libraries we're asking for is missing a name or url?

**Comment by eseidelGoogle** [comment]
We debugged this a little locally.  The Library we're crashing on has a number as a URL.

Library:'67329'
Library:'dart:core' Class: _Smi@915557746

**Comment by eseidelGoogle** [comment]
Here is the debugging setup:

Here is the patch we used to dart/runtime:

Index: lib/mirrors.cc
===================================================================
--- lib/mirrors.cc (revision 45060)
+++ lib/mirrors.cc (working copy)
@@ -358,9 +358,11 @@
   const Array& args = Array::Handle(Array::New(3));
   args.SetAt(0, MirrorReference::Handle(MirrorReference::New(lib)));
   String& str = String::Handle();
+  lib.Print();
   str = lib.name();
   args.SetAt(1, str);
   str = lib.url();
+  Object::Handle(str.clazz()).Print();
   if (str.Equals("dart:_builtin") || str.Equals("dart:_blink")) {
     // Censored library (grumble).
     return Instance::null();
Index: vm/object.cc
===================================================================
--- vm/object.cc (revision 45060)
+++ vm/object.cc (working copy)
@@ -9526,6 +9526,7 @@
 
 RawLibrary* Library::NewLibraryHelper(const String& url,
                                       bool import_core_lib) {
+  ASSERT(Object::Handle(url.raw()).IsString());
   const Library& result = Library::Handle(Library::New());
   result.StorePointer(&result.raw_ptr()->name_, Symbols::Empty().raw());
   result.StorePointer(&result.raw_ptr()->url_, url.raw());
@@ -9567,6 +9568,7 @@
 
 
 RawLibrary* Library::New(const String& url) {
+  ASSERT(Object::Handle(url.raw()).IsString());
   return NewLibraryHelper(url, false);
 }
 

You need to build mojo:

fetch mojo (you likely did this already)
cd mojo/src/
./mojo/tools/mojob.py gn
./mojo/tools/mojob.py build
./sky/tools/skydb start out/Debug crash_test.sky


% cat crash_test.sky
#!mojo mojo:sky_viewer
<sky>
<script>
import 'sky_home.dart';
import "dart:mirrors" as mirrors;

void main() {
  var m = mirrors.currentMirrorSystem();
}
</script>
</sky>

**Comment by eseidelGoogle** [comment]
Met with @rmacnak-google and @iposva-google and we learned that Sky is never calling Dart_LoadScript, only using Dart_LoadLibrary, which means we never set the "root library".  This root_library concept is only used by mirrors and observatory (fyi @johnmccutchan) hence why this was the first time we were crashing this way.  The resolution was to fix mirrors to not care about the root_library being null.

We also are discussing (after the dart summit) changing the way that dart_controller.cc works in sky to use main.dart instead of main.sky as an entry point, at which point we'll likely use Dart_LoadScript anyway.

**Comment by rmacnak-google** [comment]
Isolate.spawnUri also cares about the root library, so loading an empty library via Dart_LoadScript seems the way to go.
