### ISSUE TITLE
mojo:kiosk_wm crash on resume on android

### ISSUE THREAD

**Issue by emembrives** [domokit/mojo#99]
Steps to reproduce:
1. `mojo/tools/mojob.py build --android`
2. `./mojo/tools/android_mojo_shell.py --content-handlers=image/png,mojo:png_viewer --url-mappings=mojo:window_manager=mojo:kiosk_wm --args-for="mojo:window_manager http://upload.wikimedia.org/wikipedia/commons/9/9a/PNG_transparency_demonstration_2.png" mojo:window_manager`
3. The image loads
4. Navigate away from MojoShell (hit the Home button)
5. Go back to MojoShell through the app switcher
6. Behold the magnificent black screen!
7. Rotate the screen and see MojoShell crash

This crash can be reproduced with png_viewer and sky_viewer through kiosk_wm, but not with bare surfaces_app and spinning_cube, so this seems a kiosk_wm problem rather than a pure shell problem.

**Comment by emembrives** [comment]
I compared the execution of `mojo:spinning_cube` and `mojo:kiosk_wm`. It appears that:
 - when the android activity starts, both apps initialize a `CommandBuffer` (`CommandBufferImpl::Initialize` is called).
 - when the android activity pauses, `spinning_cube` receives an `OnGLContextLost` which `kiosk_wm` either do not receive or ignores.
 - when the android activity resumes, `spinning_cube` generates a new call to `CommandBufferImpl::Initialize`; this method is never called again by `kiosk_wm`.

I believe the difference in behavior explains the crash of `kiosk_wm`. Still investigating...

**Comment by emembrives** [comment]
More notes: `mojo:kiosk_wm` is using `native_viewport`, which does *not* use `MojoGLES2CreateContext` to create a surface to draw on. `services/native_viewport/platform_viewport_android.(h|cc)` contain the code that creates a custom Android `SurfaceView`. `SurfaceDestroyed` is called (rightly) when the android activity is paused. We need to find a way to bubble that info up the stack so that all views and listeners are re-initialized on resume.

**Comment by sky2** [comment]
Views shouldn't need to be reinitialized, right? Maybe you mean recreate their surfaces?

I spoke with James a while back about what needs to happen and he had mentioned Adam was looking into this. That was likely right before Adam went on vacation. James might know what needs to happen here.

**Comment by jamesr** [comment]
Right. I made a fair amount of forward progress on this a few weeks back but didn't finish it. I suggest studying mojo:surfaces_app, which did recover correctly, with mojo:ganesh_app (run it in skydb) which does not recover and is the next simplest app in terms of dependencies. I'm on vacation today but can look more on Monday

**Comment by emembrives** [comment]
@sky2: I don't know exactly what needs to be done. By "re-initialized", I just mean redo whatever setup is needed (be it initialization, creation, etc...).

@jamesr: I would be happy do sync with you, so we both don't waste work on this.

Today investigations: Adding `  delegate_->OnDestroyed();` to `PlatformViewportAndroid::SurfaceDestroyed` prevents the shell from crashing, but still does not solve the bigger issue. When I do that, `PlatformViewportAndroid::SurfaceCreated` is called when the app is resumed, but I still get a blank screen.

**Comment by emembrives** [comment]
I think the solution is somehow linked to [this changelist](https://github.com/domokit/mojo/commit/187e1faf437be935fe55ae769f0ecc19ce4c3db4) from @jamesr. From what I understood, there are two kinds of "drawable" objects, ie. objects you can post a frame to: `Display` and `Surface`. There is only one `Display`, and there can be many embedded `Surfaces`.

When one does `Display::SubmitFrame()`, the system ends up calling `CommandBufferDriver::Flush` which detects the context is no longer valid, and then calls `CommandBufferDriver::OnContextLost`. This leads to the following linked issues (in no particular order):
- `Surface::SubmitFrame` had no knowledge of the root display, or of command buffer, so calling it does nothing special.
- Neither `Display` nor `CommandBufferDriver` receive information on surface deletion by `native_viewport_service`, but need someone trying to submit a frame to detect the problem
- So, if an application uses only `Surfaces`, it has no way of recovering from an Activity pause

My current thinking is to extend the `NativeViewport` interface to include a `NativeViewportStatusObserver` which could receive creation/destruction events.

It is very likely, however, that I am still missing some critical pieces or that my reasoning is lacking, so any comment is welcome.

**Comment by jamesr** [comment]
mojo:surfaces_app uses only Surfaces and it recovers fine from being backgrounded.  That part of the system works fine, it's higher layer things that are failing to recover.  My guess would be that we aren't notifying apps that the *resources* they submitted have been lost so they know that they need to generate new ones and submit them.

**Comment by emembrives** [comment]
@jamesr: I haven't found any code in `mojo:surfaces_app` to recover anything. It is all done at lower layers that `mojo:surfaces_app` has no access to. And, from what I saw, it only works because [line 96@embedder.cc](https://github.com/domokit/mojo/blob/master/examples/surfaces_app/embedder.cc#L96) calls `SubmitFrame` on a `Display` every 10 ticks and not on a `Surface`.

**Comment by jamesr** [comment]
mojo:surfaces_app doesn't use any resources, so it doesn't have to do anything in particular to recover.  The surfaces service *does* detect that its context is lost and constructs a new one.  See DisplayImpl::OutputSurfaceLost.  Clients that are using resources need to also learn that their resources are lost and regenerate them.

**Comment by emembrives** [comment]
I may have missed something, but during my tests, `DisplayImpl::OutputSurfaceLost` is *not* called when, for example, sky_viewer is started and the android activity is paused. 

The resources problem is also real and will need to be addressed, but it is not the only one.

**Comment by emembrives** [comment]
It turns out I did miss something. My previous [partial fix](https://github.com/domokit/mojo/issues/99#issuecomment-94485907) wasn't good at all (case in point: `NativeViewport::OnDestroyed` should *not* be called when the native surface is destroyed ...). Without this "fix", actually, the next `PostFrame` on anything will trigger the context checking, and propagating an OnContextLost event.

**Comment by colinblundell** [comment]
Fixed by https://codereview.chromium.org/1110423002/. etiennej@ did all the heavy lifting here. Thanks, Etienne!
